#ifndef INCLUDE_RUBY_CONFIG_H
#define INCLUDE_RUBY_CONFIG_H 1
/* ---------------------------------------------------------------------------
 * The MSVC view of the external CRuby in bind/external.
 *
 * bind/external is a *prebuilt* CRuby whose headers were generated by a MinGW
 * build; its arch directory is `include/ruby-<ver>/x64-mingw64/ruby/config.h`.
 * That file is not usable from MSVC: it claims POSIX headers the Windows SDK
 * does not ship (`<strings.h>`, `<unistd.h>`, `<dirent.h>`), spells keywords
 * with GCC syntax (`#define restrict __restrict__`, which turns the UCRT's own
 * `__declspec(restrict)` into the unrecognised attribute `__restrict__`), and
 * maps types through the POSIX names MinGW's `<sys/types.h>` happens to
 * provide but the UCRT does not (`ssize_t`, `pid_t`).
 *
 * So this file takes its place: it is the `ruby/config.h` the build resolves
 * for the external interpreter.  It is a direct transcription of the config.h
 * that Ruby's own `win32/Makefile.sub` generates for MSVC x64, with the ABI
 * facts taken from the MinGW file so that the host and the DLL agree:
 *
 *   * RUBY_ABI_VERSION / RUBY_MSVCRT_VERSION, and every SIZEOF_* below, are
 *     the values from the MinGW config.h.  They describe the DLL, not us.
 *   * `#define USE_YJIT 1` is likewise the DLL's: bind/external is a CRuby
 *     built with YJIT, which is what makes the interpreter swap worth doing.
 *   * everything else is the MSVC spelling of the same fact -- `__declspec`
 *     instead of `__attribute__`, `<sys/utime.h>` instead of `<utime.h>`,
 *     `_setjmp` instead of `__builtin_setjmp`.
 *
 * Keeping it a separate file, rather than patching the MinGW one through
 * Ruby's RUBY_EXTCONF_H hook, is deliberate: the two disagree on more than
 * they agree on, and a config.h is a document about the target, not about the
 * compiler that happens to read it.
 *
 * Consumed through bind/CMakeLists.txt, which puts this directory on the
 * include path and deliberately leaves `x64-mingw64/` off it -- the arch
 * directory holds nothing but the config.h this file replaces.
 * --------------------------------------------------------------------------- */

/* The ABI the DLL was built with (Ruby 4.1.0+4).  ruby/internal/abi.h
   re-checks this against the number compiled into the DLL. */
#define RUBY_ABI_VERSION 4
#define RUBY_MSVCRT_VERSION 140

#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_AFUNIX_H 1
#define HAVE_LONG_LONG 1
#define HAVE_OFF_T 1

/* The UCRT's off_t is 32 bits; the DLL's is 64 (`_FILE_OFFSET_BITS 64` in the
   MinGW build).  rb_off_t is what crosses the boundary, so it has to be the
   DLL's width, not the header's. */
#define rb_off_t __int64
#define SIGNEDNESS_OF_OFF_T -1
#define OFFT2NUM(v) LL2NUM(v)
#define NUM2OFFT(v) NUM2LL(v)
#define SIZEOF_OFF_T 8

#define SIZEOF_INT 4
#define SIZEOF_SHORT 2
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF___INT64 8
#ifndef _INTEGRAL_MAX_BITS
#define _INTEGRAL_MAX_BITS 64
#endif
#define SIZEOF_VOIDP 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIGNEDNESS_OF_TIME_T -1
#define NEGATIVE_TIME_T 1
#define SIZEOF_TIME_T 8
#define TIMET2NUM(v) LL2NUM(v)
#define NUM2TIMET(v) NUM2LL(v)
#define CLOCKID2NUM(v) INT2NUM(v)
#define NUM2CLOCKID(v) NUM2INT(v)
#define SIZEOF_CLOCK_T 4
#define SIZEOF_RLIM_T 0
#define SIZEOF_SIZE_T 8
#define SIZEOF_PTRDIFF_T 8
#define SIZEOF_INTPTR_T 8
#define SIZEOF_UINTPTR_T 8

/* The MSVC spelling of the function attributes the MinGW config.h writes with
   __attribute__.  The ones MSVC has no equivalent for degrade to a no-op
   rather than to a syntax error. */
#define HAVE_VA_COPY 1
#define NORETURN(x) __declspec(noreturn) x
#define DEPRECATED(x) __declspec(deprecated) x
#define RUBY_CXX_DEPRECATED(mesg) __declspec(deprecated(mesg))
#define NOINLINE(x) __declspec(noinline) x
#define ALWAYS_INLINE(x) __forceinline x
#define WARN_UNUSED_RESULT(x) x
#define MAYBE_UNUSED(x) x
#define HAVE___ASSUME 1
#define FUNC_STDCALL(x) __stdcall x
#define FUNC_CDECL(x) __cdecl x
#define FUNC_FASTCALL(x) __fastcall x
#define RUBY_FUNCTION_NAME_STRING __FUNCTION__
#define RBIMPL_ATTR_PACKED_STRUCT_BEGIN() __pragma(pack(push, 1))
#define RBIMPL_ATTR_PACKED_STRUCT_END() __pragma(pack(pop))
#define RUBY_ALIGNAS(n) __declspec(align(n))
#define RUBY_ALIGNOF __alignof

/* No `HAVE_FUNC_WEAK` / `HAVE_GCC_ATOMIC_BUILTINS` / `HAVE_TYPEOF` /
   `HAVE_BUILTIN___BUILTIN_*` / `HAVE_INT128_T`: those are the GCC features
   ruby/internal/abi.h, ruby/atomic.h and ruby/internal/memory.h probe for
   precisely so that they can fall back to MSVC intrinsics.  Defining them
   here would send those headers down the GCC path. */

/* MinGW has no `ssize_t` in the Windows SDK either; the MinGW config.h gets it
   from its own <sys/types.h>, and ruby/internal/intern/bignum.h documents that
   on Windows the type is expected to be `#define`d here instead. */
#define HAVE_SSIZE_T 1
#define ssize_t __int64
#define PRI_PTR_PREFIX "I64"
#define PRI_LL_PREFIX "I64"

/* The POSIX scalar names the UCRT does not declare.  These are plain `int` in
   both builds, so the DLL and the host agree. */
#define rb_pid_t int
#define rb_gid_t int
#define rb_uid_t int
#define PRI_PIDT_PREFIX PRI_INT_PREFIX
#define GETGROUPS_T int

#define HAVE_STRUCT_STAT_ST_RDEV 1
#define HAVE_STRUCT_TIMEVAL 1
#define HAVE_STRUCT_TIMESPEC
#define TYPEOF_TIMEVAL_TV_SEC long

#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_INT8_T 1
#define HAVE_UINT8_T 1
#define SIZEOF_INT8_T 1
#define SIZEOF_UINT8_T 1
#define HAVE_INT16_T 1
#define HAVE_UINT16_T 1
#define SIZEOF_INT16_T 2
#define SIZEOF_UINT16_T 2
#define HAVE_INT32_T 1
#define HAVE_UINT32_T 1
#define SIZEOF_INT32_T 4
#define SIZEOF_UINT32_T 4
#define HAVE_INT64_T 1
#define HAVE_UINT64_T 1
#define SIZEOF_INT64_T 8
#define SIZEOF_UINT64_T 8
#define HAVE_INTPTR_T 1
#define HAVE_UINTPTR_T 1

#define HAVE_ACOSH 1
#define HAVE_ASINH 1
#define HAVE_ATANH 1
#define HAVE_CBRT 1
#define HAVE_LOG2 1
#define log2(x) log2(x)
#define HAVE_ERF 1
#define HAVE_ERFC 1
#define HAVE_ROUND 1
#define HAVE_TGAMMA 1
#define HAVE_NEXTAFTER 1
#define HAVE_ALLOCA 1
#define HAVE_DUP2 1
#define HAVE_MEMCMP 1
#define HAVE_MEMMOVE 1
#define HAVE_MKDIR 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CLOCK_GETRES 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_SPAWNV 1
#define HAVE_STRCASECMP 1
#define HAVE_STRNCASECMP 1
#define HAVE_STRERROR 1
#define HAVE_STRFTIME 1
#define HAVE_STRCHR 1
#define HAVE_STRSTR 1
#define HAVE_FLOCK 1
#define HAVE_ISINF 1
#define HAVE_ISNAN 1
#define HAVE_FINITE 1
#define HAVE_NAN 1
#define HAVE_HYPOT 1
#define HAVE_FMOD 1
#define HAVE_FREXP 1
#define HAVE_MODF 1
#define HAVE_WAITPID 1
#define HAVE_FSYNC 1
#define HAVE_GETCWD 1
#define HAVE_TRUNCATE 1
#define HAVE_FTRUNCATE 1
#define HAVE_LSTAT 1
#define HAVE_TIMES 1
#define HAVE_FCNTL 1
#define HAVE_LINK 1
#define HAVE_READLINK 1
#define HAVE_SYMLINK 1
#define HAVE_LCHOWN 1
#define HAVE__SETJMP 1
#define HAVE_TELLDIR 1
#define HAVE_SEEKDIR 1
#define HAVE_MKTIME 1
#define HAVE_COSH 1
#define HAVE_SINH 1
#define HAVE_TANH 1
#define HAVE_SIGNBIT 1
#define HAVE_TZNAME 1
#define HAVE_DAYLIGHT 1
#define HAVE_GMTIME_R 1
#define HAVE_CHMOD 1
#define HAVE_CHOWN 1
#define HAVE_DUP 1
#define HAVE_EXECL 1
#define HAVE_EXECLE 1
#define HAVE_EXECV 1
#define HAVE_EXECVE 1
#define HAVE_GETEGID 1
#define HAVE_GETEUID 1
#define HAVE_GETGID 1
#define HAVE_GETUID 1
#define HAVE_PCLOSE 1
#define HAVE_PIPE 1
#define HAVE_POPEN 1
#define HAVE_SHUTDOWN 1
#define HAVE_SYSTEM 1
#define HAVE_TZSET 1
#define HAVE_UMASK 1
#define HAVE_QSORT_S
#define HAVE_TYPE_NET_LUID 1
#define HAVE_NULLPTR 1
#define HAVE_DECL_SYS_NERR 1
#define SETPGRP_VOID 1

/* ruby/win32.h picks `<sys/utime.h>` over `<utime.h>` on this switch, and the
   UCRT ships the rest of these under their usual names. */
#define HAVE_LIMITS_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_UTIME_H 1
#define HAVE_FLOAT_H 1
#define HAVE_TIME_H 1
#define HAVE_SETJMPEX_H 1
#define HAVE_DIRECT_H 1
#define HAVE_PROCESS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_STDALIGN_H 1

#define RSHIFT(x,y) ((x)>>(int)y)
#define HAVE_RB_FD_INIT 1
#define RUBY_SETJMP(env) _setjmp(env)
#define RUBY_LONGJMP(env,val) longjmp(env,val)
#define RUBY_JMP_BUF jmp_buf

/* The MinGW config.h defines `restrict` for both C and C++, where it clobbers
   the UCRT's `__declspec(restrict)`.  MSVC only needs the alias in C, and
   `__restrict` is the spelling its own headers use. */
#ifndef __cplusplus
#define inline __inline
#define restrict __restrict
#endif

#define NEED_IO_SEEK_BETWEEN_RW 1
#define STACK_GROW_DIRECTION -1
#define THREAD_IMPL_H "thread_win32.h"
#define THREAD_IMPL_SRC "thread_win32.c"
#define LOAD_RELATIVE 1
#define DLEXT ".so"
#define SOEXT ".dll"
#define LIBDIR_BASENAME "lib"

/* bind/external is a CRuby with YJIT compiled in -- the reason this whole
   interpreter swap exists.  cruby_main.cc reads it back through
   URGE_EXTERNAL_RUBY and turns the engine on. */
#define USE_YJIT 1
#define USE_ZJIT 0

#define EXECUTABLE_EXTS ".exe",".com",".cmd",".bat"
#define RUBY_PLATFORM "x64-mswin64"
#define RB_DEFAULT_PARSER RB_DEFAULT_PARSER_PRISM
#endif /* INCLUDE_RUBY_CONFIG_H */
