// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_render_pipeline_descriptor.h"

#include "binding_gpu_object.h"
#include "binding_gpu_pipeline_layout.h"
#include "binding_gpu_shader_module.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPURenderPipelineDescriptor  (core/gpu.h:487-551)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPURenderPipelineDescriptor, GPUObject);

RB_FUNC(GPURenderPipelineDescriptor_initialize) {
  urge::RefPtr<urge::GPURenderPipelineDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPURenderPipelineDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPURenderPipelineDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPURenderPipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPipelineDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPURenderPipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPipelineDescriptor_GetVertexEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPURenderPipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetVertexEntryPoint();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPipelineDescriptor_SetVertexEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPURenderPipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetVertexEntryPoint(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPipelineDescriptor_GetFragmentEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPURenderPipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetFragmentEntryPoint();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPipelineDescriptor_SetFragmentEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPURenderPipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetFragmentEntryPoint(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPipelineDescriptor_AddVertexAttribute) {
  auto* self_obj = GetSelfData<urge::GPURenderPipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    uint32_t location, format;
    uint64_t offset;
    ParseArgs(argc, argv, "uup", &location, &format, &offset);

    self_obj->AddVertexAttribute(location, format, offset);
  }
  EXC_END;
  return Qnil;
}

// Attribute: layout (RefPtr<GPUPipelineLayout>)
BINDING_ATTR_OBJECT_REF(GPURenderPipelineDescriptor,
                        urge::GPURenderPipelineDescriptor,
                        Layout,
                        urge::GPUPipelineLayout,
                        kGPUPipelineLayoutDataType);

// Attribute: vertex_module (RefPtr<GPUShaderModule>)
BINDING_ATTR_OBJECT_REF(GPURenderPipelineDescriptor,
                        urge::GPURenderPipelineDescriptor,
                        VertexModule,
                        urge::GPUShaderModule,
                        kGPUShaderModuleDataType);

// Attribute: fragment_module (RefPtr<GPUShaderModule>)
BINDING_ATTR_OBJECT_REF(GPURenderPipelineDescriptor,
                        urge::GPURenderPipelineDescriptor,
                        FragmentModule,
                        urge::GPUShaderModule,
                        kGPUShaderModuleDataType);

// Attribute: topology (uint32_t)
BINDING_ATTR_INT(GPURenderPipelineDescriptor,
                 urge::GPURenderPipelineDescriptor,
                 Topology);

// Attribute: format (uint32_t)
BINDING_ATTR_INT(GPURenderPipelineDescriptor,
                 urge::GPURenderPipelineDescriptor,
                 Format);

// Attribute: vertex_stride (uint32_t)
BINDING_ATTR_INT(GPURenderPipelineDescriptor,
                 urge::GPURenderPipelineDescriptor,
                 VertexStride);

void InitGPURenderPipelineDescriptorBindingAppend(VALUE klass);

void InitGPURenderPipelineDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPURenderPipelineDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPURenderPipelineDescriptorDataType>);

  DefineMethod(klass, "initialize", GPURenderPipelineDescriptor_initialize);
  DefineMethod(klass, "label", GPURenderPipelineDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPURenderPipelineDescriptor_SetLabel);
  DefineMethod(klass, "vertex_entry_point", GPURenderPipelineDescriptor_GetVertexEntryPoint);
  DefineMethod(klass, "vertex_entry_point=", GPURenderPipelineDescriptor_SetVertexEntryPoint);
  DefineMethod(klass, "fragment_entry_point", GPURenderPipelineDescriptor_GetFragmentEntryPoint);
  DefineMethod(klass, "fragment_entry_point=", GPURenderPipelineDescriptor_SetFragmentEntryPoint);
  DefineMethod(klass, "add_vertex_attribute", GPURenderPipelineDescriptor_AddVertexAttribute);
  DefineMethod(klass, "layout", GPURenderPipelineDescriptor_Layout);
  DefineMethod(klass, "layout=", GPURenderPipelineDescriptor_LayoutEqual);
  DefineMethod(klass, "vertex_module", GPURenderPipelineDescriptor_VertexModule);
  DefineMethod(klass, "vertex_module=", GPURenderPipelineDescriptor_VertexModuleEqual);
  DefineMethod(klass, "fragment_module", GPURenderPipelineDescriptor_FragmentModule);
  DefineMethod(klass, "fragment_module=", GPURenderPipelineDescriptor_FragmentModuleEqual);
  DefineMethod(klass, "topology", GPURenderPipelineDescriptor_Topology);
  DefineMethod(klass, "topology=", GPURenderPipelineDescriptor_TopologyEqual);
  DefineMethod(klass, "format", GPURenderPipelineDescriptor_Format);
  DefineMethod(klass, "format=", GPURenderPipelineDescriptor_FormatEqual);
  DefineMethod(klass, "vertex_stride", GPURenderPipelineDescriptor_VertexStride);
  DefineMethod(klass, "vertex_stride=", GPURenderPipelineDescriptor_VertexStrideEqual);
  InitGPURenderPipelineDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPURenderPipelineDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPURenderPipelineDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
