// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_effect.h"

#include "binding_bitmap.h"

#include "core/bitmap.h"
#include "core/effect.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Effect  (core/effect.h:64-76)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Effect);

RB_FUNC(Effect_initialize) {
  urge::RefPtr<urge::Effect> obj = nullptr;
  EXC_BEGIN {
    if (argc == 2) {
      // initialize(vs_glsl, fs_glsl)
      std::string vs_glsl, fs_glsl;
      ParseArgs(argc, argv, "ss", &vs_glsl, &fs_glsl);
      obj = urge::MakeRefCounted<urge::Effect>(vs_glsl, fs_glsl);
    } else if (argc == 3) {
      // initialize(vs_glsl, fs_glsl, blend_states)
      std::string vs_glsl, fs_glsl, blend_states;
      ParseArgs(argc, argv, "sss", &vs_glsl, &fs_glsl, &blend_states);
      obj = urge::MakeRefCounted<urge::Effect>(vs_glsl, fs_glsl, blend_states);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Effect_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Effect> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Effect>(other, kEffectDataType);
    obj = urge::MakeRefCounted<urge::Effect>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Effect_SetFloat) {
  auto* self_obj = GetSelfData<urge::Effect>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t slot;
    VALUE data_val;
    ParseArgs(argc, argv, "uo", &slot, &data_val);

    self_obj->SetFloat(slot, GetVectorOf<float>(data_val));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Effect_SetInt) {
  auto* self_obj = GetSelfData<urge::Effect>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t slot;
    VALUE data_val;
    ParseArgs(argc, argv, "uo", &slot, &data_val);

    self_obj->SetInt(slot, GetVectorOf<int32_t>(data_val));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Effect_SetTexture) {
  auto* self_obj = GetSelfData<urge::Effect>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t slot;
    VALUE texture_val;
    ParseArgs(argc, argv, "uo", &slot, &texture_val);

    self_obj->SetTexture(slot,
        GetObject<urge::Bitmap>(texture_val, kBitmapDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Effect_SetSampler) {
  auto* self_obj = GetSelfData<urge::Effect>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t slot;
    VALUE texture_val;
    ParseArgs(argc, argv, "uo", &slot, &texture_val);

    self_obj->SetSampler(slot,
        GetObject<urge::Bitmap>(texture_val, kBitmapDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Effect_SetBlock) {
  auto* self_obj = GetSelfData<urge::Effect>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t slot;
    std::string uniform_block;
    ParseArgs(argc, argv, "us", &slot, &uniform_block);

    self_obj->SetBlock(slot, uniform_block);
  }
  EXC_END;
  return Qnil;
}

void InitEffectBindingAppend(VALUE klass);

void InitEffectBinding() {
  auto klass = rb_define_class("Effect", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kEffectDataType>);

  DefineMethod(klass, "initialize", Effect_initialize);
  DefineMethod(klass, "initialize_copy", Effect_initialize_copy);
  DefineMethod(klass, "set_float", Effect_SetFloat);
  DefineMethod(klass, "set_int", Effect_SetInt);
  DefineMethod(klass, "set_texture", Effect_SetTexture);
  DefineMethod(klass, "set_sampler", Effect_SetSampler);
  DefineMethod(klass, "set_block", Effect_SetBlock);
  InitEffectBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitEffectBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitEffectBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
