// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_compute_pass_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUComputePassDescriptor  (core/gpu.h:637-644)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUComputePassDescriptor, GPUObject);

RB_FUNC(GPUComputePassDescriptor_initialize) {
  urge::RefPtr<urge::GPUComputePassDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUComputePassDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUComputePassDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUComputePassDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUComputePassDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUComputePassDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

void InitGPUComputePassDescriptorBindingAppend(VALUE klass);

void InitGPUComputePassDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUComputePassDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUComputePassDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUComputePassDescriptor_initialize);
  DefineMethod(klass, "label", GPUComputePassDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUComputePassDescriptor_SetLabel);
  InitGPUComputePassDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUComputePassDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUComputePassDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
