// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_texture_view_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUTextureViewDescriptor  (core/gpu.h:171-217)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUTextureViewDescriptor, GPUObject);

RB_FUNC(GPUTextureViewDescriptor_initialize) {
  urge::RefPtr<urge::GPUTextureViewDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUTextureViewDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUTextureViewDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUTextureViewDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTextureViewDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUTextureViewDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: format (uint32_t)
BINDING_ATTR_INT(GPUTextureViewDescriptor,
                 urge::GPUTextureViewDescriptor,
                 Format);

// Attribute: dimension (uint32_t)
BINDING_ATTR_INT(GPUTextureViewDescriptor,
                 urge::GPUTextureViewDescriptor,
                 Dimension);

// Attribute: base_mip_level (uint32_t)
BINDING_ATTR_INT(GPUTextureViewDescriptor,
                 urge::GPUTextureViewDescriptor,
                 BaseMipLevel);

// Attribute: mip_level_count (uint32_t)
BINDING_ATTR_INT(GPUTextureViewDescriptor,
                 urge::GPUTextureViewDescriptor,
                 MipLevelCount);

// Attribute: base_array_layer (uint32_t)
BINDING_ATTR_INT(GPUTextureViewDescriptor,
                 urge::GPUTextureViewDescriptor,
                 BaseArrayLayer);

// Attribute: array_layer_count (uint32_t)
BINDING_ATTR_INT(GPUTextureViewDescriptor,
                 urge::GPUTextureViewDescriptor,
                 ArrayLayerCount);

// Attribute: aspect (uint32_t)
BINDING_ATTR_INT(GPUTextureViewDescriptor,
                 urge::GPUTextureViewDescriptor,
                 Aspect);

void InitGPUTextureViewDescriptorBindingAppend(VALUE klass);

void InitGPUTextureViewDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUTextureViewDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUTextureViewDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUTextureViewDescriptor_initialize);
  DefineMethod(klass, "label", GPUTextureViewDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUTextureViewDescriptor_SetLabel);
  DefineMethod(klass, "format", GPUTextureViewDescriptor_Format);
  DefineMethod(klass, "format=", GPUTextureViewDescriptor_FormatEqual);
  DefineMethod(klass, "dimension", GPUTextureViewDescriptor_Dimension);
  DefineMethod(klass, "dimension=", GPUTextureViewDescriptor_DimensionEqual);
  DefineMethod(klass, "base_mip_level", GPUTextureViewDescriptor_BaseMipLevel);
  DefineMethod(klass, "base_mip_level=", GPUTextureViewDescriptor_BaseMipLevelEqual);
  DefineMethod(klass, "mip_level_count", GPUTextureViewDescriptor_MipLevelCount);
  DefineMethod(klass, "mip_level_count=", GPUTextureViewDescriptor_MipLevelCountEqual);
  DefineMethod(klass, "base_array_layer", GPUTextureViewDescriptor_BaseArrayLayer);
  DefineMethod(klass, "base_array_layer=", GPUTextureViewDescriptor_BaseArrayLayerEqual);
  DefineMethod(klass, "array_layer_count", GPUTextureViewDescriptor_ArrayLayerCount);
  DefineMethod(klass, "array_layer_count=", GPUTextureViewDescriptor_ArrayLayerCountEqual);
  DefineMethod(klass, "aspect", GPUTextureViewDescriptor_Aspect);
  DefineMethod(klass, "aspect=", GPUTextureViewDescriptor_AspectEqual);
  InitGPUTextureViewDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUTextureViewDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUTextureViewDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
