// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_sampler_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUSamplerDescriptor  (core/gpu.h:236-300)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUSamplerDescriptor, GPUObject);

RB_FUNC(GPUSamplerDescriptor_initialize) {
  urge::RefPtr<urge::GPUSamplerDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUSamplerDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUSamplerDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUSamplerDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUSamplerDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUSamplerDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: address_mode_u (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor,
                 urge::GPUSamplerDescriptor,
                 AddressModeU);

// Attribute: address_mode_v (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor,
                 urge::GPUSamplerDescriptor,
                 AddressModeV);

// Attribute: address_mode_w (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor,
                 urge::GPUSamplerDescriptor,
                 AddressModeW);

// Attribute: mag_filter (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor, urge::GPUSamplerDescriptor, MagFilter);

// Attribute: min_filter (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor, urge::GPUSamplerDescriptor, MinFilter);

// Attribute: mipmap_filter (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor,
                 urge::GPUSamplerDescriptor,
                 MipmapFilter);

// Attribute: lod_min_clamp (float)
BINDING_ATTR_FLOAT(GPUSamplerDescriptor,
                   urge::GPUSamplerDescriptor,
                   LodMinClamp);

// Attribute: lod_max_clamp (float)
BINDING_ATTR_FLOAT(GPUSamplerDescriptor,
                   urge::GPUSamplerDescriptor,
                   LodMaxClamp);

// Attribute: compare (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor, urge::GPUSamplerDescriptor, Compare);

// Attribute: max_anisotropy (uint32_t)
BINDING_ATTR_INT(GPUSamplerDescriptor,
                 urge::GPUSamplerDescriptor,
                 MaxAnisotropy);

void InitGPUSamplerDescriptorBindingAppend(VALUE klass);

void InitGPUSamplerDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUSamplerDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUSamplerDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUSamplerDescriptor_initialize);
  DefineMethod(klass, "label", GPUSamplerDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUSamplerDescriptor_SetLabel);
  DefineMethod(klass, "address_mode_u", GPUSamplerDescriptor_AddressModeU);
  DefineMethod(klass, "address_mode_u=", GPUSamplerDescriptor_AddressModeUEqual);
  DefineMethod(klass, "address_mode_v", GPUSamplerDescriptor_AddressModeV);
  DefineMethod(klass, "address_mode_v=", GPUSamplerDescriptor_AddressModeVEqual);
  DefineMethod(klass, "address_mode_w", GPUSamplerDescriptor_AddressModeW);
  DefineMethod(klass, "address_mode_w=", GPUSamplerDescriptor_AddressModeWEqual);
  DefineMethod(klass, "mag_filter", GPUSamplerDescriptor_MagFilter);
  DefineMethod(klass, "mag_filter=", GPUSamplerDescriptor_MagFilterEqual);
  DefineMethod(klass, "min_filter", GPUSamplerDescriptor_MinFilter);
  DefineMethod(klass, "min_filter=", GPUSamplerDescriptor_MinFilterEqual);
  DefineMethod(klass, "mipmap_filter", GPUSamplerDescriptor_MipmapFilter);
  DefineMethod(klass, "mipmap_filter=", GPUSamplerDescriptor_MipmapFilterEqual);
  DefineMethod(klass, "lod_min_clamp", GPUSamplerDescriptor_LodMinClamp);
  DefineMethod(klass, "lod_min_clamp=", GPUSamplerDescriptor_LodMinClampEqual);
  DefineMethod(klass, "lod_max_clamp", GPUSamplerDescriptor_LodMaxClamp);
  DefineMethod(klass, "lod_max_clamp=", GPUSamplerDescriptor_LodMaxClampEqual);
  DefineMethod(klass, "compare", GPUSamplerDescriptor_Compare);
  DefineMethod(klass, "compare=", GPUSamplerDescriptor_CompareEqual);
  DefineMethod(klass, "max_anisotropy", GPUSamplerDescriptor_MaxAnisotropy);
  DefineMethod(klass, "max_anisotropy=", GPUSamplerDescriptor_MaxAnisotropyEqual);
  InitGPUSamplerDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUSamplerDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUSamplerDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
