// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu.h"

#include "binding_gpu_bind_group.h"
#include "binding_gpu_bind_group_descriptor.h"
#include "binding_gpu_bind_group_layout.h"
#include "binding_gpu_bind_group_layout_descriptor.h"
#include "binding_gpu_buffer.h"
#include "binding_gpu_buffer_descriptor.h"
#include "binding_gpu_command_encoder.h"
#include "binding_gpu_compute_pipeline.h"
#include "binding_gpu_compute_pipeline_descriptor.h"
#include "binding_gpu_pipeline_layout.h"
#include "binding_gpu_pipeline_layout_descriptor.h"
#include "binding_gpu_query_set.h"
#include "binding_gpu_query_set_descriptor.h"
#include "binding_gpu_queue.h"
#include "binding_gpu_render_pipeline.h"
#include "binding_gpu_render_pipeline_descriptor.h"
#include "binding_gpu_sampler.h"
#include "binding_gpu_sampler_descriptor.h"
#include "binding_gpu_shader_module.h"
#include "binding_gpu_shader_module_descriptor.h"
#include "binding_gpu_texture.h"
#include "binding_gpu_texture_descriptor.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPU  (core/gpu.h:965-1085)
// -------------------------------------------------------------------------

RB_FUNC(GPU_queue) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = urge::GPU::Get().queue();
    return WrapObject(result.get(), kGPUQueueDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateBuffer) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateBuffer(GetObject<urge::GPUBufferDescriptor>(descriptor_val, kGPUBufferDescriptorDataType));
    return WrapObject(result.get(), kGPUBufferDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateTexture) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateTexture(GetObject<urge::GPUTextureDescriptor>(descriptor_val, kGPUTextureDescriptorDataType));
    return WrapObject(result.get(), kGPUTextureDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateSampler) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateSampler(GetObject<urge::GPUSamplerDescriptor>(descriptor_val, kGPUSamplerDescriptorDataType));
    return WrapObject(result.get(), kGPUSamplerDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateShaderModule) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateShaderModule(GetObject<urge::GPUShaderModuleDescriptor>(descriptor_val, kGPUShaderModuleDescriptorDataType));
    return WrapObject(result.get(), kGPUShaderModuleDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateBindGroupLayout) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateBindGroupLayout(GetObject<urge::GPUBindGroupLayoutDescriptor>(descriptor_val, kGPUBindGroupLayoutDescriptorDataType));
    return WrapObject(result.get(), kGPUBindGroupLayoutDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreatePipelineLayout) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreatePipelineLayout(GetObject<urge::GPUPipelineLayoutDescriptor>(descriptor_val, kGPUPipelineLayoutDescriptorDataType));
    return WrapObject(result.get(), kGPUPipelineLayoutDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateBindGroup) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateBindGroup(GetObject<urge::GPUBindGroupDescriptor>(descriptor_val, kGPUBindGroupDescriptorDataType));
    return WrapObject(result.get(), kGPUBindGroupDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateRenderPipeline) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateRenderPipeline(GetObject<urge::GPURenderPipelineDescriptor>(descriptor_val, kGPURenderPipelineDescriptorDataType));
    return WrapObject(result.get(), kGPURenderPipelineDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateComputePipeline) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateComputePipeline(GetObject<urge::GPUComputePipelineDescriptor>(descriptor_val, kGPUComputePipelineDescriptorDataType));
    return WrapObject(result.get(), kGPUComputePipelineDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateQuerySet) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = urge::GPU::Get().CreateQuerySet(GetObject<urge::GPUQuerySetDescriptor>(descriptor_val, kGPUQuerySetDescriptorDataType));
    return WrapObject(result.get(), kGPUQuerySetDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPU_CreateCommandEncoder) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = urge::GPU::Get().CreateCommandEncoder();
    return WrapObject(result.get(), kGPUCommandEncoderDataType);
  }
  EXC_END;
  return Qnil;
}

void InitGPUBindingAppend(VALUE mod);

void InitGPUBinding() {
  auto mod = rb_define_module("GPU");

  DefineModuleFunction(mod, "queue", GPU_queue);
  DefineModuleFunction(mod, "create_buffer", GPU_CreateBuffer);
  DefineModuleFunction(mod, "create_texture", GPU_CreateTexture);
  DefineModuleFunction(mod, "create_sampler", GPU_CreateSampler);
  DefineModuleFunction(mod, "create_shader_module", GPU_CreateShaderModule);
  DefineModuleFunction(mod, "create_bind_group_layout", GPU_CreateBindGroupLayout);
  DefineModuleFunction(mod, "create_pipeline_layout", GPU_CreatePipelineLayout);
  DefineModuleFunction(mod, "create_bind_group", GPU_CreateBindGroup);
  DefineModuleFunction(mod, "create_render_pipeline", GPU_CreateRenderPipeline);
  DefineModuleFunction(mod, "create_compute_pipeline", GPU_CreateComputePipeline);
  DefineModuleFunction(mod, "create_query_set", GPU_CreateQuerySet);
  DefineModuleFunction(mod, "create_command_encoder", GPU_CreateCommandEncoder);
  rb_const_set(mod, rb_intern("MAP_READ"),
               LONG2NUM(static_cast<long>(urge::GPU::MapRead)));
  rb_const_set(mod, rb_intern("MAP_WRITE"),
               LONG2NUM(static_cast<long>(urge::GPU::MapWrite)));
  rb_const_set(mod, rb_intern("COPY_SRC"),
               LONG2NUM(static_cast<long>(urge::GPU::CopySrc)));
  rb_const_set(mod, rb_intern("COPY_DST"),
               LONG2NUM(static_cast<long>(urge::GPU::CopyDst)));
  rb_const_set(mod, rb_intern("INDEX"),
               LONG2NUM(static_cast<long>(urge::GPU::Index)));
  rb_const_set(mod, rb_intern("VERTEX"),
               LONG2NUM(static_cast<long>(urge::GPU::Vertex)));
  rb_const_set(mod, rb_intern("UNIFORM"),
               LONG2NUM(static_cast<long>(urge::GPU::Uniform)));
  rb_const_set(mod, rb_intern("STORAGE"),
               LONG2NUM(static_cast<long>(urge::GPU::Storage)));
  rb_const_set(mod, rb_intern("INDIRECT"),
               LONG2NUM(static_cast<long>(urge::GPU::Indirect)));
  rb_const_set(mod, rb_intern("QUERY_RESOLVE"),
               LONG2NUM(static_cast<long>(urge::GPU::QueryResolve)));
  rb_const_set(mod, rb_intern("TEXTURE_BINDING"),
               LONG2NUM(static_cast<long>(urge::GPU::TextureBinding)));
  rb_const_set(mod, rb_intern("TEXTURE_STORAGE_BINDING"),
               LONG2NUM(static_cast<long>(urge::GPU::TextureStorageBinding)));
  rb_const_set(mod, rb_intern("TEXTURE_RENDER_ATTACHMENT"),
               LONG2NUM(static_cast<long>(urge::GPU::TextureRenderAttachment)));
  rb_const_set(mod, rb_intern("LOAD"),
               LONG2NUM(static_cast<long>(urge::GPU::Load)));
  rb_const_set(mod, rb_intern("CLEAR"),
               LONG2NUM(static_cast<long>(urge::GPU::Clear)));
  rb_const_set(mod, rb_intern("STORE"),
               LONG2NUM(static_cast<long>(urge::GPU::Store)));
  rb_const_set(mod, rb_intern("DISCARD"),
               LONG2NUM(static_cast<long>(urge::GPU::Discard)));
  rb_const_set(mod, rb_intern("SHADER_LANGUAGE_WGSL"),
               LONG2NUM(static_cast<long>(urge::GPU::ShaderLanguageWgsl)));
  rb_const_set(mod, rb_intern("SHADER_LANGUAGE_GLSL"),
               LONG2NUM(static_cast<long>(urge::GPU::ShaderLanguageGlsl)));
  rb_const_set(mod, rb_intern("SHADER_STAGE_VERTEX"),
               LONG2NUM(static_cast<long>(urge::GPU::ShaderStageVertex)));
  rb_const_set(mod, rb_intern("SHADER_STAGE_FRAGMENT"),
               LONG2NUM(static_cast<long>(urge::GPU::ShaderStageFragment)));
  rb_const_set(mod, rb_intern("INDEX_FORMAT_UINT16"),
               LONG2NUM(static_cast<long>(urge::GPU::IndexFormatUint16)));
  rb_const_set(mod, rb_intern("INDEX_FORMAT_UINT32"),
               LONG2NUM(static_cast<long>(urge::GPU::IndexFormatUint32)));
  rb_const_set(mod, rb_intern("VERTEX_FORMAT_FLOAT32"),
               LONG2NUM(static_cast<long>(urge::GPU::VertexFormatFloat32)));
  rb_const_set(mod, rb_intern("VERTEX_FORMAT_FLOAT32X2"),
               LONG2NUM(static_cast<long>(urge::GPU::VertexFormatFloat32x2)));
  rb_const_set(mod, rb_intern("VERTEX_FORMAT_FLOAT32X3"),
               LONG2NUM(static_cast<long>(urge::GPU::VertexFormatFloat32x3)));
  rb_const_set(mod, rb_intern("VERTEX_FORMAT_FLOAT32X4"),
               LONG2NUM(static_cast<long>(urge::GPU::VertexFormatFloat32x4)));
  rb_const_set(mod, rb_intern("TEXTURE_FORMAT_UNDEFINED"),
               LONG2NUM(static_cast<long>(urge::GPU::TextureFormatUndefined)));
  rb_const_set(mod, rb_intern("TEXTURE_FORMAT_RGBA8_UNORM"),
               LONG2NUM(static_cast<long>(urge::GPU::TextureFormatRgba8Unorm)));
  rb_const_set(mod, rb_intern("FILTER_MODE_NEAREST"),
               LONG2NUM(static_cast<long>(urge::GPU::FilterModeNearest)));
  rb_const_set(mod, rb_intern("FILTER_MODE_LINEAR"),
               LONG2NUM(static_cast<long>(urge::GPU::FilterModeLinear)));
  rb_const_set(mod, rb_intern("ADDRESS_MODE_CLAMP_TO_EDGE"),
               LONG2NUM(static_cast<long>(urge::GPU::AddressModeClampToEdge)));
  rb_const_set(mod, rb_intern("ADDRESS_MODE_REPEAT"),
               LONG2NUM(static_cast<long>(urge::GPU::AddressModeRepeat)));
  rb_const_set(mod, rb_intern("ADDRESS_MODE_MIRROR_REPEAT"),
               LONG2NUM(static_cast<long>(urge::GPU::AddressModeMirrorRepeat)));
  InitGPUBindingAppend(mod);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
