// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_compute_pipeline_descriptor.h"

#include "binding_gpu_object.h"
#include "binding_gpu_pipeline_layout.h"
#include "binding_gpu_shader_module.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUComputePipelineDescriptor  (core/gpu.h:449-475)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUComputePipelineDescriptor, GPUObject);

RB_FUNC(GPUComputePipelineDescriptor_initialize) {
  urge::RefPtr<urge::GPUComputePipelineDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUComputePipelineDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUComputePipelineDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUComputePipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUComputePipelineDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUComputePipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUComputePipelineDescriptor_GetEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPUComputePipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetEntryPoint();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUComputePipelineDescriptor_SetEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPUComputePipelineDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetEntryPoint(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: layout (RefPtr<GPUPipelineLayout>)
BINDING_ATTR_OBJECT_REF(GPUComputePipelineDescriptor,
                        urge::GPUComputePipelineDescriptor,
                        Layout,
                        urge::GPUPipelineLayout,
                        kGPUPipelineLayoutDataType);

// Attribute: module (RefPtr<GPUShaderModule>)
BINDING_ATTR_OBJECT_REF(GPUComputePipelineDescriptor,
                        urge::GPUComputePipelineDescriptor,
                        Module,
                        urge::GPUShaderModule,
                        kGPUShaderModuleDataType);

void InitGPUComputePipelineDescriptorBindingAppend(VALUE klass);

void InitGPUComputePipelineDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUComputePipelineDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUComputePipelineDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUComputePipelineDescriptor_initialize);
  DefineMethod(klass, "label", GPUComputePipelineDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUComputePipelineDescriptor_SetLabel);
  DefineMethod(klass, "entry_point", GPUComputePipelineDescriptor_GetEntryPoint);
  DefineMethod(klass, "entry_point=", GPUComputePipelineDescriptor_SetEntryPoint);
  DefineMethod(klass, "layout", GPUComputePipelineDescriptor_Layout);
  DefineMethod(klass, "layout=", GPUComputePipelineDescriptor_LayoutEqual);
  DefineMethod(klass, "module", GPUComputePipelineDescriptor_Module);
  DefineMethod(klass, "module=", GPUComputePipelineDescriptor_ModuleEqual);
  InitGPUComputePipelineDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUComputePipelineDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUComputePipelineDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
