// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_init.h"

#include "binding_disposable.h"
#include "binding_node.h"
#include "binding_geometry.h"
#include "binding_bitmap.h"
#include "binding_color.h"
#include "binding_font.h"
#include "binding_palette.h"
#include "binding_plane.h"
#include "binding_rect.h"
#include "binding_sprite.h"
#include "binding_table.h"
#include "binding_tone.h"
#include "binding_vector2.h"
#include "binding_vector3.h"
#include "binding_vector4.h"
#include "binding_tilemap_vx.h"
#include "binding_tilemap_xp.h"
#include "binding_viewport.h"
#include "binding_window_vx.h"
#include "binding_window_xp.h"
#include "binding_effect.h"
#include "binding_audio_stream.h"
#include "binding_audio.h"
#include "binding_graphics.h"
#include "binding_input.h"
#include "binding_mouse.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
namespace {

// The RGSS exception classes the glue raises. A host entry point may
// define them first, with parent classes of its own; this is the fallback
// which keeps the binding library self sufficient.
void DefineRGSSExceptions() {
  if (NIL_P(g_reset_exception))
    g_reset_exception = rb_define_class("RGSSReset", rb_eStandardError);
  if (NIL_P(g_rgss_exception))
    g_rgss_exception = rb_define_class("RGSSError", rb_eStandardError);
}

}  // namespace

void InitBindings() {
  DefineRGSSExceptions();

  InitDisposableBinding();
  InitNodeBinding();
  InitGeometryBinding();
  InitBitmapBinding();
  InitColorBinding();
  InitFontBinding();
  InitPaletteBinding();
  InitPlaneBinding();
  InitRectBinding();
  InitSpriteBinding();
  InitTableBinding();
  InitToneBinding();
  InitVector2Binding();
  InitVector3Binding();
  InitVector4Binding();
  InitTilemapVXBinding();
  InitTilemapXPBinding();
  InitViewportBinding();
  InitWindowVXBinding();
  InitWindowXPBinding();
  InitEffectBinding();
  InitAudioStreamBinding();
  InitAudioBinding();
  InitGraphicsBinding();
  InitInputBinding();
  InitMouseBinding();
}
// --- GENERATED END ---

}  // namespace binding
