// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_texture_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUTextureDescriptor  (core/gpu.h:99-151)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUTextureDescriptor, GPUObject);

RB_FUNC(GPUTextureDescriptor_initialize) {
  urge::RefPtr<urge::GPUTextureDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUTextureDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUTextureDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUTextureDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTextureDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUTextureDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: usage (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor, urge::GPUTextureDescriptor, Usage);

// Attribute: dimension (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor, urge::GPUTextureDescriptor, Dimension);

// Attribute: format (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor, urge::GPUTextureDescriptor, Format);

// Attribute: width (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor, urge::GPUTextureDescriptor, Width);

// Attribute: height (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor, urge::GPUTextureDescriptor, Height);

// Attribute: depth_or_array_layers (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor,
                 urge::GPUTextureDescriptor,
                 DepthOrArrayLayers);

// Attribute: mip_level_count (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor,
                 urge::GPUTextureDescriptor,
                 MipLevelCount);

// Attribute: sample_count (uint32_t)
BINDING_ATTR_INT(GPUTextureDescriptor, urge::GPUTextureDescriptor, SampleCount);

void InitGPUTextureDescriptorBindingAppend(VALUE klass);

void InitGPUTextureDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUTextureDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUTextureDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUTextureDescriptor_initialize);
  DefineMethod(klass, "label", GPUTextureDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUTextureDescriptor_SetLabel);
  DefineMethod(klass, "usage", GPUTextureDescriptor_Usage);
  DefineMethod(klass, "usage=", GPUTextureDescriptor_UsageEqual);
  DefineMethod(klass, "dimension", GPUTextureDescriptor_Dimension);
  DefineMethod(klass, "dimension=", GPUTextureDescriptor_DimensionEqual);
  DefineMethod(klass, "format", GPUTextureDescriptor_Format);
  DefineMethod(klass, "format=", GPUTextureDescriptor_FormatEqual);
  DefineMethod(klass, "width", GPUTextureDescriptor_Width);
  DefineMethod(klass, "width=", GPUTextureDescriptor_WidthEqual);
  DefineMethod(klass, "height", GPUTextureDescriptor_Height);
  DefineMethod(klass, "height=", GPUTextureDescriptor_HeightEqual);
  DefineMethod(klass, "depth_or_array_layers", GPUTextureDescriptor_DepthOrArrayLayers);
  DefineMethod(klass, "depth_or_array_layers=", GPUTextureDescriptor_DepthOrArrayLayersEqual);
  DefineMethod(klass, "mip_level_count", GPUTextureDescriptor_MipLevelCount);
  DefineMethod(klass, "mip_level_count=", GPUTextureDescriptor_MipLevelCountEqual);
  DefineMethod(klass, "sample_count", GPUTextureDescriptor_SampleCount);
  DefineMethod(klass, "sample_count=", GPUTextureDescriptor_SampleCountEqual);
  InitGPUTextureDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUTextureDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUTextureDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
