// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_render_pipeline.h"

#include "binding_gpu_bind_group_layout.h"
#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPURenderPipeline  (core/gpu.h:812-816)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPURenderPipeline, GPUObject);

RB_FUNC(GPURenderPipeline_GetBindGroupLayout) {
  auto* self_obj = GetSelfData<urge::GPURenderPipeline>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    uint32_t group_index;
    ParseArgs(argc, argv, "u", &group_index);

    auto result = self_obj->GetBindGroupLayout(group_index);
    return WrapObject(result.get(), kGPUBindGroupLayoutDataType);
  }
  EXC_END;
  return Qnil;
}

void InitGPURenderPipelineBindingAppend(VALUE klass);

void InitGPURenderPipelineBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPURenderPipeline", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPURenderPipelineDataType>);

  DefineMethod(klass, "get_bind_group_layout", GPURenderPipeline_GetBindGroupLayout);
  InitGPURenderPipelineBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPURenderPipelineBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPURenderPipelineBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
