// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_geometry.h"

#include "binding_bitmap.h"
#include "binding_color.h"
#include "binding_effect.h"
#include "binding_node.h"
#include "binding_vector2.h"
#include "binding_vector3.h"
#include "binding_viewport.h"

#include "core/bitmap.h"
#include "core/effect.h"
#include "core/geometry.h"
#include "core/utility.h"
#include "core/viewport.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Geometry  (core/geometry.h:39-61)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(Geometry, Node);

RB_FUNC(Geometry_initialize) {
  urge::RefPtr<urge::Geometry> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Geometry>();
    } else if (argc == 1) {
      // initialize(viewport)
      VALUE viewport_val;
      ParseArgs(argc, argv, "o", &viewport_val);
      obj = urge::MakeRefCounted<urge::Geometry>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Geometry_SetPosition) {
  auto* self_obj = GetSelfData<urge::Geometry>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    int triangle, point;
    VALUE position_val;
    ParseArgs(argc, argv, "iio", &triangle, &point, &position_val);

    self_obj->SetPosition(triangle, point,
        GetObject<urge::Vector3>(position_val, kVector3DataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Geometry_SetTexcoord) {
  auto* self_obj = GetSelfData<urge::Geometry>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    int triangle, point;
    VALUE texcoord_val;
    ParseArgs(argc, argv, "iio", &triangle, &point, &texcoord_val);

    self_obj->SetTexcoord(triangle, point,
        GetObject<urge::Vector2>(texcoord_val, kVector2DataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Geometry_SetColor) {
  auto* self_obj = GetSelfData<urge::Geometry>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    int triangle, point;
    VALUE color_val;
    ParseArgs(argc, argv, "iio", &triangle, &point, &color_val);

    self_obj->SetColor(triangle, point,
        GetObject<urge::Color>(color_val, kColorDataType));
  }
  EXC_END;
  return Qnil;
}

// Attribute: viewport (RefPtr<Viewport>)
BINDING_ATTR_OBJECT_REF(Geometry,
                        urge::Geometry,
                        Viewport,
                        urge::Viewport,
                        kViewportDataType);

// Attribute: capacity (int32_t)
BINDING_ATTR_INT(Geometry, urge::Geometry, Capacity);

// Attribute: bitmap (RefPtr<Bitmap>)
BINDING_ATTR_OBJECT_REF(Geometry,
                        urge::Geometry,
                        Bitmap,
                        urge::Bitmap,
                        kBitmapDataType);

// Attribute: blend_type (int32_t)
BINDING_ATTR_INT(Geometry, urge::Geometry, BlendType);

// Attribute: effect (RefPtr<Effect>)
BINDING_ATTR_OBJECT_REF(Geometry,
                        urge::Geometry,
                        Effect,
                        urge::Effect,
                        kEffectDataType);

void InitGeometryBindingAppend(VALUE klass);

void InitGeometryBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("Geometry", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGeometryDataType>);

  DefineMethod(klass, "initialize", Geometry_initialize);
  DefineMethod(klass, "set_position", Geometry_SetPosition);
  DefineMethod(klass, "set_texcoord", Geometry_SetTexcoord);
  DefineMethod(klass, "set_color", Geometry_SetColor);
  DefineMethod(klass, "viewport", Geometry_Viewport);
  DefineMethod(klass, "viewport=", Geometry_ViewportEqual);
  DefineMethod(klass, "capacity", Geometry_Capacity);
  DefineMethod(klass, "capacity=", Geometry_CapacityEqual);
  DefineMethod(klass, "bitmap", Geometry_Bitmap);
  DefineMethod(klass, "bitmap=", Geometry_BitmapEqual);
  DefineMethod(klass, "blend_type", Geometry_BlendType);
  DefineMethod(klass, "blend_type=", Geometry_BlendTypeEqual);
  DefineMethod(klass, "effect", Geometry_Effect);
  DefineMethod(klass, "effect=", Geometry_EffectEqual);
  InitGeometryBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGeometryBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGeometryBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
