// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_perspective_camera.h"

#include "binding_camera.h"

#include "core/camera.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// PerspectiveCamera  (core/camera.h:99-109)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(PerspectiveCamera, Camera);

RB_FUNC(PerspectiveCamera_initialize) {
  urge::RefPtr<urge::PerspectiveCamera> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::PerspectiveCamera>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

// Attribute: fov (float)
BINDING_ATTR_FLOAT(PerspectiveCamera, urge::PerspectiveCamera, Fov);

// Attribute: near (float)
BINDING_ATTR_FLOAT(PerspectiveCamera, urge::PerspectiveCamera, Near);

// Attribute: far (float)
BINDING_ATTR_FLOAT(PerspectiveCamera, urge::PerspectiveCamera, Far);

void InitPerspectiveCameraBindingAppend(VALUE klass);

void InitPerspectiveCameraBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Camera"));
  auto klass = rb_define_class("PerspectiveCamera", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kPerspectiveCameraDataType>);

  DefineMethod(klass, "initialize", PerspectiveCamera_initialize);
  DefineMethod(klass, "fov", PerspectiveCamera_Fov);
  DefineMethod(klass, "fov=", PerspectiveCamera_FovEqual);
  DefineMethod(klass, "near", PerspectiveCamera_Near);
  DefineMethod(klass, "near=", PerspectiveCamera_NearEqual);
  DefineMethod(klass, "far", PerspectiveCamera_Far);
  DefineMethod(klass, "far=", PerspectiveCamera_FarEqual);
  InitPerspectiveCameraBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitPerspectiveCameraBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitPerspectiveCameraBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
