// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_orthographic_camera.h"

#include "binding_camera.h"

#include "core/camera.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// OrthographicCamera  (core/camera.h:128-138)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(OrthographicCamera, Camera);

RB_FUNC(OrthographicCamera_initialize) {
  urge::RefPtr<urge::OrthographicCamera> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::OrthographicCamera>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

// Attribute: size (float)
BINDING_ATTR_FLOAT(OrthographicCamera, urge::OrthographicCamera, Size);

// Attribute: near (float)
BINDING_ATTR_FLOAT(OrthographicCamera, urge::OrthographicCamera, Near);

// Attribute: far (float)
BINDING_ATTR_FLOAT(OrthographicCamera, urge::OrthographicCamera, Far);

void InitOrthographicCameraBindingAppend(VALUE klass);

void InitOrthographicCameraBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Camera"));
  auto klass = rb_define_class("OrthographicCamera", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kOrthographicCameraDataType>);

  DefineMethod(klass, "initialize", OrthographicCamera_initialize);
  DefineMethod(klass, "size", OrthographicCamera_Size);
  DefineMethod(klass, "size=", OrthographicCamera_SizeEqual);
  DefineMethod(klass, "near", OrthographicCamera_Near);
  DefineMethod(klass, "near=", OrthographicCamera_NearEqual);
  DefineMethod(klass, "far", OrthographicCamera_Far);
  DefineMethod(klass, "far=", OrthographicCamera_FarEqual);
  InitOrthographicCameraBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitOrthographicCameraBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitOrthographicCameraBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
