// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_tilemap_xp.h"

#include "binding_bitmap.h"
#include "binding_table.h"
#include "binding_viewport.h"

#include "core/bitmap.h"
#include "core/table.h"
#include "core/tilemap_xp.h"
#include "core/viewport.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
VALUE AllocateAutotileProxy(VALUE parent, const char* klass_name) {
  VALUE klass = rb_const_get(rb_cObject, rb_intern(klass_name));
  VALUE obj = rb_obj_alloc(klass);
  rb_iv_set(obj, "@parent", parent);
  return obj;
}

RB_FUNC(TilemapAutotile_Get) {
  auto parent = GetObject<urge::TilemapXP>(rb_iv_get(self, "@parent"),
                                           kTilemapXPDataType);
  int index;
  ParseArgs(argc, argv, "i", &index);

  EXC_BEGIN {
    auto result = parent->GetAutotile(index);
    if (result)
      return WrapObject(result.get(), kBitmapDataType);
    return Qnil;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapAutotile_Set) {
  auto parent = GetObject<urge::TilemapXP>(rb_iv_get(self, "@parent"),
                                           kTilemapXPDataType);
  int index;
  VALUE bitmap_val;
  ParseArgs(argc, argv, "io", &index, &bitmap_val);

  auto bitmap = GetObject<urge::Bitmap>(bitmap_val, kBitmapDataType);

  EXC_BEGIN {
    parent->SetAutotile(index, bitmap);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapXP_Autotiles) {
  return AllocateAutotileProxy(self, "TilemapAutotileArray");
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// TilemapXP  (core/tilemap_xp.h:86-108)
// -------------------------------------------------------------------------

RB_DEF_TYPE(TilemapXP);

RB_FUNC(TilemapXP_initialize) {
  urge::RefPtr<urge::TilemapXP> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::TilemapXP>();
    } else if (argc == 1) {
      // initialize(viewport)
      VALUE viewport_val;
      ParseArgs(argc, argv, "o", &viewport_val);
      obj = urge::MakeRefCounted<urge::TilemapXP>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(TilemapXP_Update) {
  auto* self_obj = GetSelfData<urge::TilemapXP>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapXP_SetTileset) {
  auto* self_obj = GetSelfData<urge::TilemapXP>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE bitmap_val;
    ParseArgs(argc, argv, "o", &bitmap_val);

    self_obj->SetTileset(GetObject<urge::Bitmap>(bitmap_val, kBitmapDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapXP_GetTileset) {
  auto* self_obj = GetSelfData<urge::TilemapXP>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = self_obj->GetTileset();
    return WrapObject(result.get(), kBitmapDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapXP_SetAutotile) {
  auto* self_obj = GetSelfData<urge::TilemapXP>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    int index;
    VALUE bitmap_val;
    ParseArgs(argc, argv, "io", &index, &bitmap_val);

    self_obj->SetAutotile(index,
        GetObject<urge::Bitmap>(bitmap_val, kBitmapDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapXP_GetAutotile) {
  auto* self_obj = GetSelfData<urge::TilemapXP>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    int index;
    ParseArgs(argc, argv, "i", &index);

    auto result = self_obj->GetAutotile(index);
    return WrapObject(result.get(), kBitmapDataType);
  }
  EXC_END;
  return Qnil;
}

// Attribute: viewport (RefPtr<Viewport>)
BINDING_ATTR_OBJECT_REF(TilemapXP,
                        urge::TilemapXP,
                        Viewport,
                        urge::Viewport,
                        kViewportDataType);

// Attribute: visible (bool)
BINDING_ATTR_BOOL(TilemapXP, urge::TilemapXP, Visible);

// Attribute: z (int32_t)
BINDING_ATTR_INT(TilemapXP, urge::TilemapXP, Z);

// Attribute: map_data (RefPtr<Table>)
BINDING_ATTR_OBJECT(TilemapXP,
                    urge::TilemapXP,
                    MapData,
                    urge::Table,
                    kTableDataType);

// Attribute: flash_data (RefPtr<Table>)
BINDING_ATTR_OBJECT(TilemapXP,
                    urge::TilemapXP,
                    FlashData,
                    urge::Table,
                    kTableDataType);

// Attribute: priorities (RefPtr<Table>)
BINDING_ATTR_OBJECT(TilemapXP,
                    urge::TilemapXP,
                    Priorities,
                    urge::Table,
                    kTableDataType);

// Attribute: ox (int32_t)
BINDING_ATTR_INT(TilemapXP, urge::TilemapXP, OX);

// Attribute: oy (int32_t)
BINDING_ATTR_INT(TilemapXP, urge::TilemapXP, OY);

void InitTilemapXPBindingAppend(VALUE klass);

void InitTilemapXPBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("TilemapXP", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kTilemapXPDataType>);

  DefineMethod(klass, "initialize", TilemapXP_initialize);
  DefineMethod(klass, "update", TilemapXP_Update);
  DefineMethod(klass, "tileset=", TilemapXP_SetTileset);
  DefineMethod(klass, "tileset", TilemapXP_GetTileset);
  DefineMethod(klass, "set_autotile", TilemapXP_SetAutotile);
  DefineMethod(klass, "get_autotile", TilemapXP_GetAutotile);
  DefineMethod(klass, "viewport", TilemapXP_Viewport);
  DefineMethod(klass, "viewport=", TilemapXP_ViewportEqual);
  DefineMethod(klass, "visible", TilemapXP_Visible);
  DefineMethod(klass, "visible=", TilemapXP_VisibleEqual);
  DefineMethod(klass, "z", TilemapXP_Z);
  DefineMethod(klass, "z=", TilemapXP_ZEqual);
  DefineMethod(klass, "map_data", TilemapXP_MapData);
  DefineMethod(klass, "map_data=", TilemapXP_MapDataEqual);
  DefineMethod(klass, "flash_data", TilemapXP_FlashData);
  DefineMethod(klass, "flash_data=", TilemapXP_FlashDataEqual);
  DefineMethod(klass, "priorities", TilemapXP_Priorities);
  DefineMethod(klass, "priorities=", TilemapXP_PrioritiesEqual);
  DefineMethod(klass, "ox", TilemapXP_OX);
  DefineMethod(klass, "ox=", TilemapXP_OXEqual);
  DefineMethod(klass, "oy", TilemapXP_OY);
  DefineMethod(klass, "oy=", TilemapXP_OYEqual);
  InitTilemapXPBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// XP holds its seven autotiles in an array-like object rather than in one
// bitmap, so `Tilemap#autotiles[i]` is what the Ruby side reads.  The proxy
// class and the accessor it uses are both out of reach of the IR, hence the
// two HANDWRITTEN blocks.
void InitTilemapXPBindingAppend(VALUE klass) {
  // The proxy carries its parent in an instance variable and the accessors
  // above read it back, so it keeps the default allocator.
  auto proxy = rb_define_class("TilemapAutotileArray", rb_cObject);
  DefineMethod(proxy, "[]", TilemapAutotile_Get);
  DefineMethod(proxy, "[]=", TilemapAutotile_Set);

  DefineMethod(klass, "autotiles", TilemapXP_Autotiles);
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
