// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_input.h"

#include "core/input.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// RGSS key constants (`Input::DOWN`, `Input::A`, ...).  They come from the
// table in core/input.h rather than from a declaration in the export block,
// so they cannot be generated.
void DefineInputKeyConstants(VALUE mod) {
  for (const auto& binding : urge::kKeyboardBindings) {
    ID key =
        rb_intern2(binding.name.data(), static_cast<long>(binding.name.size()));
    rb_const_set(mod, key, LONG2NUM(binding.key_id));
  }
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Input  (core/input.h:55-73)
// -------------------------------------------------------------------------

RB_FUNC(Input_Update) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Input::Get().Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Pressed) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string sym;
    ParseArgs(argc, argv, "s", &sym);

    return urge::Input::Get().Pressed(sym) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Triggered) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string sym;
    ParseArgs(argc, argv, "s", &sym);

    return urge::Input::Get().Triggered(sym) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Repeated) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string sym;
    ParseArgs(argc, argv, "s", &sym);

    return urge::Input::Get().Repeated(sym) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Dir4) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Input::Get().Dir4());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Dir8) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Input::Get().Dir8());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_KeyPressed) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    return urge::Input::Get().KeyPressed(keycode) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_KeyTriggered) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    return urge::Input::Get().KeyTriggered(keycode) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_KeyRepeated) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    return urge::Input::Get().KeyRepeated(keycode) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_GetKeyName) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    std::string result = urge::Input::Get().GetKeyName(keycode);
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

void InitInputBinding() {
  auto mod = rb_define_module("Input");

  DefineModuleFunction(mod, "update", Input_Update);
  DefineModuleFunction(mod, "press?", Input_Pressed);
  DefineModuleFunction(mod, "trigger?", Input_Triggered);
  DefineModuleFunction(mod, "repeat?", Input_Repeated);
  DefineModuleFunction(mod, "dir4", Input_Dir4);
  DefineModuleFunction(mod, "dir8", Input_Dir8);
  DefineModuleFunction(mod, "key_press?", Input_KeyPressed);
  DefineModuleFunction(mod, "key_trigger?", Input_KeyTriggered);
  DefineModuleFunction(mod, "key_repeat?", Input_KeyRepeated);
  DefineModuleFunction(mod, "get_key_name", Input_GetKeyName);
  DefineInputKeyConstants(mod);
}
// --- GENERATED END ---

}  // namespace binding
