// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_sprite.h"

#include "binding_bitmap.h"
#include "binding_color.h"
#include "binding_effect.h"
#include "binding_node.h"
#include "binding_rect.h"
#include "binding_tone.h"
#include "binding_viewport.h"

#include "core/bitmap.h"
#include "core/effect.h"
#include "core/sprite.h"
#include "core/utility.h"
#include "core/viewport.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Sprite  (core/sprite.h:34-93)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(Sprite, Node);

RB_FUNC(Sprite_initialize) {
  urge::RefPtr<urge::Sprite> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Sprite>();
    } else if (argc == 1) {
      // initialize(viewport)
      VALUE viewport_val;
      ParseArgs(argc, argv, "o", &viewport_val);
      obj = urge::MakeRefCounted<urge::Sprite>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Sprite_Flash) {
  auto* self_obj = GetSelfData<urge::Sprite>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    VALUE color_val;
    int duration;
    ParseArgs(argc, argv, "oi", &color_val, &duration);

    self_obj->Flash(GetObject<urge::Color>(color_val, kColorDataType),
        duration);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Sprite_Update) {
  auto* self_obj = GetSelfData<urge::Sprite>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Sprite_Width) {
  auto* self_obj = GetSelfData<urge::Sprite>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Width());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Sprite_Height) {
  auto* self_obj = GetSelfData<urge::Sprite>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Height());
  }
  EXC_END;
  return Qnil;
}

// Attribute: viewport (RefPtr<Viewport>)
BINDING_ATTR_OBJECT_REF(Sprite,
                        urge::Sprite,
                        Viewport,
                        urge::Viewport,
                        kViewportDataType);

// Attribute: bitmap (RefPtr<Bitmap>)
BINDING_ATTR_OBJECT_REF(Sprite,
                        urge::Sprite,
                        Bitmap,
                        urge::Bitmap,
                        kBitmapDataType);

// Attribute: src_rect (RefPtr<Rect>)
BINDING_ATTR_OBJECT(Sprite, urge::Sprite, SrcRect, urge::Rect, kRectDataType);

// Attribute: x (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, X);

// Attribute: y (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, Y);

// Attribute: ox (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, OX);

// Attribute: oy (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, OY);

// Attribute: zoom_x (float)
BINDING_ATTR_FLOAT(Sprite, urge::Sprite, ZoomX);

// Attribute: zoom_y (float)
BINDING_ATTR_FLOAT(Sprite, urge::Sprite, ZoomY);

// Attribute: angle (float)
BINDING_ATTR_FLOAT(Sprite, urge::Sprite, Angle);

// Attribute: wave_amp (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, WaveAmp);

// Attribute: wave_length (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, WaveLength);

// Attribute: wave_speed (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, WaveSpeed);

// Attribute: wave_phase (float)
BINDING_ATTR_FLOAT(Sprite, urge::Sprite, WavePhase);

// Attribute: mirror (bool)
BINDING_ATTR_BOOL(Sprite, urge::Sprite, Mirror);

// Attribute: bush_depth (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, BushDepth);

// Attribute: bush_opacity (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, BushOpacity);

// Attribute: opacity (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, Opacity);

// Attribute: blend_type (int32_t)
BINDING_ATTR_INT(Sprite, urge::Sprite, BlendType);

// Attribute: color (RefPtr<Color>)
BINDING_ATTR_OBJECT(Sprite, urge::Sprite, Color, urge::Color, kColorDataType);

// Attribute: tone (RefPtr<Tone>)
BINDING_ATTR_OBJECT(Sprite, urge::Sprite, Tone, urge::Tone, kToneDataType);

// Attribute: effect (RefPtr<Effect>)
BINDING_ATTR_OBJECT_REF(Sprite,
                        urge::Sprite,
                        Effect,
                        urge::Effect,
                        kEffectDataType);

void InitSpriteBindingAppend(VALUE klass);

void InitSpriteBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("Sprite", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kSpriteDataType>);

  DefineMethod(klass, "initialize", Sprite_initialize);
  DefineMethod(klass, "flash", Sprite_Flash);
  DefineMethod(klass, "update", Sprite_Update);
  DefineMethod(klass, "width", Sprite_Width);
  DefineMethod(klass, "height", Sprite_Height);
  DefineMethod(klass, "viewport", Sprite_Viewport);
  DefineMethod(klass, "viewport=", Sprite_ViewportEqual);
  DefineMethod(klass, "bitmap", Sprite_Bitmap);
  DefineMethod(klass, "bitmap=", Sprite_BitmapEqual);
  DefineMethod(klass, "src_rect", Sprite_SrcRect);
  DefineMethod(klass, "src_rect=", Sprite_SrcRectEqual);
  DefineMethod(klass, "x", Sprite_X);
  DefineMethod(klass, "x=", Sprite_XEqual);
  DefineMethod(klass, "y", Sprite_Y);
  DefineMethod(klass, "y=", Sprite_YEqual);
  DefineMethod(klass, "ox", Sprite_OX);
  DefineMethod(klass, "ox=", Sprite_OXEqual);
  DefineMethod(klass, "oy", Sprite_OY);
  DefineMethod(klass, "oy=", Sprite_OYEqual);
  DefineMethod(klass, "zoom_x", Sprite_ZoomX);
  DefineMethod(klass, "zoom_x=", Sprite_ZoomXEqual);
  DefineMethod(klass, "zoom_y", Sprite_ZoomY);
  DefineMethod(klass, "zoom_y=", Sprite_ZoomYEqual);
  DefineMethod(klass, "angle", Sprite_Angle);
  DefineMethod(klass, "angle=", Sprite_AngleEqual);
  DefineMethod(klass, "wave_amp", Sprite_WaveAmp);
  DefineMethod(klass, "wave_amp=", Sprite_WaveAmpEqual);
  DefineMethod(klass, "wave_length", Sprite_WaveLength);
  DefineMethod(klass, "wave_length=", Sprite_WaveLengthEqual);
  DefineMethod(klass, "wave_speed", Sprite_WaveSpeed);
  DefineMethod(klass, "wave_speed=", Sprite_WaveSpeedEqual);
  DefineMethod(klass, "wave_phase", Sprite_WavePhase);
  DefineMethod(klass, "wave_phase=", Sprite_WavePhaseEqual);
  DefineMethod(klass, "mirror", Sprite_Mirror);
  DefineMethod(klass, "mirror=", Sprite_MirrorEqual);
  DefineMethod(klass, "bush_depth", Sprite_BushDepth);
  DefineMethod(klass, "bush_depth=", Sprite_BushDepthEqual);
  DefineMethod(klass, "bush_opacity", Sprite_BushOpacity);
  DefineMethod(klass, "bush_opacity=", Sprite_BushOpacityEqual);
  DefineMethod(klass, "opacity", Sprite_Opacity);
  DefineMethod(klass, "opacity=", Sprite_OpacityEqual);
  DefineMethod(klass, "blend_type", Sprite_BlendType);
  DefineMethod(klass, "blend_type=", Sprite_BlendTypeEqual);
  DefineMethod(klass, "color", Sprite_Color);
  DefineMethod(klass, "color=", Sprite_ColorEqual);
  DefineMethod(klass, "tone", Sprite_Tone);
  DefineMethod(klass, "tone=", Sprite_ToneEqual);
  DefineMethod(klass, "effect", Sprite_Effect);
  DefineMethod(klass, "effect=", Sprite_EffectEqual);
  InitSpriteBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitSpriteBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitSpriteBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
