// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_buffer_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUBufferDescriptor  (core/gpu.h:62-84)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUBufferDescriptor, GPUObject);

RB_FUNC(GPUBufferDescriptor_initialize) {
  urge::RefPtr<urge::GPUBufferDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUBufferDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUBufferDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUBufferDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBufferDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUBufferDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBufferDescriptor_GetSize) {
  auto* self_obj = GetSelfData<urge::GPUBufferDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULL2NUM(self_obj->GetSize());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBufferDescriptor_SetSize) {
  auto* self_obj = GetSelfData<urge::GPUBufferDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    uint64_t value;
    ParseArgs(argc, argv, "p", &value);

    self_obj->SetSize(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: usage (uint32_t)
BINDING_ATTR_INT(GPUBufferDescriptor, urge::GPUBufferDescriptor, Usage);

// Attribute: mapped_at_creation (bool)
BINDING_ATTR_BOOL(GPUBufferDescriptor,
                  urge::GPUBufferDescriptor,
                  MappedAtCreation);

void InitGPUBufferDescriptorBindingAppend(VALUE klass);

void InitGPUBufferDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUBufferDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUBufferDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUBufferDescriptor_initialize);
  DefineMethod(klass, "label", GPUBufferDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUBufferDescriptor_SetLabel);
  DefineMethod(klass, "size", GPUBufferDescriptor_GetSize);
  DefineMethod(klass, "size=", GPUBufferDescriptor_SetSize);
  DefineMethod(klass, "usage", GPUBufferDescriptor_Usage);
  DefineMethod(klass, "usage=", GPUBufferDescriptor_UsageEqual);
  DefineMethod(klass, "mapped_at_creation", GPUBufferDescriptor_MappedAtCreation);
  DefineMethod(klass, "mapped_at_creation=", GPUBufferDescriptor_MappedAtCreationEqual);
  InitGPUBufferDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUBufferDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUBufferDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
