// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_vector3.h"

#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Vector3  (core/utility.h:301-317)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Vector3);

RB_FUNC(Vector3_initialize) {
  urge::RefPtr<urge::Vector3> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Vector3>();
    } else if (argc == 1) {
      // initialize(v)
      double v;
      ParseArgs(argc, argv, "f", &v);
      obj = urge::MakeRefCounted<urge::Vector3>(static_cast<float>(v));
    } else if (argc == 3) {
      // initialize(xv, yv, zv)
      double xv, yv, zv;
      ParseArgs(argc, argv, "fff", &xv, &yv, &zv);
      obj = urge::MakeRefCounted<urge::Vector3>(static_cast<float>(xv),
          static_cast<float>(yv), static_cast<float>(zv));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Vector3_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Vector3> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Vector3>(other, kVector3DataType);
    obj = urge::MakeRefCounted<urge::Vector3>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Vector3_Set) {
  auto* self_obj = GetSelfData<urge::Vector3>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // set(v)
      VALUE v_val;
      ParseArgs(argc, argv, "o", &v_val);
      self_obj->Set(GetObject<urge::Vector3>(v_val, kVector3DataType));
    } else if (argc == 3) {
      // set(xv, yv, zv)
      double xv, yv, zv;
      ParseArgs(argc, argv, "fff", &xv, &yv, &zv);
      self_obj->Set(static_cast<float>(xv), static_cast<float>(yv),
          static_cast<float>(zv));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

void InitVector3BindingAppend(VALUE klass);

void InitVector3Binding() {
  auto klass = rb_define_class("Vector3", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kVector3DataType>);

  DefineMethod(klass, "initialize", Vector3_initialize);
  DefineMethod(klass, "initialize_copy", Vector3_initialize_copy);
  DefineMethod(klass, "set", Vector3_Set);
  InitVector3BindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitVector3Binding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitVector3BindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
