// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_table.h"

#include "core/table.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// `Table#[]` / `Table#[]=` are hand written: Ruby hands the operands in
// (x[, y[, z]]) order with the value last, while `Table::Get` / `Table::Set`
// take the value first, so the arguments have to be reordered.  Out of range
// reads answer nil and out of range writes are ignored.
RB_FUNC(Table_Get) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // [](x)
      int x;
      ParseArgs(argc, argv, "i", &x);
      if (x < 0 || x >= self_obj->Xsize())
        return Qnil;
      return INT2NUM(self_obj->Get(x));
    } else if (argc == 2) {
      // [](x, y)
      int x, y;
      ParseArgs(argc, argv, "ii", &x, &y);
      if (x < 0 || x >= self_obj->Xsize() || y < 0 || y >= self_obj->Ysize())
        return Qnil;
      return INT2NUM(self_obj->Get(x, y));
    } else if (argc == 3) {
      // [](x, y, z)
      int x, y, z;
      ParseArgs(argc, argv, "iii", &x, &y, &z);
      if (x < 0 || x >= self_obj->Xsize() || y < 0 || y >= self_obj->Ysize() ||
          z < 0 || z >= self_obj->Zsize())
        return Qnil;
      return INT2NUM(self_obj->Get(x, y, z));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Table_Set) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  int x = 0, y = 0, z = 0, value = 0;
  EXC_BEGIN {
    if (argc == 2) {
      // []=(x, value)
      ParseArgs(argc, argv, "ii", &x, &value);
    } else if (argc == 3) {
      // []=(x, y, value)
      ParseArgs(argc, argv, "iii", &x, &y, &value);
    } else if (argc == 4) {
      // []=(x, y, z, value)
      ParseArgs(argc, argv, "iiii", &x, &y, &z, &value);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }

    if (x < 0 || x >= self_obj->Xsize() || y < 0 || y >= self_obj->Ysize() ||
        z < 0 || z >= self_obj->Zsize()) {
      return Qnil;
    }

    self_obj->Set(static_cast<int16_t>(value), x, y, z);
  }
  EXC_END;
  return Qnil;
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Table  (core/table.h:33-56)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Table);

RB_FUNC(Table_initialize) {
  urge::RefPtr<urge::Table> obj = nullptr;
  EXC_BEGIN {
    if (argc == 1) {
      // initialize(xsize)
      int xsize;
      ParseArgs(argc, argv, "i", &xsize);
      obj = urge::MakeRefCounted<urge::Table>(xsize);
    } else if (argc == 2) {
      // initialize(xsize, ysize)
      int xsize, ysize;
      ParseArgs(argc, argv, "ii", &xsize, &ysize);
      obj = urge::MakeRefCounted<urge::Table>(xsize, ysize);
    } else if (argc == 3) {
      // initialize(xsize, ysize, zsize)
      int xsize, ysize, zsize;
      ParseArgs(argc, argv, "iii", &xsize, &ysize, &zsize);
      obj = urge::MakeRefCounted<urge::Table>(xsize, ysize, zsize);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Table_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Table> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Table>(other, kTableDataType);
    obj = urge::MakeRefCounted<urge::Table>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Table__dump) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  EXC_BEGIN {
    std::string result =
        urge::Table::MarshalDump(urge::RefPtr<urge::Table>(self_obj));
    return rb_str_new(result.data(), static_cast<long>(result.size()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Table__load) {
  std::string data;
  ParseArgs(argc, argv, "s", &data);

  EXC_BEGIN {
    VALUE obj = rb_obj_alloc(self);
    auto ptr = urge::Table::MarshalLoad(data);
    return SetupSelfData(obj, ptr.get());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Table_Resize) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // resize(xsize)
      int xsize;
      ParseArgs(argc, argv, "i", &xsize);
      self_obj->Resize(xsize);
    } else if (argc == 2) {
      // resize(xsize, ysize)
      int xsize, ysize;
      ParseArgs(argc, argv, "ii", &xsize, &ysize);
      self_obj->Resize(xsize, ysize);
    } else if (argc == 3) {
      // resize(xsize, ysize, zsize)
      int xsize, ysize, zsize;
      ParseArgs(argc, argv, "iii", &xsize, &ysize, &zsize);
      self_obj->Resize(xsize, ysize, zsize);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Table_Xsize) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Xsize());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Table_Ysize) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Ysize());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Table_Zsize) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Zsize());
  }
  EXC_END;
  return Qnil;
}

void InitTableBindingAppend(VALUE klass);

void InitTableBinding() {
  auto klass = rb_define_class("Table", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kTableDataType>);

  DefineMethod(klass, "initialize", Table_initialize);
  DefineMethod(klass, "initialize_copy", Table_initialize_copy);
  DefineMethod(klass, "resize", Table_Resize);
  DefineMethod(klass, "xsize", Table_Xsize);
  DefineMethod(klass, "ysize", Table_Ysize);
  DefineMethod(klass, "zsize", Table_Zsize);
  DefineMethod(klass, "[]", Table_Get);
  DefineMethod(klass, "[]=", Table_Set);
  DefineMethod(klass, "_dump", Table__dump);
  DefineClassMethod(klass, "_load", Table__load);
  InitTableBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitTableBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitTableBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
