#pragma once

// Generated by bind/generate_binding.py -- do not edit.
// Rules: bind/Bindgen.md

#include "cruby_utils.h"

namespace binding {

// Defines the RGSS exception classes, every exported class and every exported
// module, in dependency order. Requires a live Ruby VM (`ruby_init()` must have
// run first) and redefines the classes when called again, so call it once.
void InitBindings();

}  // namespace binding
