// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_texture.h"

#include "binding_gpu_object.h"
#include "binding_gpu_texture_view.h"
#include "binding_gpu_texture_view_descriptor.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUTexture  (core/gpu.h:714-740)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUTexture, GPUObject);

RB_FUNC(GPUTexture_Width) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->Width());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_Height) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->Height());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_DepthOrArrayLayers) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->DepthOrArrayLayers());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_MipLevelCount) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->MipLevelCount());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_SampleCount) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->SampleCount());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_Dimension) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->Dimension());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_Format) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->Format());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_Usage) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULONG2NUM(self_obj->Usage());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_CreateView) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    if (argc == 0) {
      // create_view()
      auto result = self_obj->CreateView();
      return WrapObject(result.get(), kGPUTextureViewDataType);
    } else if (argc == 1) {
      // create_view(descriptor)
      VALUE descriptor_val;
      ParseArgs(argc, argv, "o", &descriptor_val);
      auto result = self_obj->CreateView(GetObject<urge::GPUTextureViewDescriptor>(descriptor_val, kGPUTextureViewDescriptorDataType));
      return WrapObject(result.get(), kGPUTextureViewDataType);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUTexture_Destroy) {
  auto* self_obj = GetSelfData<urge::GPUTexture>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Destroy();
  }
  EXC_END;
  return Qnil;
}

void InitGPUTextureBindingAppend(VALUE klass);

void InitGPUTextureBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUTexture", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUTextureDataType>);

  DefineMethod(klass, "width", GPUTexture_Width);
  DefineMethod(klass, "height", GPUTexture_Height);
  DefineMethod(klass, "depth_or_array_layers", GPUTexture_DepthOrArrayLayers);
  DefineMethod(klass, "mip_level_count", GPUTexture_MipLevelCount);
  DefineMethod(klass, "sample_count", GPUTexture_SampleCount);
  DefineMethod(klass, "dimension", GPUTexture_Dimension);
  DefineMethod(klass, "format", GPUTexture_Format);
  DefineMethod(klass, "usage", GPUTexture_Usage);
  DefineMethod(klass, "create_view", GPUTexture_CreateView);
  DefineMethod(klass, "destroy", GPUTexture_Destroy);
  InitGPUTextureBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUTextureBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUTextureBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
