// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_node.h"

#include "binding_bitmap.h"
#include "binding_color.h"
#include "binding_disposable.h"
#include "binding_vector3.h"
#include "binding_vector4.h"

#include "core/bitmap.h"
#include "core/node.h"
#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Node  (core/node.h:34-59)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(Node, Disposable);

RB_FUNC(Node_initialize) {
  urge::RefPtr<urge::Node> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::Node>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Node_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Node> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Node>(other, kNodeDataType);
    obj = urge::MakeRefCounted<urge::Node>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Node_Render) {
  auto* self_obj = GetSelfData<urge::Node>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // render(target)
      VALUE target_val;
      ParseArgs(argc, argv, "o", &target_val);
      self_obj->Render(GetObject<urge::Bitmap>(target_val, kBitmapDataType));
    } else if (argc == 2) {
      // render(target, clear)
      VALUE target_val, clear_val;
      ParseArgs(argc, argv, "oo", &target_val, &clear_val);
      self_obj->Render(GetObject<urge::Bitmap>(target_val, kBitmapDataType),
          GetObject<urge::Color>(clear_val, kColorDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

// Attribute: z (int32_t)
BINDING_ATTR_INT(Node, urge::Node, Z);

// Attribute: visible (bool)
BINDING_ATTR_BOOL(Node, urge::Node, Visible);

// Attribute: parent (RefPtr<Node>)
BINDING_ATTR_OBJECT_REF(Node, urge::Node, Parent, urge::Node, kNodeDataType);

// Attribute: position (RefPtr<Vector3>)
BINDING_ATTR_OBJECT_REF(Node,
                        urge::Node,
                        Position,
                        urge::Vector3,
                        kVector3DataType);

// Attribute: quaternion (RefPtr<Vector4>)
BINDING_ATTR_OBJECT_REF(Node,
                        urge::Node,
                        Quaternion,
                        urge::Vector4,
                        kVector4DataType);

// Attribute: scale (RefPtr<Vector3>)
BINDING_ATTR_OBJECT_REF(Node,
                        urge::Node,
                        Scale,
                        urge::Vector3,
                        kVector3DataType);

void InitNodeBindingAppend(VALUE klass);

void InitNodeBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Disposable"));
  auto klass = rb_define_class("Node", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kNodeDataType>);

  DefineMethod(klass, "initialize", Node_initialize);
  DefineMethod(klass, "initialize_copy", Node_initialize_copy);
  DefineMethod(klass, "render", Node_Render);
  DefineMethod(klass, "z", Node_Z);
  DefineMethod(klass, "z=", Node_ZEqual);
  DefineMethod(klass, "visible", Node_Visible);
  DefineMethod(klass, "visible=", Node_VisibleEqual);
  DefineMethod(klass, "parent", Node_Parent);
  DefineMethod(klass, "parent=", Node_ParentEqual);
  DefineMethod(klass, "position", Node_Position);
  DefineMethod(klass, "position=", Node_PositionEqual);
  DefineMethod(klass, "quaternion", Node_Quaternion);
  DefineMethod(klass, "quaternion=", Node_QuaternionEqual);
  DefineMethod(klass, "scale", Node_Scale);
  DefineMethod(klass, "scale=", Node_ScaleEqual);
  InitNodeBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitNodeBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitNodeBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
