// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_tone.h"

#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Tone  (core/utility.h:183-226)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Tone);

RB_FUNC(Tone_initialize) {
  urge::RefPtr<urge::Tone> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Tone>();
    } else if (argc == 3) {
      // initialize(r, g, b)
      double r, g, b;
      ParseArgs(argc, argv, "fff", &r, &g, &b);
      obj = urge::MakeRefCounted<urge::Tone>(static_cast<float>(r),
          static_cast<float>(g), static_cast<float>(b));
    } else if (argc == 4) {
      // initialize(r, g, b, a)
      double r, g, b, a;
      ParseArgs(argc, argv, "ffff", &r, &g, &b, &a);
      obj = urge::MakeRefCounted<urge::Tone>(static_cast<float>(r),
          static_cast<float>(g), static_cast<float>(b), static_cast<float>(a));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Tone_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Tone> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Tone>(other, kToneDataType);
    obj = urge::MakeRefCounted<urge::Tone>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Tone__dump) {
  auto* self_obj = GetSelfData<urge::Tone>(self);

  EXC_BEGIN {
    std::string result =
        urge::Tone::MarshalDump(urge::RefPtr<urge::Tone>(self_obj));
    return rb_str_new(result.data(), static_cast<long>(result.size()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Tone__load) {
  std::string data;
  ParseArgs(argc, argv, "s", &data);

  EXC_BEGIN {
    VALUE obj = rb_obj_alloc(self);
    auto ptr = urge::Tone::MarshalLoad(data);
    return SetupSelfData(obj, ptr.get());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Tone_Set) {
  auto* self_obj = GetSelfData<urge::Tone>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // set(tone)
      VALUE tone_val;
      ParseArgs(argc, argv, "o", &tone_val);
      self_obj->Set(GetObject<urge::Tone>(tone_val, kToneDataType));
    } else if (argc == 3) {
      // set(r, g, b)
      double r, g, b;
      ParseArgs(argc, argv, "fff", &r, &g, &b);
      self_obj->Set(static_cast<float>(r), static_cast<float>(g),
          static_cast<float>(b));
    } else if (argc == 4) {
      // set(r, g, b, a)
      double r, g, b, a;
      ParseArgs(argc, argv, "ffff", &r, &g, &b, &a);
      self_obj->Set(static_cast<float>(r), static_cast<float>(g),
          static_cast<float>(b), static_cast<float>(a));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

// Attribute: red (float)
BINDING_ATTR_FLOAT(Tone, urge::Tone, Red);

// Attribute: green (float)
BINDING_ATTR_FLOAT(Tone, urge::Tone, Green);

// Attribute: blue (float)
BINDING_ATTR_FLOAT(Tone, urge::Tone, Blue);

// Attribute: gray (float)
BINDING_ATTR_FLOAT(Tone, urge::Tone, Gray);

void InitToneBindingAppend(VALUE klass);

void InitToneBinding() {
  auto klass = rb_define_class("Tone", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kToneDataType>);

  DefineMethod(klass, "initialize", Tone_initialize);
  DefineMethod(klass, "initialize_copy", Tone_initialize_copy);
  DefineMethod(klass, "set", Tone_Set);
  DefineMethod(klass, "_dump", Tone__dump);
  DefineClassMethod(klass, "_load", Tone__load);
  DefineMethod(klass, "red", Tone_Red);
  DefineMethod(klass, "red=", Tone_RedEqual);
  DefineMethod(klass, "green", Tone_Green);
  DefineMethod(klass, "green=", Tone_GreenEqual);
  DefineMethod(klass, "blue", Tone_Blue);
  DefineMethod(klass, "blue=", Tone_BlueEqual);
  DefineMethod(klass, "gray", Tone_Gray);
  DefineMethod(klass, "gray=", Tone_GrayEqual);
  InitToneBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitToneBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitToneBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
