// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_tilemap_vx.h"

#include "binding_bitmap.h"
#include "binding_node.h"
#include "binding_table.h"
#include "binding_viewport.h"

#include "core/bitmap.h"
#include "core/table.h"
#include "core/tilemap_vx.h"
#include "core/viewport.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
VALUE AllocateBitmapsProxy(VALUE parent, const char* klass_name) {
  VALUE klass = rb_const_get(rb_cObject, rb_intern(klass_name));
  VALUE obj = rb_obj_alloc(klass);
  rb_iv_set(obj, "@parent", parent);
  return obj;
}

RB_FUNC(TilemapBitmaps_Get) {
  auto parent = GetObject<urge::TilemapVX>(rb_iv_get(self, "@parent"),
                                           kTilemapVXDataType);
  int index;
  ParseArgs(argc, argv, "i", &index);

  EXC_BEGIN {
    auto result = parent->GetBitmap(index);
    if (result)
      return WrapObject(result.get(), kBitmapDataType);
    return Qnil;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapBitmaps_Set) {
  auto parent = GetObject<urge::TilemapVX>(rb_iv_get(self, "@parent"),
                                           kTilemapVXDataType);
  int index;
  VALUE bitmap_val;
  ParseArgs(argc, argv, "io", &index, &bitmap_val);

  auto bitmap = GetObject<urge::Bitmap>(bitmap_val, kBitmapDataType);

  EXC_BEGIN {
    parent->SetBitmap(index, bitmap);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Tilemap_GetBitmaps) {
  return AllocateBitmapsProxy(self, "TilemapBitmapArray");
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// TilemapVX  (core/tilemap_vx.h:56-87)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(TilemapVX, Node);

RB_FUNC(TilemapVX_initialize) {
  urge::RefPtr<urge::TilemapVX> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::TilemapVX>();
    } else if (argc == 1) {
      // initialize(viewport)
      VALUE viewport_val;
      ParseArgs(argc, argv, "o", &viewport_val);
      obj = urge::MakeRefCounted<urge::TilemapVX>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType));
    } else if (argc == 2) {
      // initialize(viewport, tilesize)
      VALUE viewport_val;
      int tilesize;
      ParseArgs(argc, argv, "oi", &viewport_val, &tilesize);
      obj = urge::MakeRefCounted<urge::TilemapVX>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType), tilesize);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(TilemapVX_Update) {
  auto* self_obj = GetSelfData<urge::TilemapVX>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapVX_SetBitmap) {
  auto* self_obj = GetSelfData<urge::TilemapVX>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    int index;
    VALUE bitmap_val;
    ParseArgs(argc, argv, "io", &index, &bitmap_val);

    self_obj->SetBitmap(index,
        GetObject<urge::Bitmap>(bitmap_val, kBitmapDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(TilemapVX_GetBitmap) {
  auto* self_obj = GetSelfData<urge::TilemapVX>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    int index;
    ParseArgs(argc, argv, "i", &index);

    auto result = self_obj->GetBitmap(index);
    return WrapObject(result.get(), kBitmapDataType);
  }
  EXC_END;
  return Qnil;
}

// Attribute: viewport (RefPtr<Viewport>)
BINDING_ATTR_OBJECT_REF(TilemapVX,
                        urge::TilemapVX,
                        Viewport,
                        urge::Viewport,
                        kViewportDataType);

// Attribute: visible (bool)
BINDING_ATTR_BOOL(TilemapVX, urge::TilemapVX, Visible);

// Attribute: z (int32_t)
BINDING_ATTR_INT(TilemapVX, urge::TilemapVX, Z);

// Attribute: map_data (RefPtr<Table>)
BINDING_ATTR_OBJECT(TilemapVX,
                    urge::TilemapVX,
                    MapData,
                    urge::Table,
                    kTableDataType);

// Attribute: flash_data (RefPtr<Table>)
BINDING_ATTR_OBJECT(TilemapVX,
                    urge::TilemapVX,
                    FlashData,
                    urge::Table,
                    kTableDataType);

// Attribute: flags (RefPtr<Table>)
BINDING_ATTR_OBJECT(TilemapVX,
                    urge::TilemapVX,
                    Flags,
                    urge::Table,
                    kTableDataType);

// Attribute: passages (RefPtr<Table>)
BINDING_ATTR_OBJECT(TilemapVX,
                    urge::TilemapVX,
                    Passages,
                    urge::Table,
                    kTableDataType);

// Attribute: ox (int32_t)
BINDING_ATTR_INT(TilemapVX, urge::TilemapVX, OX);

// Attribute: oy (int32_t)
BINDING_ATTR_INT(TilemapVX, urge::TilemapVX, OY);

void InitTilemapVXBindingAppend(VALUE klass);

void InitTilemapVXBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("TilemapVX", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kTilemapVXDataType>);

  DefineMethod(klass, "initialize", TilemapVX_initialize);
  DefineMethod(klass, "update", TilemapVX_Update);
  DefineMethod(klass, "set_bitmap", TilemapVX_SetBitmap);
  DefineMethod(klass, "get_bitmap", TilemapVX_GetBitmap);
  DefineMethod(klass, "viewport", TilemapVX_Viewport);
  DefineMethod(klass, "viewport=", TilemapVX_ViewportEqual);
  DefineMethod(klass, "visible", TilemapVX_Visible);
  DefineMethod(klass, "visible=", TilemapVX_VisibleEqual);
  DefineMethod(klass, "z", TilemapVX_Z);
  DefineMethod(klass, "z=", TilemapVX_ZEqual);
  DefineMethod(klass, "map_data", TilemapVX_MapData);
  DefineMethod(klass, "map_data=", TilemapVX_MapDataEqual);
  DefineMethod(klass, "flash_data", TilemapVX_FlashData);
  DefineMethod(klass, "flash_data=", TilemapVX_FlashDataEqual);
  DefineMethod(klass, "flags", TilemapVX_Flags);
  DefineMethod(klass, "flags=", TilemapVX_FlagsEqual);
  DefineMethod(klass, "passages", TilemapVX_Passages);
  DefineMethod(klass, "passages=", TilemapVX_PassagesEqual);
  DefineMethod(klass, "ox", TilemapVX_OX);
  DefineMethod(klass, "ox=", TilemapVX_OXEqual);
  DefineMethod(klass, "oy", TilemapVX_OY);
  DefineMethod(klass, "oy=", TilemapVX_OYEqual);
  InitTilemapVXBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// The tilemap exposes its eight tile bitmaps as one array-like object, the
// same way RGSS does: `Tilemap#bitmaps[0]` rather than eight accessors.  The
// proxy class is defined here because the IR has no way to describe it, and
// the accessor it reads through lives in the HANDWRITTEN block above.
void InitTilemapVXBindingAppend(VALUE klass) {
  // The default allocator is kept: the proxy carries its parent in an
  // instance variable and the accessors above read it back, so it has to be
  // allocatable without going through `initialize`.
  auto proxy = rb_define_class("TilemapBitmapArray", rb_cObject);
  DefineMethod(proxy, "[]", TilemapBitmaps_Get);
  DefineMethod(proxy, "[]=", TilemapBitmaps_Set);

  DefineMethod(klass, "bitmaps", Tilemap_GetBitmaps);
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
