// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_rect.h"

#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Rect  (core/utility.h:46-108)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Rect);

RB_FUNC(Rect_initialize) {
  urge::RefPtr<urge::Rect> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Rect>();
    } else if (argc == 4) {
      // initialize(xv, yv, wv, hv)
      int xv, yv, wv, hv;
      ParseArgs(argc, argv, "iiii", &xv, &yv, &wv, &hv);
      obj = urge::MakeRefCounted<urge::Rect>(xv, yv, wv, hv);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Rect_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Rect> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Rect>(other, kRectDataType);
    obj = urge::MakeRefCounted<urge::Rect>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Rect__dump) {
  auto* self_obj = GetSelfData<urge::Rect>(self);

  EXC_BEGIN {
    std::string result =
        urge::Rect::MarshalDump(urge::RefPtr<urge::Rect>(self_obj));
    return rb_str_new(result.data(), static_cast<long>(result.size()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Rect__load) {
  std::string data;
  ParseArgs(argc, argv, "s", &data);

  EXC_BEGIN {
    VALUE obj = rb_obj_alloc(self);
    auto ptr = urge::Rect::MarshalLoad(data);
    return SetupSelfData(obj, ptr.get());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Rect_Set) {
  auto* self_obj = GetSelfData<urge::Rect>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // set(rect)
      VALUE rect_val;
      ParseArgs(argc, argv, "o", &rect_val);
      self_obj->Set(GetObject<urge::Rect>(rect_val, kRectDataType));
    } else if (argc == 4) {
      // set(xv, yv, wv, hv)
      int xv, yv, wv, hv;
      ParseArgs(argc, argv, "iiii", &xv, &yv, &wv, &hv);
      self_obj->Set(xv, yv, wv, hv);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Rect_Empty) {
  auto* self_obj = GetSelfData<urge::Rect>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Empty();
  }
  EXC_END;
  return Qnil;
}

// Attribute: x (int32_t)
BINDING_ATTR_INT(Rect, urge::Rect, X);

// Attribute: y (int32_t)
BINDING_ATTR_INT(Rect, urge::Rect, Y);

// Attribute: width (int32_t)
BINDING_ATTR_INT(Rect, urge::Rect, Width);

// Attribute: height (int32_t)
BINDING_ATTR_INT(Rect, urge::Rect, Height);

void InitRectBindingAppend(VALUE klass);

void InitRectBinding() {
  auto klass = rb_define_class("Rect", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kRectDataType>);

  DefineMethod(klass, "initialize", Rect_initialize);
  DefineMethod(klass, "initialize_copy", Rect_initialize_copy);
  DefineMethod(klass, "set", Rect_Set);
  DefineMethod(klass, "empty", Rect_Empty);
  DefineMethod(klass, "_dump", Rect__dump);
  DefineClassMethod(klass, "_load", Rect__load);
  DefineMethod(klass, "x", Rect_X);
  DefineMethod(klass, "x=", Rect_XEqual);
  DefineMethod(klass, "y", Rect_Y);
  DefineMethod(klass, "y=", Rect_YEqual);
  DefineMethod(klass, "width", Rect_Width);
  DefineMethod(klass, "width=", Rect_WidthEqual);
  DefineMethod(klass, "height", Rect_Height);
  DefineMethod(klass, "height=", Rect_HeightEqual);
  InitRectBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitRectBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitRectBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
