// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_font.h"

#include "binding_color.h"

#include "core/font.h"
#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Font  (core/font.h:40-69)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Font);

RB_FUNC(Font_initialize) {
  urge::RefPtr<urge::Font> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Font>();
    } else if (argc == 1) {
      // initialize(names)
      VALUE names_val;
      ParseArgs(argc, argv, "o", &names_val);
      obj = urge::MakeRefCounted<urge::Font>(GetStringVector(names_val));
    } else if (argc == 2) {
      // initialize(names, size)
      VALUE names_val;
      int size;
      ParseArgs(argc, argv, "oi", &names_val, &size);
      obj = urge::MakeRefCounted<urge::Font>(GetStringVector(names_val), size);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Font_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Font> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Font>(other, kFontDataType);
    obj = urge::MakeRefCounted<urge::Font>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Font_Existed) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string name;
    ParseArgs(argc, argv, "s", &name);

    return urge::Font::Existed(name) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

// Attribute: name (std::vector<std::string>)
BINDING_ATTR_STRINGVECTOR(Font, urge::Font, Name);

// Attribute: size (int32_t)
BINDING_ATTR_INT(Font, urge::Font, Size);

// Attribute: bold (bool)
BINDING_ATTR_BOOL(Font, urge::Font, Bold);

// Attribute: italic (bool)
BINDING_ATTR_BOOL(Font, urge::Font, Italic);

// Attribute: outline (bool)
BINDING_ATTR_BOOL(Font, urge::Font, Outline);

// Attribute: shadow (bool)
BINDING_ATTR_BOOL(Font, urge::Font, Shadow);

// Attribute: solid (bool)
BINDING_ATTR_BOOL(Font, urge::Font, Solid);

// Attribute: color (RefPtr<Color>)
BINDING_ATTR_OBJECT(Font, urge::Font, Color, urge::Color, kColorDataType);

// Attribute: out_color (RefPtr<Color>)
BINDING_ATTR_OBJECT(Font, urge::Font, OutColor, urge::Color, kColorDataType);

// Attribute: gradient_color (RefPtr<Color>)
BINDING_ATTR_OBJECT(Font,
                    urge::Font,
                    GradientColor,
                    urge::Color,
                    kColorDataType);

// Class attribute: default_name (std::vector<std::string>)
BINDING_CLASS_ATTR_STRINGVECTOR(Font, urge::Font, DefaultName);

// Class attribute: default_size (int32_t)
BINDING_CLASS_ATTR_INT(Font, urge::Font, DefaultSize);

// Class attribute: default_bold (bool)
BINDING_CLASS_ATTR_BOOL(Font, urge::Font, DefaultBold);

// Class attribute: default_italic (bool)
BINDING_CLASS_ATTR_BOOL(Font, urge::Font, DefaultItalic);

// Class attribute: default_outline (bool)
BINDING_CLASS_ATTR_BOOL(Font, urge::Font, DefaultOutline);

// Class attribute: default_shadow (bool)
BINDING_CLASS_ATTR_BOOL(Font, urge::Font, DefaultShadow);

// Class attribute: default_solid (bool)
BINDING_CLASS_ATTR_BOOL(Font, urge::Font, DefaultSolid);

// Class attribute: default_color (RefPtr<Color>)
BINDING_CLASS_ATTR_OBJECT(Font,
                          urge::Font,
                          DefaultColor,
                          urge::Color,
                          kColorDataType);

// Class attribute: default_out_color (RefPtr<Color>)
BINDING_CLASS_ATTR_OBJECT(Font,
                          urge::Font,
                          DefaultOutColor,
                          urge::Color,
                          kColorDataType);

// Class attribute: default_gradient_color (RefPtr<Color>)
BINDING_CLASS_ATTR_OBJECT(Font,
                          urge::Font,
                          DefaultGradientColor,
                          urge::Color,
                          kColorDataType);

void InitFontBindingAppend(VALUE klass);

void InitFontBinding() {
  auto klass = rb_define_class("Font", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kFontDataType>);

  DefineMethod(klass, "initialize", Font_initialize);
  DefineMethod(klass, "initialize_copy", Font_initialize_copy);
  DefineClassMethod(klass, "exist?", Font_Existed);
  DefineMethod(klass, "name", Font_Name);
  DefineMethod(klass, "name=", Font_NameEqual);
  DefineMethod(klass, "size", Font_Size);
  DefineMethod(klass, "size=", Font_SizeEqual);
  DefineMethod(klass, "bold", Font_Bold);
  DefineMethod(klass, "bold=", Font_BoldEqual);
  DefineMethod(klass, "italic", Font_Italic);
  DefineMethod(klass, "italic=", Font_ItalicEqual);
  DefineMethod(klass, "outline", Font_Outline);
  DefineMethod(klass, "outline=", Font_OutlineEqual);
  DefineMethod(klass, "shadow", Font_Shadow);
  DefineMethod(klass, "shadow=", Font_ShadowEqual);
  DefineMethod(klass, "solid", Font_Solid);
  DefineMethod(klass, "solid=", Font_SolidEqual);
  DefineMethod(klass, "color", Font_Color);
  DefineMethod(klass, "color=", Font_ColorEqual);
  DefineMethod(klass, "out_color", Font_OutColor);
  DefineMethod(klass, "out_color=", Font_OutColorEqual);
  DefineMethod(klass, "gradient_color", Font_GradientColor);
  DefineMethod(klass, "gradient_color=", Font_GradientColorEqual);
  DefineClassMethod(klass, "default_name", Font_DefaultName);
  DefineClassMethod(klass, "default_name=", Font_DefaultNameEqual);
  DefineClassMethod(klass, "default_size", Font_DefaultSize);
  DefineClassMethod(klass, "default_size=", Font_DefaultSizeEqual);
  DefineClassMethod(klass, "default_bold", Font_DefaultBold);
  DefineClassMethod(klass, "default_bold=", Font_DefaultBoldEqual);
  DefineClassMethod(klass, "default_italic", Font_DefaultItalic);
  DefineClassMethod(klass, "default_italic=", Font_DefaultItalicEqual);
  DefineClassMethod(klass, "default_outline", Font_DefaultOutline);
  DefineClassMethod(klass, "default_outline=", Font_DefaultOutlineEqual);
  DefineClassMethod(klass, "default_shadow", Font_DefaultShadow);
  DefineClassMethod(klass, "default_shadow=", Font_DefaultShadowEqual);
  DefineClassMethod(klass, "default_solid", Font_DefaultSolid);
  DefineClassMethod(klass, "default_solid=", Font_DefaultSolidEqual);
  DefineClassMethod(klass, "default_color", Font_DefaultColor);
  DefineClassMethod(klass, "default_color=", Font_DefaultColorEqual);
  DefineClassMethod(klass, "default_out_color", Font_DefaultOutColor);
  DefineClassMethod(klass, "default_out_color=", Font_DefaultOutColorEqual);
  DefineClassMethod(klass, "default_gradient_color", Font_DefaultGradientColor);
  DefineClassMethod(klass, "default_gradient_color=", Font_DefaultGradientColorEqual);
  InitFontBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitFontBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitFontBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
