// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_network_event.h"

#include "core/network.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// `NetworkEvent#data` answers a Ruby String tagged ASCII-8BIT: the payload is
// raw bytes and the generated `s` codec would tag it UTF-8.  The C++ accessor
// therefore carries no `URGE_BINDING()` marker.
RB_FUNC(NetworkEvent_Data) {
  auto* self_obj = GetSelfData<urge::NetworkEvent>(self);

  const std::string& data = self_obj->data();
  return rb_enc_str_new(data.data(), static_cast<long>(data.size()),
                        rb_ascii8bit_encoding());
}

// The `Type` enum is registered by hand because the IR describes methods, not
// constants.
void DefineNetworkEventConstants(VALUE klass) {
  rb_const_set(klass, rb_intern("OPEN"), LONG2NUM(urge::NetworkEvent::Open));
  rb_const_set(klass, rb_intern("TEXT"), LONG2NUM(urge::NetworkEvent::Text));
  rb_const_set(klass, rb_intern("BINARY"),
               LONG2NUM(urge::NetworkEvent::Binary));
  rb_const_set(klass, rb_intern("CLOSE"), LONG2NUM(urge::NetworkEvent::Close));
  rb_const_set(klass, rb_intern("ERROR"), LONG2NUM(urge::NetworkEvent::Error));

  DefineMethod(klass, "data", NetworkEvent_Data);
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// NetworkEvent  (core/network.h:41-64)
// -------------------------------------------------------------------------

RB_DEF_TYPE(NetworkEvent);

RB_FUNC(NetworkEvent_initialize) {
  urge::RefPtr<urge::NetworkEvent> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::NetworkEvent>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(NetworkEvent_GetType) {
  auto* self_obj = GetSelfData<urge::NetworkEvent>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->GetType());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(NetworkEvent_GetText) {
  auto* self_obj = GetSelfData<urge::NetworkEvent>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetText();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(NetworkEvent_GetCode) {
  auto* self_obj = GetSelfData<urge::NetworkEvent>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->GetCode());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(NetworkEvent_GetReason) {
  auto* self_obj = GetSelfData<urge::NetworkEvent>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetReason();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(NetworkEvent_GetErrorMessage) {
  auto* self_obj = GetSelfData<urge::NetworkEvent>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetErrorMessage();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

void InitNetworkEventBindingAppend(VALUE klass);

void InitNetworkEventBinding() {
  auto klass = rb_define_class("NetworkEvent", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kNetworkEventDataType>);

  DefineMethod(klass, "initialize", NetworkEvent_initialize);
  DefineMethod(klass, "type", NetworkEvent_GetType);
  DefineMethod(klass, "text", NetworkEvent_GetText);
  DefineMethod(klass, "code", NetworkEvent_GetCode);
  DefineMethod(klass, "reason", NetworkEvent_GetReason);
  DefineMethod(klass, "message", NetworkEvent_GetErrorMessage);
  DefineNetworkEventConstants(klass);
  InitNetworkEventBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitNetworkEventBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitNetworkEventBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
