// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_color.h"

#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Color  (core/utility.h:126-183)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Color);

RB_FUNC(Color_initialize) {
  urge::RefPtr<urge::Color> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Color>();
    } else if (argc == 3) {
      // initialize(r, g, b)
      double r, g, b;
      ParseArgs(argc, argv, "fff", &r, &g, &b);
      obj = urge::MakeRefCounted<urge::Color>(static_cast<float>(r),
          static_cast<float>(g), static_cast<float>(b));
    } else if (argc == 4) {
      // initialize(r, g, b, a)
      double r, g, b, a;
      ParseArgs(argc, argv, "ffff", &r, &g, &b, &a);
      obj = urge::MakeRefCounted<urge::Color>(static_cast<float>(r),
          static_cast<float>(g), static_cast<float>(b), static_cast<float>(a));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Color_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Color> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Color>(other, kColorDataType);
    obj = urge::MakeRefCounted<urge::Color>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Color__dump) {
  auto* self_obj = GetSelfData<urge::Color>(self);

  EXC_BEGIN {
    std::string result =
        urge::Color::MarshalDump(urge::RefPtr<urge::Color>(self_obj));
    return rb_str_new(result.data(), static_cast<long>(result.size()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Color__load) {
  std::string data;
  ParseArgs(argc, argv, "s", &data);

  EXC_BEGIN {
    VALUE obj = rb_obj_alloc(self);
    auto ptr = urge::Color::MarshalLoad(data);
    return SetupSelfData(obj, ptr.get());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Color_Set) {
  auto* self_obj = GetSelfData<urge::Color>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // set(color)
      VALUE color_val;
      ParseArgs(argc, argv, "o", &color_val);
      self_obj->Set(GetObject<urge::Color>(color_val, kColorDataType));
    } else if (argc == 3) {
      // set(r, g, b)
      double r, g, b;
      ParseArgs(argc, argv, "fff", &r, &g, &b);
      self_obj->Set(static_cast<float>(r), static_cast<float>(g),
          static_cast<float>(b));
    } else if (argc == 4) {
      // set(r, g, b, a)
      double r, g, b, a;
      ParseArgs(argc, argv, "ffff", &r, &g, &b, &a);
      self_obj->Set(static_cast<float>(r), static_cast<float>(g),
          static_cast<float>(b), static_cast<float>(a));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

// Attribute: red (float)
BINDING_ATTR_FLOAT(Color, urge::Color, Red);

// Attribute: green (float)
BINDING_ATTR_FLOAT(Color, urge::Color, Green);

// Attribute: blue (float)
BINDING_ATTR_FLOAT(Color, urge::Color, Blue);

// Attribute: alpha (float)
BINDING_ATTR_FLOAT(Color, urge::Color, Alpha);

void InitColorBindingAppend(VALUE klass);

void InitColorBinding() {
  auto klass = rb_define_class("Color", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kColorDataType>);

  DefineMethod(klass, "initialize", Color_initialize);
  DefineMethod(klass, "initialize_copy", Color_initialize_copy);
  DefineMethod(klass, "set", Color_Set);
  DefineMethod(klass, "_dump", Color__dump);
  DefineClassMethod(klass, "_load", Color__load);
  DefineMethod(klass, "red", Color_Red);
  DefineMethod(klass, "red=", Color_RedEqual);
  DefineMethod(klass, "green", Color_Green);
  DefineMethod(klass, "green=", Color_GreenEqual);
  DefineMethod(klass, "blue", Color_Blue);
  DefineMethod(klass, "blue=", Color_BlueEqual);
  DefineMethod(klass, "alpha", Color_Alpha);
  DefineMethod(klass, "alpha=", Color_AlphaEqual);
  InitColorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitColorBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitColorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
