// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_palette.h"

#include "binding_color.h"

#include "core/palette.h"
#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Palette  (core/palette.h:37-45)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Palette);

RB_FUNC(Palette_initialize) {
  urge::RefPtr<urge::Palette> obj = nullptr;
  EXC_BEGIN {
    if (argc == 1) {
      // initialize(filename)
      std::string filename;
      ParseArgs(argc, argv, "s", &filename);
      obj = urge::MakeRefCounted<urge::Palette>(filename);
    } else if (argc == 2) {
      // initialize(width, height)
      int width, height;
      ParseArgs(argc, argv, "ii", &width, &height);
      obj = urge::MakeRefCounted<urge::Palette>(width, height);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Palette_GetPixel) {
  auto* self_obj = GetSelfData<urge::Palette>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    int x, y;
    ParseArgs(argc, argv, "ii", &x, &y);

    auto result = self_obj->GetPixel(x, y);
    return WrapObject(result.get(), kColorDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Palette_SetPixel) {
  auto* self_obj = GetSelfData<urge::Palette>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    int x, y;
    VALUE color_val;
    ParseArgs(argc, argv, "iio", &x, &y, &color_val);

    self_obj->SetPixel(x, y, GetObject<urge::Color>(color_val, kColorDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Palette_SaveFile) {
  auto* self_obj = GetSelfData<urge::Palette>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string filename;
    ParseArgs(argc, argv, "s", &filename);

    self_obj->SaveFile(filename);
  }
  EXC_END;
  return Qnil;
}

void InitPaletteBindingAppend(VALUE klass);

void InitPaletteBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Disposable"));
  auto klass = rb_define_class("Palette", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kPaletteDataType>);

  DefineMethod(klass, "initialize", Palette_initialize);
  DefineMethod(klass, "get_pixel", Palette_GetPixel);
  DefineMethod(klass, "set_pixel", Palette_SetPixel);
  DefineMethod(klass, "save_file", Palette_SaveFile);
  InitPaletteBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitPaletteBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitPaletteBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
