// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_network.h"

#include "binding_fetch.h"
#include "binding_web_socket.h"

#include "core/network.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Network  (core/network.h:184-201)
// -------------------------------------------------------------------------

RB_FUNC(Network_Update) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Network::Get().Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Network_OpenWebSocket) {
  EXC_BEGIN {
    if (argc == 1) {
      // websocket(url)
      std::string url;
      ParseArgs(argc, argv, "s", &url);
      auto result = urge::Network::Get().OpenWebSocket(url);
      return WrapObject(result.get(), kWebSocketDataType);
    } else if (argc == 2) {
      // websocket(url, protocols)
      std::string url;
      VALUE protocols_val;
      ParseArgs(argc, argv, "so", &url, &protocols_val);
      auto result = urge::Network::Get().OpenWebSocket(url, GetVectorOf<std::string>(protocols_val));
      return WrapObject(result.get(), kWebSocketDataType);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Network_OpenFetch) {
  EXC_BEGIN {
    if (argc == 1) {
      // fetch(url)
      std::string url;
      ParseArgs(argc, argv, "s", &url);
      auto result = urge::Network::Get().OpenFetch(url);
      return WrapObject(result.get(), kFetchDataType);
    } else if (argc == 2) {
      // fetch(url, method)
      std::string url, method;
      ParseArgs(argc, argv, "ss", &url, &method);
      auto result = urge::Network::Get().OpenFetch(url, method);
      return WrapObject(result.get(), kFetchDataType);
    } else if (argc == 3) {
      // fetch(url, method, body)
      std::string url, method, body;
      ParseArgs(argc, argv, "sss", &url, &method, &body);
      auto result = urge::Network::Get().OpenFetch(url, method, body);
      return WrapObject(result.get(), kFetchDataType);
    } else if (argc == 4) {
      // fetch(url, method, body, headers)
      std::string url, method, body;
      VALUE headers_val;
      ParseArgs(argc, argv, "ssso", &url, &method, &body, &headers_val);
      auto result = urge::Network::Get().OpenFetch(url, method, body, GetVectorOf<std::string>(headers_val));
      return WrapObject(result.get(), kFetchDataType);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Network_Timeout) {
  EXC_BEGIN {
    return LONG2NUM((*urge::Network::Get().Attr_Timeout()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Network_TimeoutEqual) {
  int value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "i", &value);
    urge::Network::Get().Attr_Timeout(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Network_MaxEvents) {
  EXC_BEGIN {
    return LONG2NUM((*urge::Network::Get().Attr_MaxEvents()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Network_MaxEventsEqual) {
  int value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "i", &value);
    urge::Network::Get().Attr_MaxEvents(value);
  }
  EXC_END;
  return Qnil;
}

void InitNetworkBindingAppend(VALUE mod);

void InitNetworkBinding() {
  auto mod = rb_define_module("Network");

  DefineModuleFunction(mod, "update", Network_Update);
  DefineModuleFunction(mod, "websocket", Network_OpenWebSocket);
  DefineModuleFunction(mod, "fetch", Network_OpenFetch);
  DefineModuleFunction(mod, "timeout", Network_Timeout);
  DefineModuleFunction(mod, "timeout=", Network_TimeoutEqual);
  DefineModuleFunction(mod, "max_events", Network_MaxEvents);
  DefineModuleFunction(mod, "max_events=", Network_MaxEventsEqual);
  InitNetworkBindingAppend(mod);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitNetworkBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitNetworkBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
