// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_web_socket.h"

#include "binding_network_event.h"

#include "core/network.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// The `ReadyState` enum, registered by hand for the same reason as the event
// types.
void DefineWebSocketConstants(VALUE klass) {
  rb_const_set(klass, rb_intern("CONNECTING"),
               LONG2NUM(urge::WebSocket::Connecting));
  rb_const_set(klass, rb_intern("OPEN"), LONG2NUM(urge::WebSocket::OpenState));
  rb_const_set(klass, rb_intern("CLOSING"),
               LONG2NUM(urge::WebSocket::Closing));
  rb_const_set(klass, rb_intern("CLOSED"),
               LONG2NUM(urge::WebSocket::ClosedState));
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// WebSocket  (core/network.h:78-112)
// -------------------------------------------------------------------------

RB_DEF_TYPE(WebSocket);

RB_FUNC(WebSocket_initialize) {
  urge::RefPtr<urge::WebSocket> obj = nullptr;
  EXC_BEGIN {
    if (argc == 1) {
      // initialize(url)
      std::string url;
      ParseArgs(argc, argv, "s", &url);
      obj = urge::MakeRefCounted<urge::WebSocket>(url);
    } else if (argc == 2) {
      // initialize(url, protocols)
      std::string url;
      VALUE protocols_val;
      ParseArgs(argc, argv, "so", &url, &protocols_val);
      obj = urge::MakeRefCounted<urge::WebSocket>(url,
          GetVectorOf<std::string>(protocols_val));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(WebSocket_GetUrl) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetUrl();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_GetReadyState) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->GetReadyState());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_GetError) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetError();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_GetDropped) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->GetDropped());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_SendText) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string data;
    ParseArgs(argc, argv, "s", &data);

    self_obj->SendText(data);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_SendBinary) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string data;
    ParseArgs(argc, argv, "s", &data);

    self_obj->SendBinary(data);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_SendPing) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    if (argc == 0) {
      // send_ping()
      self_obj->SendPing();
    } else if (argc == 1) {
      // send_ping(data)
      std::string data;
      ParseArgs(argc, argv, "s", &data);
      self_obj->SendPing(data);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_Close) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    if (argc == 0) {
      // close()
      self_obj->Close();
    } else if (argc == 1) {
      // close(code)
      int code;
      ParseArgs(argc, argv, "i", &code);
      self_obj->Close(code);
    } else if (argc == 2) {
      // close(code, reason)
      int code;
      std::string reason;
      ParseArgs(argc, argv, "is", &code, &reason);
      self_obj->Close(code, reason);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_NextEvent) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = self_obj->NextEvent();
    return WrapObject(result.get(), kNetworkEventDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WebSocket_GetPending) {
  auto* self_obj = GetSelfData<urge::WebSocket>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->GetPending());
  }
  EXC_END;
  return Qnil;
}

void InitWebSocketBindingAppend(VALUE klass);

void InitWebSocketBinding() {
  auto klass = rb_define_class("WebSocket", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kWebSocketDataType>);

  DefineMethod(klass, "initialize", WebSocket_initialize);
  DefineMethod(klass, "url", WebSocket_GetUrl);
  DefineMethod(klass, "ready_state", WebSocket_GetReadyState);
  DefineMethod(klass, "error", WebSocket_GetError);
  DefineMethod(klass, "dropped", WebSocket_GetDropped);
  DefineMethod(klass, "send_text", WebSocket_SendText);
  DefineMethod(klass, "send_binary", WebSocket_SendBinary);
  DefineMethod(klass, "send_ping", WebSocket_SendPing);
  DefineMethod(klass, "close", WebSocket_Close);
  DefineMethod(klass, "next_event", WebSocket_NextEvent);
  DefineMethod(klass, "pending", WebSocket_GetPending);
  DefineWebSocketConstants(klass);
  InitWebSocketBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitWebSocketBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitWebSocketBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
