// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_video.h"

#include "binding_audio_stream.h"
#include "binding_bitmap.h"

#include "core/audio_stream.h"
#include "core/bitmap.h"
#include "core/video.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// `Video#player_info` answers a Ruby Hash, and the generator has no `std::map`
// codec, so both the body and its registration are hand written here.  The C++
// accessor deliberately carries no `URGE_BINDING()` marker: the IR cannot
// describe a Hash, and a declaration it has to skip would only show up as an
// `unsupported` entry.
RB_FUNC(Video_PlayerInfo) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    VALUE hash = rb_hash_new();
    for (const auto& entry : self_obj->PlayerInfo()) {
      VALUE key = rb_enc_str_new(entry.first.data(),
                                 static_cast<long>(entry.first.size()),
                                 rb_utf8_encoding());
      VALUE value = rb_enc_str_new(entry.second.data(),
                                   static_cast<long>(entry.second.size()),
                                   rb_utf8_encoding());
      rb_hash_aset(hash, key, value);
    }
    return hash;
  }
  EXC_END;
  return Qnil;
}

void DefineVideoPlayerInfo(VALUE klass) {
  DefineMethod(klass, "player_info", Video_PlayerInfo);
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Video  (core/video.h:42-75)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Video);

RB_FUNC(Video_initialize) {
  urge::RefPtr<urge::Video> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string filename;
    ParseArgs(argc, argv, "s", &filename);

    obj = urge::MakeRefCounted<urge::Video>(filename);
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Video_Play) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Play();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_Pause) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Pause();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_Stop) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Stop();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_End) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->End() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_IsPlaying) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->IsPlaying() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_Seek) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    double pos;
    ParseArgs(argc, argv, "f", &pos);

    self_obj->Seek(static_cast<float>(pos));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_Tell) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(self_obj->Tell());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_Duration) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(self_obj->Duration());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_GetAudioStream) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = self_obj->GetAudioStream();
    return WrapObject(result.get(), kAudioStreamDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_Update) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Video_Render) {
  auto* self_obj = GetSelfData<urge::Video>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE target_val;
    ParseArgs(argc, argv, "o", &target_val);

    self_obj->Render(GetObject<urge::Bitmap>(target_val, kBitmapDataType));
  }
  EXC_END;
  return Qnil;
}

void InitVideoBindingAppend(VALUE klass);

void InitVideoBinding() {
  auto klass = rb_define_class("Video", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kVideoDataType>);

  DefineMethod(klass, "initialize", Video_initialize);
  DefineMethod(klass, "play", Video_Play);
  DefineMethod(klass, "pause", Video_Pause);
  DefineMethod(klass, "stop", Video_Stop);
  DefineMethod(klass, "end?", Video_End);
  DefineMethod(klass, "playing?", Video_IsPlaying);
  DefineMethod(klass, "seek", Video_Seek);
  DefineMethod(klass, "tell", Video_Tell);
  DefineMethod(klass, "duration", Video_Duration);
  DefineMethod(klass, "audio_stream", Video_GetAudioStream);
  DefineMethod(klass, "update", Video_Update);
  DefineMethod(klass, "render", Video_Render);
  DefineVideoPlayerInfo(klass);
  InitVideoBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitVideoBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitVideoBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
