// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_audio_stream.h"

#include "core/audio_stream.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// AudioStream  (core/audio_stream.h:38-71)
// -------------------------------------------------------------------------

RB_DEF_TYPE(AudioStream);

RB_FUNC(AudioStream_initialize) {
  urge::RefPtr<urge::AudioStream> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string filename;
    ParseArgs(argc, argv, "s", &filename);

    obj = urge::MakeRefCounted<urge::AudioStream>(filename);
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(AudioStream_Start) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Start();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_Stop) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Stop();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_Seek) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    double pos;
    ParseArgs(argc, argv, "f", &pos);

    self_obj->Seek(static_cast<float>(pos));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_Cursor) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(self_obj->Cursor());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_Length) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(self_obj->Length());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_IsPlaying) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->IsPlaying() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_IsEnd) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->IsEnd() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_SetStartTime) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    double pos;
    ParseArgs(argc, argv, "f", &pos);

    self_obj->SetStartTime(static_cast<float>(pos));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(AudioStream_SetStopTime) {
  auto* self_obj = GetSelfData<urge::AudioStream>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    double pos;
    ParseArgs(argc, argv, "f", &pos);

    self_obj->SetStopTime(static_cast<float>(pos));
  }
  EXC_END;
  return Qnil;
}

// Attribute: volume (float)
BINDING_ATTR_FLOAT(AudioStream, urge::AudioStream, Volume);

// Attribute: pan (float)
BINDING_ATTR_FLOAT(AudioStream, urge::AudioStream, Pan);

// Attribute: pitch (float)
BINDING_ATTR_FLOAT(AudioStream, urge::AudioStream, Pitch);

// Attribute: loop (bool)
BINDING_ATTR_BOOL(AudioStream, urge::AudioStream, Loop);

void InitAudioStreamBindingAppend(VALUE klass);

void InitAudioStreamBinding() {
  auto klass = rb_define_class("AudioStream", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kAudioStreamDataType>);

  DefineMethod(klass, "initialize", AudioStream_initialize);
  DefineMethod(klass, "start", AudioStream_Start);
  DefineMethod(klass, "stop", AudioStream_Stop);
  DefineMethod(klass, "seek", AudioStream_Seek);
  DefineMethod(klass, "cursor", AudioStream_Cursor);
  DefineMethod(klass, "length", AudioStream_Length);
  DefineMethod(klass, "playing?", AudioStream_IsPlaying);
  DefineMethod(klass, "end?", AudioStream_IsEnd);
  DefineMethod(klass, "set_start_time", AudioStream_SetStartTime);
  DefineMethod(klass, "set_stop_time", AudioStream_SetStopTime);
  DefineMethod(klass, "volume", AudioStream_Volume);
  DefineMethod(klass, "volume=", AudioStream_VolumeEqual);
  DefineMethod(klass, "pan", AudioStream_Pan);
  DefineMethod(klass, "pan=", AudioStream_PanEqual);
  DefineMethod(klass, "pitch", AudioStream_Pitch);
  DefineMethod(klass, "pitch=", AudioStream_PitchEqual);
  DefineMethod(klass, "loop", AudioStream_Loop);
  DefineMethod(klass, "loop=", AudioStream_LoopEqual);
  InitAudioStreamBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitAudioStreamBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitAudioStreamBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
