// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_window_xp.h"

#include "binding_bitmap.h"
#include "binding_rect.h"
#include "binding_viewport.h"

#include "core/bitmap.h"
#include "core/utility.h"
#include "core/viewport.h"
#include "core/window_xp.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// WindowXP  (core/window_xp.h:104-128)
// -------------------------------------------------------------------------

RB_DEF_TYPE(WindowXP);

RB_FUNC(WindowXP_initialize) {
  urge::RefPtr<urge::WindowXP> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::WindowXP>();
    } else if (argc == 1) {
      // initialize(viewport)
      VALUE viewport_val;
      ParseArgs(argc, argv, "o", &viewport_val);
      obj = urge::MakeRefCounted<urge::WindowXP>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(WindowXP_Update) {
  auto* self_obj = GetSelfData<urge::WindowXP>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Update();
  }
  EXC_END;
  return Qnil;
}

// Attribute: visible (bool)
BINDING_ATTR_BOOL(WindowXP, urge::WindowXP, Visible);

// Attribute: viewport (RefPtr<Viewport>)
BINDING_ATTR_OBJECT_REF(WindowXP,
                        urge::WindowXP,
                        Viewport,
                        urge::Viewport,
                        kViewportDataType);

// Attribute: windowskin (RefPtr<Bitmap>)
BINDING_ATTR_OBJECT_REF(WindowXP,
                        urge::WindowXP,
                        Windowskin,
                        urge::Bitmap,
                        kBitmapDataType);

// Attribute: contents (RefPtr<Bitmap>)
BINDING_ATTR_OBJECT_REF(WindowXP,
                        urge::WindowXP,
                        Contents,
                        urge::Bitmap,
                        kBitmapDataType);

// Attribute: stretch (bool)
BINDING_ATTR_BOOL(WindowXP, urge::WindowXP, Stretch);

// Attribute: cursor_rect (RefPtr<Rect>)
BINDING_ATTR_OBJECT(WindowXP,
                    urge::WindowXP,
                    CursorRect,
                    urge::Rect,
                    kRectDataType);

// Attribute: active (bool)
BINDING_ATTR_BOOL(WindowXP, urge::WindowXP, Active);

// Attribute: pause (bool)
BINDING_ATTR_BOOL(WindowXP, urge::WindowXP, Pause);

// Attribute: x (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, X);

// Attribute: y (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, Y);

// Attribute: width (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, Width);

// Attribute: height (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, Height);

// Attribute: ox (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, OX);

// Attribute: oy (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, OY);

// Attribute: opacity (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, Opacity);

// Attribute: back_opacity (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, BackOpacity);

// Attribute: contents_opacity (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, ContentsOpacity);

// Attribute: z (int32_t)
BINDING_ATTR_INT(WindowXP, urge::WindowXP, Z);

void InitWindowXPBindingAppend(VALUE klass);

void InitWindowXPBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("WindowXP", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kWindowXPDataType>);

  DefineMethod(klass, "initialize", WindowXP_initialize);
  DefineMethod(klass, "update", WindowXP_Update);
  DefineMethod(klass, "visible", WindowXP_Visible);
  DefineMethod(klass, "visible=", WindowXP_VisibleEqual);
  DefineMethod(klass, "viewport", WindowXP_Viewport);
  DefineMethod(klass, "viewport=", WindowXP_ViewportEqual);
  DefineMethod(klass, "windowskin", WindowXP_Windowskin);
  DefineMethod(klass, "windowskin=", WindowXP_WindowskinEqual);
  DefineMethod(klass, "contents", WindowXP_Contents);
  DefineMethod(klass, "contents=", WindowXP_ContentsEqual);
  DefineMethod(klass, "stretch", WindowXP_Stretch);
  DefineMethod(klass, "stretch=", WindowXP_StretchEqual);
  DefineMethod(klass, "cursor_rect", WindowXP_CursorRect);
  DefineMethod(klass, "cursor_rect=", WindowXP_CursorRectEqual);
  DefineMethod(klass, "active", WindowXP_Active);
  DefineMethod(klass, "active=", WindowXP_ActiveEqual);
  DefineMethod(klass, "pause", WindowXP_Pause);
  DefineMethod(klass, "pause=", WindowXP_PauseEqual);
  DefineMethod(klass, "x", WindowXP_X);
  DefineMethod(klass, "x=", WindowXP_XEqual);
  DefineMethod(klass, "y", WindowXP_Y);
  DefineMethod(klass, "y=", WindowXP_YEqual);
  DefineMethod(klass, "width", WindowXP_Width);
  DefineMethod(klass, "width=", WindowXP_WidthEqual);
  DefineMethod(klass, "height", WindowXP_Height);
  DefineMethod(klass, "height=", WindowXP_HeightEqual);
  DefineMethod(klass, "ox", WindowXP_OX);
  DefineMethod(klass, "ox=", WindowXP_OXEqual);
  DefineMethod(klass, "oy", WindowXP_OY);
  DefineMethod(klass, "oy=", WindowXP_OYEqual);
  DefineMethod(klass, "opacity", WindowXP_Opacity);
  DefineMethod(klass, "opacity=", WindowXP_OpacityEqual);
  DefineMethod(klass, "back_opacity", WindowXP_BackOpacity);
  DefineMethod(klass, "back_opacity=", WindowXP_BackOpacityEqual);
  DefineMethod(klass, "contents_opacity", WindowXP_ContentsOpacity);
  DefineMethod(klass, "contents_opacity=", WindowXP_ContentsOpacityEqual);
  DefineMethod(klass, "z", WindowXP_Z);
  DefineMethod(klass, "z=", WindowXP_ZEqual);
  InitWindowXPBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitWindowXPBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitWindowXPBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
