// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_command_encoder.h"

#include "binding_gpu_buffer.h"
#include "binding_gpu_command_buffer.h"
#include "binding_gpu_compute_pass_descriptor.h"
#include "binding_gpu_compute_pass_encoder.h"
#include "binding_gpu_object.h"
#include "binding_gpu_render_pass_descriptor.h"
#include "binding_gpu_render_pass_encoder.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUCommandEncoder  (core/gpu.h:870-886)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUCommandEncoder, GPUObject);

RB_FUNC(GPUCommandEncoder_BeginRenderPass) {
  auto* self_obj = GetSelfData<urge::GPUCommandEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE descriptor_val;
    ParseArgs(argc, argv, "o", &descriptor_val);

    auto result = self_obj->BeginRenderPass(GetObject<urge::GPURenderPassDescriptor>(descriptor_val, kGPURenderPassDescriptorDataType));
    return WrapObject(result.get(), kGPURenderPassEncoderDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUCommandEncoder_BeginComputePass) {
  auto* self_obj = GetSelfData<urge::GPUCommandEncoder>(self);

  EXC_BEGIN {
    if (argc == 0) {
      // begin_compute_pass()
      auto result = self_obj->BeginComputePass();
      return WrapObject(result.get(), kGPUComputePassEncoderDataType);
    } else if (argc == 1) {
      // begin_compute_pass(descriptor)
      VALUE descriptor_val;
      ParseArgs(argc, argv, "o", &descriptor_val);
      auto result = self_obj->BeginComputePass(GetObject<urge::GPUComputePassDescriptor>(descriptor_val, kGPUComputePassDescriptorDataType));
      return WrapObject(result.get(), kGPUComputePassEncoderDataType);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUCommandEncoder_CopyBufferToBuffer) {
  auto* self_obj = GetSelfData<urge::GPUCommandEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 5);
    VALUE source_val, destination_val;
    uint64_t source_offset, destination_offset, size;
    ParseArgs(argc, argv, "opopp", &source_val, &source_offset,
        &destination_val, &destination_offset, &size);

    self_obj->CopyBufferToBuffer(
        GetObject<urge::GPUBuffer>(source_val, kGPUBufferDataType),
        source_offset,
        GetObject<urge::GPUBuffer>(destination_val, kGPUBufferDataType),
        destination_offset, size);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUCommandEncoder_ClearBuffer) {
  auto* self_obj = GetSelfData<urge::GPUCommandEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    VALUE buffer_val;
    uint64_t offset, size;
    ParseArgs(argc, argv, "opp", &buffer_val, &offset, &size);

    self_obj->ClearBuffer(
        GetObject<urge::GPUBuffer>(buffer_val, kGPUBufferDataType), offset,
        size);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUCommandEncoder_Finish) {
  auto* self_obj = GetSelfData<urge::GPUCommandEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = self_obj->Finish();
    return WrapObject(result.get(), kGPUCommandBufferDataType);
  }
  EXC_END;
  return Qnil;
}

void InitGPUCommandEncoderBindingAppend(VALUE klass);

void InitGPUCommandEncoderBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUCommandEncoder", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUCommandEncoderDataType>);

  DefineMethod(klass, "begin_render_pass", GPUCommandEncoder_BeginRenderPass);
  DefineMethod(klass, "begin_compute_pass", GPUCommandEncoder_BeginComputePass);
  DefineMethod(klass, "copy_buffer_to_buffer", GPUCommandEncoder_CopyBufferToBuffer);
  DefineMethod(klass, "clear_buffer", GPUCommandEncoder_ClearBuffer);
  DefineMethod(klass, "finish", GPUCommandEncoder_Finish);
  InitGPUCommandEncoderBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUCommandEncoderBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUCommandEncoderBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
