// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_pipeline_layout_descriptor.h"

#include "binding_gpu_bind_group_layout.h"
#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUPipelineLayoutDescriptor  (core/gpu.h:391-408)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUPipelineLayoutDescriptor, GPUObject);

RB_FUNC(GPUPipelineLayoutDescriptor_initialize) {
  urge::RefPtr<urge::GPUPipelineLayoutDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUPipelineLayoutDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUPipelineLayoutDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUPipelineLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUPipelineLayoutDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUPipelineLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUPipelineLayoutDescriptor_AddBindGroupLayout) {
  auto* self_obj = GetSelfData<urge::GPUPipelineLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE layout_val;
    ParseArgs(argc, argv, "o", &layout_val);

    self_obj->AddBindGroupLayout(
        GetObject<urge::GPUBindGroupLayout>(layout_val, kGPUBindGroupLayoutDataType));
  }
  EXC_END;
  return Qnil;
}

// Attribute: immediate_size (uint32_t)
BINDING_ATTR_INT(GPUPipelineLayoutDescriptor,
                 urge::GPUPipelineLayoutDescriptor,
                 ImmediateSize);

void InitGPUPipelineLayoutDescriptorBindingAppend(VALUE klass);

void InitGPUPipelineLayoutDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUPipelineLayoutDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUPipelineLayoutDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUPipelineLayoutDescriptor_initialize);
  DefineMethod(klass, "label", GPUPipelineLayoutDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUPipelineLayoutDescriptor_SetLabel);
  DefineMethod(klass, "add_bind_group_layout", GPUPipelineLayoutDescriptor_AddBindGroupLayout);
  DefineMethod(klass, "immediate_size", GPUPipelineLayoutDescriptor_ImmediateSize);
  DefineMethod(klass, "immediate_size=", GPUPipelineLayoutDescriptor_ImmediateSizeEqual);
  InitGPUPipelineLayoutDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUPipelineLayoutDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUPipelineLayoutDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
