// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_graphics.h"

#include "binding_bitmap.h"

#include "core/bitmap.h"
#include "core/graphics.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Graphics  (core/graphics.h:58-80)
// -------------------------------------------------------------------------

RB_FUNC(Graphics_Update) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Graphics::Get().Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Wait) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int duration;
    ParseArgs(argc, argv, "i", &duration);

    urge::Graphics::Get().Wait(duration);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Fadein) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int duration;
    ParseArgs(argc, argv, "i", &duration);

    urge::Graphics::Get().Fadein(duration);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Fadeout) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int duration;
    ParseArgs(argc, argv, "i", &duration);

    urge::Graphics::Get().Fadeout(duration);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Freeze) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Graphics::Get().Freeze();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Transition) {
  EXC_BEGIN {
    if (argc == 0) {
      // transition()
      urge::Graphics::Get().Transition();
    } else if (argc == 1) {
      // transition(duration)
      int duration;
      ParseArgs(argc, argv, "i", &duration);
      urge::Graphics::Get().Transition(duration);
    } else if (argc == 2) {
      // transition(duration, filename)
      int duration;
      std::string filename;
      ParseArgs(argc, argv, "is", &duration, &filename);
      urge::Graphics::Get().Transition(duration, filename);
    } else if (argc == 3) {
      // transition(duration, filename, vague)
      int duration, vague;
      std::string filename;
      ParseArgs(argc, argv, "isi", &duration, &filename, &vague);
      urge::Graphics::Get().Transition(duration, filename, vague);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_TransitionBitmap) {
  EXC_BEGIN {
    if (argc == 0) {
      // transition_bitmap()
      urge::Graphics::Get().TransitionBitmap();
    } else if (argc == 1) {
      // transition_bitmap(duration)
      int duration;
      ParseArgs(argc, argv, "i", &duration);
      urge::Graphics::Get().TransitionBitmap(duration);
    } else if (argc == 2) {
      // transition_bitmap(duration, bitmap)
      int duration;
      VALUE bitmap_val;
      ParseArgs(argc, argv, "io", &duration, &bitmap_val);
      urge::Graphics::Get().TransitionBitmap(duration,
          GetObject<urge::Bitmap>(bitmap_val, kBitmapDataType));
    } else if (argc == 3) {
      // transition_bitmap(duration, bitmap, vague)
      int duration, vague;
      VALUE bitmap_val;
      ParseArgs(argc, argv, "ioi", &duration, &bitmap_val, &vague);
      urge::Graphics::Get().TransitionBitmap(duration,
          GetObject<urge::Bitmap>(bitmap_val, kBitmapDataType), vague);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_SnapToBitmap) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = urge::Graphics::Get().SnapToBitmap();
    return WrapObject(result.get(), kBitmapDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_FrameReset) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Graphics::Get().FrameReset();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Width) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Graphics::Get().Width());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Height) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Graphics::Get().Height());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_ResizeScreen) {
  EXC_BEGIN {
    CheckArgc(argc, 2);
    int width, height;
    ParseArgs(argc, argv, "ii", &width, &height);

    urge::Graphics::Get().ResizeScreen(width, height);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_PlayMovie) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string filename;
    ParseArgs(argc, argv, "s", &filename);

    urge::Graphics::Get().PlayMovie(filename);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_FrameRate) {
  EXC_BEGIN {
    return LONG2NUM((*urge::Graphics::Get().Attr_FrameRate()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_FrameRateEqual) {
  int value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "i", &value);
    urge::Graphics::Get().Attr_FrameRate(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_FrameCount) {
  EXC_BEGIN {
    return LONG2NUM((*urge::Graphics::Get().Attr_FrameCount()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_FrameCountEqual) {
  int value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "i", &value);
    urge::Graphics::Get().Attr_FrameCount(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_Brightness) {
  EXC_BEGIN {
    return LONG2NUM((*urge::Graphics::Get().Attr_Brightness()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Graphics_BrightnessEqual) {
  int value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "i", &value);
    urge::Graphics::Get().Attr_Brightness(value);
  }
  EXC_END;
  return Qnil;
}

void InitGraphicsBindingAppend(VALUE mod);

void InitGraphicsBinding() {
  auto mod = rb_define_module("Graphics");

  DefineModuleFunction(mod, "update", Graphics_Update);
  DefineModuleFunction(mod, "wait", Graphics_Wait);
  DefineModuleFunction(mod, "fadein", Graphics_Fadein);
  DefineModuleFunction(mod, "fadeout", Graphics_Fadeout);
  DefineModuleFunction(mod, "freeze", Graphics_Freeze);
  DefineModuleFunction(mod, "transition", Graphics_Transition);
  DefineModuleFunction(mod, "transition_bitmap", Graphics_TransitionBitmap);
  DefineModuleFunction(mod, "snap_to_bitmap", Graphics_SnapToBitmap);
  DefineModuleFunction(mod, "frame_reset", Graphics_FrameReset);
  DefineModuleFunction(mod, "width", Graphics_Width);
  DefineModuleFunction(mod, "height", Graphics_Height);
  DefineModuleFunction(mod, "resize_screen", Graphics_ResizeScreen);
  DefineModuleFunction(mod, "play_movie", Graphics_PlayMovie);
  DefineModuleFunction(mod, "frame_rate", Graphics_FrameRate);
  DefineModuleFunction(mod, "frame_rate=", Graphics_FrameRateEqual);
  DefineModuleFunction(mod, "frame_count", Graphics_FrameCount);
  DefineModuleFunction(mod, "frame_count=", Graphics_FrameCountEqual);
  DefineModuleFunction(mod, "brightness", Graphics_Brightness);
  DefineModuleFunction(mod, "brightness=", Graphics_BrightnessEqual);
  InitGraphicsBindingAppend(mod);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGraphicsBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitGraphicsBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
