// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_viewport.h"

#include "binding_color.h"
#include "binding_effect.h"
#include "binding_node.h"
#include "binding_rect.h"
#include "binding_tone.h"

#include "core/effect.h"
#include "core/utility.h"
#include "core/viewport.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Viewport  (core/viewport.h:33-48)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(Viewport, Node);

RB_FUNC(Viewport_initialize) {
  urge::RefPtr<urge::Viewport> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Viewport>();
    } else if (argc == 1) {
      // initialize(rect)
      VALUE rect_val;
      ParseArgs(argc, argv, "o", &rect_val);
      obj = urge::MakeRefCounted<urge::Viewport>(
          GetObject<urge::Rect>(rect_val, kRectDataType));
    } else if (argc == 4) {
      // initialize(x, y, width, height)
      int x, y, width, height;
      ParseArgs(argc, argv, "iiii", &x, &y, &width, &height);
      obj = urge::MakeRefCounted<urge::Viewport>(x, y, width, height);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Viewport_Flash) {
  auto* self_obj = GetSelfData<urge::Viewport>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    VALUE color_val;
    int duration;
    ParseArgs(argc, argv, "oi", &color_val, &duration);

    self_obj->Flash(GetObject<urge::Color>(color_val, kColorDataType),
        duration);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Viewport_Update) {
  auto* self_obj = GetSelfData<urge::Viewport>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Update();
  }
  EXC_END;
  return Qnil;
}

// Attribute: rect (RefPtr<Rect>)
BINDING_ATTR_OBJECT(Viewport, urge::Viewport, Rect, urge::Rect, kRectDataType);

// Attribute: ox (int32_t)
BINDING_ATTR_INT(Viewport, urge::Viewport, OX);

// Attribute: oy (int32_t)
BINDING_ATTR_INT(Viewport, urge::Viewport, OY);

// Attribute: color (RefPtr<Color>)
BINDING_ATTR_OBJECT(Viewport,
                    urge::Viewport,
                    Color,
                    urge::Color,
                    kColorDataType);

// Attribute: tone (RefPtr<Tone>)
BINDING_ATTR_OBJECT(Viewport, urge::Viewport, Tone, urge::Tone, kToneDataType);

// Attribute: effect (RefPtr<Effect>)
BINDING_ATTR_OBJECT_REF(Viewport,
                        urge::Viewport,
                        Effect,
                        urge::Effect,
                        kEffectDataType);

void InitViewportBindingAppend(VALUE klass);

void InitViewportBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("Viewport", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kViewportDataType>);

  DefineMethod(klass, "initialize", Viewport_initialize);
  DefineMethod(klass, "flash", Viewport_Flash);
  DefineMethod(klass, "update", Viewport_Update);
  DefineMethod(klass, "rect", Viewport_Rect);
  DefineMethod(klass, "rect=", Viewport_RectEqual);
  DefineMethod(klass, "ox", Viewport_OX);
  DefineMethod(klass, "ox=", Viewport_OXEqual);
  DefineMethod(klass, "oy", Viewport_OY);
  DefineMethod(klass, "oy=", Viewport_OYEqual);
  DefineMethod(klass, "color", Viewport_Color);
  DefineMethod(klass, "color=", Viewport_ColorEqual);
  DefineMethod(klass, "tone", Viewport_Tone);
  DefineMethod(klass, "tone=", Viewport_ToneEqual);
  DefineMethod(klass, "effect", Viewport_Effect);
  DefineMethod(klass, "effect=", Viewport_EffectEqual);
  InitViewportBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitViewportBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitViewportBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
