// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_query_set_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUQuerySetDescriptor  (core/gpu.h:652-669)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUQuerySetDescriptor, GPUObject);

RB_FUNC(GPUQuerySetDescriptor_initialize) {
  urge::RefPtr<urge::GPUQuerySetDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUQuerySetDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUQuerySetDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUQuerySetDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUQuerySetDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUQuerySetDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: type (uint32_t)
BINDING_ATTR_INT(GPUQuerySetDescriptor, urge::GPUQuerySetDescriptor, Type);

// Attribute: count (uint32_t)
BINDING_ATTR_INT(GPUQuerySetDescriptor, urge::GPUQuerySetDescriptor, Count);

void InitGPUQuerySetDescriptorBindingAppend(VALUE klass);

void InitGPUQuerySetDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUQuerySetDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUQuerySetDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUQuerySetDescriptor_initialize);
  DefineMethod(klass, "label", GPUQuerySetDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUQuerySetDescriptor_SetLabel);
  DefineMethod(klass, "type", GPUQuerySetDescriptor_Type);
  DefineMethod(klass, "type=", GPUQuerySetDescriptor_TypeEqual);
  DefineMethod(klass, "count", GPUQuerySetDescriptor_Count);
  DefineMethod(klass, "count=", GPUQuerySetDescriptor_CountEqual);
  InitGPUQuerySetDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUQuerySetDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUQuerySetDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
