// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_bitmap.h"

#include "binding_color.h"
#include "binding_disposable.h"
#include "binding_font.h"
#include "binding_palette.h"
#include "binding_rect.h"

#include "core/bitmap.h"
#include "core/font.h"
#include "core/palette.h"
#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Bitmap  (core/bitmap.h:36-93)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(Bitmap, Disposable);

RB_FUNC(Bitmap_initialize) {
  urge::RefPtr<urge::Bitmap> obj = nullptr;
  EXC_BEGIN {
    if (argc == 1) {
      // initialize(filename)
      std::string filename;
      ParseArgs(argc, argv, "s", &filename);
      obj = urge::MakeRefCounted<urge::Bitmap>(filename);
    } else if (argc == 2) {
      // initialize(width, height)
      int width, height;
      ParseArgs(argc, argv, "ii", &width, &height);
      obj = urge::MakeRefCounted<urge::Bitmap>(width, height);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Bitmap_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Bitmap> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Bitmap>(other, kBitmapDataType);
    obj = urge::MakeRefCounted<urge::Bitmap>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Bitmap_Width) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Width());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_Height) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Height());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_GetRect) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = self_obj->GetRect();
    return WrapObject(result.get(), kRectDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_Blt) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    if (argc == 4) {
      // blt(x, y, src_bitmap, src_rect)
      int x, y;
      VALUE src_bitmap_val, src_rect_val;
      ParseArgs(argc, argv, "iioo", &x, &y, &src_bitmap_val, &src_rect_val);
      self_obj->Blt(x, y,
          GetObject<urge::Bitmap>(src_bitmap_val, kBitmapDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType));
    } else if (argc == 5) {
      // blt(x, y, src_bitmap, src_rect, opacity)
      int x, y, opacity;
      VALUE src_bitmap_val, src_rect_val;
      ParseArgs(argc, argv, "iiooi", &x, &y, &src_bitmap_val, &src_rect_val,
          &opacity);
      self_obj->Blt(x, y,
          GetObject<urge::Bitmap>(src_bitmap_val, kBitmapDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType), opacity);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_StretchBlt) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    if (argc == 3) {
      // stretch_blt(dst_rect, src_bitmap, src_rect)
      VALUE dst_rect_val, src_bitmap_val, src_rect_val;
      ParseArgs(argc, argv, "ooo", &dst_rect_val, &src_bitmap_val,
          &src_rect_val);
      self_obj->StretchBlt(GetObject<urge::Rect>(dst_rect_val, kRectDataType),
          GetObject<urge::Bitmap>(src_bitmap_val, kBitmapDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType));
    } else if (argc == 4) {
      // stretch_blt(dst_rect, src_bitmap, src_rect, opacity)
      VALUE dst_rect_val, src_bitmap_val, src_rect_val;
      int opacity;
      ParseArgs(argc, argv, "oooi", &dst_rect_val, &src_bitmap_val,
          &src_rect_val, &opacity);
      self_obj->StretchBlt(GetObject<urge::Rect>(dst_rect_val, kRectDataType),
          GetObject<urge::Bitmap>(src_bitmap_val, kBitmapDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType), opacity);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_FillRect) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    if (argc == 2) {
      // fill_rect(rect, color)
      VALUE rect_val, color_val;
      ParseArgs(argc, argv, "oo", &rect_val, &color_val);
      self_obj->FillRect(GetObject<urge::Rect>(rect_val, kRectDataType),
          GetObject<urge::Color>(color_val, kColorDataType));
    } else if (argc == 5) {
      // fill_rect(x, y, width, height, color)
      int x, y, width, height;
      VALUE color_val;
      ParseArgs(argc, argv, "iiiio", &x, &y, &width, &height, &color_val);
      self_obj->FillRect(x, y, width, height,
          GetObject<urge::Color>(color_val, kColorDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_GradientFillRect) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    if (argc == 3) {
      // gradient_fill_rect(rect, color1, color2)
      VALUE rect_val, color1_val, color2_val;
      ParseArgs(argc, argv, "ooo", &rect_val, &color1_val, &color2_val);
      self_obj->GradientFillRect(GetObject<urge::Rect>(rect_val, kRectDataType),
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType));
    } else if (argc == 4) {
      // gradient_fill_rect(rect, color1, color2, vertical)
      VALUE rect_val, color1_val, color2_val;
      bool vertical;
      ParseArgs(argc, argv, "ooob", &rect_val, &color1_val, &color2_val,
          &vertical);
      self_obj->GradientFillRect(GetObject<urge::Rect>(rect_val, kRectDataType),
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType), vertical);
    } else if (argc == 6) {
      // gradient_fill_rect(x, y, width, height, color1, color2)
      int x, y, width, height;
      VALUE color1_val, color2_val;
      ParseArgs(argc, argv, "iiiioo", &x, &y, &width, &height, &color1_val,
          &color2_val);
      self_obj->GradientFillRect(x, y, width, height,
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType));
    } else if (argc == 7) {
      // gradient_fill_rect(x, y, width, height, color1, color2, vertical)
      int x, y, width, height;
      VALUE color1_val, color2_val;
      bool vertical;
      ParseArgs(argc, argv, "iiiioob", &x, &y, &width, &height, &color1_val,
          &color2_val, &vertical);
      self_obj->GradientFillRect(x, y, width, height,
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType), vertical);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_Clear) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Clear();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_ClearRect) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // clear_rect(rect)
      VALUE rect_val;
      ParseArgs(argc, argv, "o", &rect_val);
      self_obj->ClearRect(GetObject<urge::Rect>(rect_val, kRectDataType));
    } else if (argc == 4) {
      // clear_rect(x, y, width, height)
      int x, y, width, height;
      ParseArgs(argc, argv, "iiii", &x, &y, &width, &height);
      self_obj->ClearRect(x, y, width, height);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_GetPixel) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    int x, y;
    ParseArgs(argc, argv, "ii", &x, &y);

    auto result = self_obj->GetPixel(x, y);
    return WrapObject(result.get(), kColorDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_SetPixel) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    int x, y;
    VALUE color_val;
    ParseArgs(argc, argv, "iio", &x, &y, &color_val);

    self_obj->SetPixel(x, y, GetObject<urge::Color>(color_val, kColorDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_HueChange) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    int hue;
    ParseArgs(argc, argv, "i", &hue);

    self_obj->HueChange(hue);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_Blur) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Blur();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_RadialBlur) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    int angle, division;
    ParseArgs(argc, argv, "ii", &angle, &division);

    self_obj->RadialBlur(angle, division);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_DrawText) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    if (argc == 2) {
      // draw_text(rect, str)
      VALUE rect_val;
      std::string str;
      ParseArgs(argc, argv, "os", &rect_val, &str);
      self_obj->DrawText(GetObject<urge::Rect>(rect_val, kRectDataType), str);
    } else if (argc == 3) {
      // draw_text(rect, str, align)
      VALUE rect_val;
      std::string str;
      int align;
      ParseArgs(argc, argv, "osi", &rect_val, &str, &align);
      self_obj->DrawText(GetObject<urge::Rect>(rect_val, kRectDataType), str,
          align);
    } else if (argc == 5) {
      // draw_text(x, y, width, height, str)
      int x, y, width, height;
      std::string str;
      ParseArgs(argc, argv, "iiiis", &x, &y, &width, &height, &str);
      self_obj->DrawText(x, y, width, height, str);
    } else if (argc == 6) {
      // draw_text(x, y, width, height, str, align)
      int x, y, width, height, align;
      std::string str;
      ParseArgs(argc, argv, "iiiisi", &x, &y, &width, &height, &str, &align);
      self_obj->DrawText(x, y, width, height, str, align);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_TextSize) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string str;
    ParseArgs(argc, argv, "s", &str);

    auto result = self_obj->TextSize(str);
    return WrapObject(result.get(), kRectDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_ToPalette) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    auto result = self_obj->ToPalette();
    return WrapObject(result.get(), kPaletteDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Bitmap_UpdateWithPalette) {
  auto* self_obj = GetSelfData<urge::Bitmap>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE palette_val;
    ParseArgs(argc, argv, "o", &palette_val);

    self_obj->UpdateWithPalette(
        GetObject<urge::Palette>(palette_val, kPaletteDataType));
  }
  EXC_END;
  return Qnil;
}

// Attribute: font (RefPtr<Font>)
BINDING_ATTR_OBJECT_REF(Bitmap, urge::Bitmap, Font, urge::Font, kFontDataType);

void InitBitmapBindingAppend(VALUE klass);

void InitBitmapBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Disposable"));
  auto klass = rb_define_class("Bitmap", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kBitmapDataType>);

  DefineMethod(klass, "initialize", Bitmap_initialize);
  DefineMethod(klass, "initialize_copy", Bitmap_initialize_copy);
  DefineMethod(klass, "width", Bitmap_Width);
  DefineMethod(klass, "height", Bitmap_Height);
  DefineMethod(klass, "rect", Bitmap_GetRect);
  DefineMethod(klass, "blt", Bitmap_Blt);
  DefineMethod(klass, "stretch_blt", Bitmap_StretchBlt);
  DefineMethod(klass, "fill_rect", Bitmap_FillRect);
  DefineMethod(klass, "gradient_fill_rect", Bitmap_GradientFillRect);
  DefineMethod(klass, "clear", Bitmap_Clear);
  DefineMethod(klass, "clear_rect", Bitmap_ClearRect);
  DefineMethod(klass, "get_pixel", Bitmap_GetPixel);
  DefineMethod(klass, "set_pixel", Bitmap_SetPixel);
  DefineMethod(klass, "hue_change", Bitmap_HueChange);
  DefineMethod(klass, "blur", Bitmap_Blur);
  DefineMethod(klass, "radial_blur", Bitmap_RadialBlur);
  DefineMethod(klass, "draw_text", Bitmap_DrawText);
  DefineMethod(klass, "text_size", Bitmap_TextSize);
  DefineMethod(klass, "to_palette", Bitmap_ToPalette);
  DefineMethod(klass, "update_with_palette", Bitmap_UpdateWithPalette);
  DefineMethod(klass, "font", Bitmap_Font);
  DefineMethod(klass, "font=", Bitmap_FontEqual);
  InitBitmapBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitBitmapBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitBitmapBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
