// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_audio.h"

#include "core/audio.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Audio  (core/audio.h:39-64)
// -------------------------------------------------------------------------

RB_FUNC(Audio_SetupMIDI) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Audio::Get().SetupMIDI();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGMPlay) {
  EXC_BEGIN {
    if (argc == 1) {
      // bgm_play(filename)
      std::string filename;
      ParseArgs(argc, argv, "s", &filename);
      urge::Audio::Get().BGMPlay(filename);
    } else if (argc == 2) {
      // bgm_play(filename, volume)
      std::string filename;
      int volume;
      ParseArgs(argc, argv, "si", &filename, &volume);
      urge::Audio::Get().BGMPlay(filename, volume);
    } else if (argc == 3) {
      // bgm_play(filename, volume, pitch)
      std::string filename;
      int volume, pitch;
      ParseArgs(argc, argv, "sii", &filename, &volume, &pitch);
      urge::Audio::Get().BGMPlay(filename, volume, pitch);
    } else if (argc == 4) {
      // bgm_play(filename, volume, pitch, pos)
      std::string filename;
      int volume, pitch;
      double pos;
      ParseArgs(argc, argv, "siif", &filename, &volume, &pitch, &pos);
      urge::Audio::Get().BGMPlay(filename, volume, pitch,
          static_cast<float>(pos));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGMStop) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Audio::Get().BGMStop();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGMFade) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int time;
    ParseArgs(argc, argv, "i", &time);

    urge::Audio::Get().BGMFade(time);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGMPos) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(urge::Audio::Get().BGMPos());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGSPlay) {
  EXC_BEGIN {
    if (argc == 1) {
      // bgs_play(filename)
      std::string filename;
      ParseArgs(argc, argv, "s", &filename);
      urge::Audio::Get().BGSPlay(filename);
    } else if (argc == 2) {
      // bgs_play(filename, volume)
      std::string filename;
      int volume;
      ParseArgs(argc, argv, "si", &filename, &volume);
      urge::Audio::Get().BGSPlay(filename, volume);
    } else if (argc == 3) {
      // bgs_play(filename, volume, pitch)
      std::string filename;
      int volume, pitch;
      ParseArgs(argc, argv, "sii", &filename, &volume, &pitch);
      urge::Audio::Get().BGSPlay(filename, volume, pitch);
    } else if (argc == 4) {
      // bgs_play(filename, volume, pitch, pos)
      std::string filename;
      int volume, pitch;
      double pos;
      ParseArgs(argc, argv, "siif", &filename, &volume, &pitch, &pos);
      urge::Audio::Get().BGSPlay(filename, volume, pitch,
          static_cast<float>(pos));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGSStop) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Audio::Get().BGSStop();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGSFade) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int time;
    ParseArgs(argc, argv, "i", &time);

    urge::Audio::Get().BGSFade(time);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_BGSPos) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(urge::Audio::Get().BGSPos());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_MEPlay) {
  EXC_BEGIN {
    if (argc == 1) {
      // me_play(filename)
      std::string filename;
      ParseArgs(argc, argv, "s", &filename);
      urge::Audio::Get().MEPlay(filename);
    } else if (argc == 2) {
      // me_play(filename, volume)
      std::string filename;
      int volume;
      ParseArgs(argc, argv, "si", &filename, &volume);
      urge::Audio::Get().MEPlay(filename, volume);
    } else if (argc == 3) {
      // me_play(filename, volume, pitch)
      std::string filename;
      int volume, pitch;
      ParseArgs(argc, argv, "sii", &filename, &volume, &pitch);
      urge::Audio::Get().MEPlay(filename, volume, pitch);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_MEStop) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Audio::Get().MEStop();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_MEFade) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int time;
    ParseArgs(argc, argv, "i", &time);

    urge::Audio::Get().MEFade(time);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_SEPlay) {
  EXC_BEGIN {
    if (argc == 1) {
      // se_play(filename)
      std::string filename;
      ParseArgs(argc, argv, "s", &filename);
      urge::Audio::Get().SEPlay(filename);
    } else if (argc == 2) {
      // se_play(filename, volume)
      std::string filename;
      int volume;
      ParseArgs(argc, argv, "si", &filename, &volume);
      urge::Audio::Get().SEPlay(filename, volume);
    } else if (argc == 3) {
      // se_play(filename, volume, pitch)
      std::string filename;
      int volume, pitch;
      ParseArgs(argc, argv, "sii", &filename, &volume, &pitch);
      urge::Audio::Get().SEPlay(filename, volume, pitch);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Audio_SEStop) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Audio::Get().SEStop();
  }
  EXC_END;
  return Qnil;
}

void InitAudioBinding() {
  auto mod = rb_define_module("Audio");

  DefineModuleFunction(mod, "setup_midi", Audio_SetupMIDI);
  DefineModuleFunction(mod, "bgm_play", Audio_BGMPlay);
  DefineModuleFunction(mod, "bgm_stop", Audio_BGMStop);
  DefineModuleFunction(mod, "bgm_fade", Audio_BGMFade);
  DefineModuleFunction(mod, "bgm_pos", Audio_BGMPos);
  DefineModuleFunction(mod, "bgs_play", Audio_BGSPlay);
  DefineModuleFunction(mod, "bgs_stop", Audio_BGSStop);
  DefineModuleFunction(mod, "bgs_fade", Audio_BGSFade);
  DefineModuleFunction(mod, "bgs_pos", Audio_BGSPos);
  DefineModuleFunction(mod, "me_play", Audio_MEPlay);
  DefineModuleFunction(mod, "me_stop", Audio_MEStop);
  DefineModuleFunction(mod, "me_fade", Audio_MEFade);
  DefineModuleFunction(mod, "se_play", Audio_SEPlay);
  DefineModuleFunction(mod, "se_stop", Audio_SEStop);
}
// --- GENERATED END ---

}  // namespace binding
