// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_bind_group_descriptor.h"

#include "binding_gpu_bind_group_layout.h"
#include "binding_gpu_buffer.h"
#include "binding_gpu_object.h"
#include "binding_gpu_sampler.h"
#include "binding_gpu_texture_view.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUBindGroupDescriptor  (core/gpu.h:418-439)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUBindGroupDescriptor, GPUObject);

RB_FUNC(GPUBindGroupDescriptor_initialize) {
  urge::RefPtr<urge::GPUBindGroupDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUBindGroupDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUBindGroupDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupDescriptor_AddBuffer) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t binding;
    VALUE buffer_val;
    ParseArgs(argc, argv, "uo", &binding, &buffer_val);

    self_obj->AddBuffer(binding,
        GetObject<urge::GPUBuffer>(buffer_val, kGPUBufferDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupDescriptor_AddTexture) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t binding;
    VALUE view_val;
    ParseArgs(argc, argv, "uo", &binding, &view_val);

    self_obj->AddTexture(binding,
        GetObject<urge::GPUTextureView>(view_val, kGPUTextureViewDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupDescriptor_AddSampler) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t binding;
    VALUE sampler_val;
    ParseArgs(argc, argv, "uo", &binding, &sampler_val);

    self_obj->AddSampler(binding,
        GetObject<urge::GPUSampler>(sampler_val, kGPUSamplerDataType));
  }
  EXC_END;
  return Qnil;
}

// Attribute: layout (RefPtr<GPUBindGroupLayout>)
BINDING_ATTR_OBJECT_REF(GPUBindGroupDescriptor,
                        urge::GPUBindGroupDescriptor,
                        Layout,
                        urge::GPUBindGroupLayout,
                        kGPUBindGroupLayoutDataType);

void InitGPUBindGroupDescriptorBindingAppend(VALUE klass);

void InitGPUBindGroupDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUBindGroupDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUBindGroupDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUBindGroupDescriptor_initialize);
  DefineMethod(klass, "label", GPUBindGroupDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUBindGroupDescriptor_SetLabel);
  DefineMethod(klass, "add_buffer", GPUBindGroupDescriptor_AddBuffer);
  DefineMethod(klass, "add_texture", GPUBindGroupDescriptor_AddTexture);
  DefineMethod(klass, "add_sampler", GPUBindGroupDescriptor_AddSampler);
  DefineMethod(klass, "layout", GPUBindGroupDescriptor_Layout);
  DefineMethod(klass, "layout=", GPUBindGroupDescriptor_LayoutEqual);
  InitGPUBindGroupDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUBindGroupDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUBindGroupDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
