// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_queue.h"

#include "binding_gpu_buffer.h"
#include "binding_gpu_command_buffer.h"
#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUQueue  (core/gpu.h:948-954)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUQueue, GPUObject);

RB_FUNC(GPUQueue_Submit) {
  auto* self_obj = GetSelfData<urge::GPUQueue>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE command_buffer_val;
    ParseArgs(argc, argv, "o", &command_buffer_val);

    self_obj->Submit(
        GetObject<urge::GPUCommandBuffer>(command_buffer_val, kGPUCommandBufferDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUQueue_WriteBuffer) {
  auto* self_obj = GetSelfData<urge::GPUQueue>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    VALUE buffer_val;
    uint64_t offset;
    std::string data;
    ParseArgs(argc, argv, "ops", &buffer_val, &offset, &data);

    self_obj->WriteBuffer(
        GetObject<urge::GPUBuffer>(buffer_val, kGPUBufferDataType), offset,
        data);
  }
  EXC_END;
  return Qnil;
}

void InitGPUQueueBindingAppend(VALUE klass);

void InitGPUQueueBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUQueue", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUQueueDataType>);

  DefineMethod(klass, "submit", GPUQueue_Submit);
  DefineMethod(klass, "write_buffer", GPUQueue_WriteBuffer);
  InitGPUQueueBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUQueueBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUQueueBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
