// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_input.h"

#include "core/input.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// RGSS key constants (`Input::DOWN`, `Input::A`, ...).  They come from the
// table in core/input.h rather than from a declaration in the export block,
// so they cannot be generated.
void DefineInputKeyConstants(VALUE mod) {
  for (const auto& binding : urge::kKeyboardBindings) {
    ID key =
        rb_intern2(binding.name.data(), static_cast<long>(binding.name.size()));
    rb_const_set(mod, key, LONG2NUM(binding.key_id));
  }
}

std::string GetKeyBinding(VALUE value) {
  if (SYMBOL_P(value) || RB_TYPE_P(value, T_STRING)) {
    ID sym = rb_to_id(value);
    return rb_id2name(sym);
  } else if (FIXNUM_P(value)) {
    auto key_id = NUM2LONG(value);
    for (size_t i = 0; i < std::size(urge::kKeyboardBindings); ++i) {
      if (urge::kKeyboardBindings[i].key_id == key_id)
        return urge::kKeyboardBindings[i].name;
    }
  }

  return {};
}

/* The three query methods take a Symbol, a String or the numeric id of a key,
   which ParseArgs cannot express -- its "s" format only accepts a String.  The
   generated versions are therefore overridden in the HANDWRITTEN INIT block
   below, which registers the Manual variants under the Ruby names. */
RB_FUNC(Input_PressedManual) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE sym;
    ParseArgs(argc, argv, "o", &sym);
    std::string key = GetKeyBinding(sym);

    return urge::Input::Get().Pressed(key) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_TriggeredManual) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE sym;
    ParseArgs(argc, argv, "o", &sym);
    std::string key = GetKeyBinding(sym);

    return urge::Input::Get().Triggered(key) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_RepeatedManual) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE sym;
    ParseArgs(argc, argv, "o", &sym);
    std::string key = GetKeyBinding(sym);

    return urge::Input::Get().Repeated(key) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Input  (core/input.h:55-70)
// -------------------------------------------------------------------------

RB_FUNC(Input_Update) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Input::Get().Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Pressed) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string sym;
    ParseArgs(argc, argv, "s", &sym);

    return urge::Input::Get().Pressed(sym) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Triggered) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string sym;
    ParseArgs(argc, argv, "s", &sym);

    return urge::Input::Get().Triggered(sym) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Repeated) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string sym;
    ParseArgs(argc, argv, "s", &sym);

    return urge::Input::Get().Repeated(sym) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Dir4) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Input::Get().Dir4());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_Dir8) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Input::Get().Dir8());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_KeyPressed) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    return urge::Input::Get().KeyPressed(keycode) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_KeyTriggered) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    return urge::Input::Get().KeyTriggered(keycode) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_KeyRepeated) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    return urge::Input::Get().KeyRepeated(keycode) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Input_GetKeyName) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int keycode;
    ParseArgs(argc, argv, "i", &keycode);

    std::string result = urge::Input::Get().GetKeyName(keycode);
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

void InitInputBindingAppend(VALUE mod);

void InitInputBinding() {
  auto mod = rb_define_module("Input");

  DefineModuleFunction(mod, "update", Input_Update);
  DefineModuleFunction(mod, "pressed", Input_Pressed);
  DefineModuleFunction(mod, "triggered", Input_Triggered);
  DefineModuleFunction(mod, "repeated", Input_Repeated);
  DefineModuleFunction(mod, "dir4", Input_Dir4);
  DefineModuleFunction(mod, "dir8", Input_Dir8);
  DefineModuleFunction(mod, "key_press?", Input_KeyPressed);
  DefineModuleFunction(mod, "key_trigger?", Input_KeyTriggered);
  DefineModuleFunction(mod, "key_repeat?", Input_KeyRepeated);
  DefineModuleFunction(mod, "get_key_name", Input_GetKeyName);
  DefineInputKeyConstants(mod);
  InitInputBindingAppend(mod);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// The generated `pressed` / `triggered` / `repeated` only accept a String,
// while RGSS hands them a Symbol (`Input.trigger?(:C)`) and the numeric key id
// is accepted too.  Re-registering the names here swaps the generated bodies
// for the Manual variants defined in the HANDWRITTEN block, which go through
// GetKeyBinding().
//
// The generated registrations happen first -- this block runs at the end of
// InitInputBinding() --, so the later definition wins.
void InitInputBindingAppend(VALUE mod) {
  DefineModuleFunction(mod, "press?", Input_PressedManual);
  DefineModuleFunction(mod, "trigger?", Input_TriggeredManual);
  DefineModuleFunction(mod, "repeat?", Input_RepeatedManual);
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
