// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_render_pass_descriptor.h"

#include "binding_gpu_object.h"
#include "binding_gpu_texture_view.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPURenderPassDescriptor  (core/gpu.h:569-618)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPURenderPassDescriptor, GPUObject);

RB_FUNC(GPURenderPassDescriptor_initialize) {
  urge::RefPtr<urge::GPURenderPassDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPURenderPassDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPURenderPassDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPURenderPassDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPURenderPassDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: color_view (RefPtr<GPUTextureView>)
BINDING_ATTR_OBJECT_REF(GPURenderPassDescriptor,
                        urge::GPURenderPassDescriptor,
                        ColorView,
                        urge::GPUTextureView,
                        kGPUTextureViewDataType);

// Attribute: load_op (uint32_t)
BINDING_ATTR_INT(GPURenderPassDescriptor,
                 urge::GPURenderPassDescriptor,
                 LoadOp);

// Attribute: store_op (uint32_t)
BINDING_ATTR_INT(GPURenderPassDescriptor,
                 urge::GPURenderPassDescriptor,
                 StoreOp);

// Attribute: clear_r (float)
BINDING_ATTR_FLOAT(GPURenderPassDescriptor,
                   urge::GPURenderPassDescriptor,
                   ClearR);

// Attribute: clear_g (float)
BINDING_ATTR_FLOAT(GPURenderPassDescriptor,
                   urge::GPURenderPassDescriptor,
                   ClearG);

// Attribute: clear_b (float)
BINDING_ATTR_FLOAT(GPURenderPassDescriptor,
                   urge::GPURenderPassDescriptor,
                   ClearB);

// Attribute: clear_a (float)
BINDING_ATTR_FLOAT(GPURenderPassDescriptor,
                   urge::GPURenderPassDescriptor,
                   ClearA);

void InitGPURenderPassDescriptorBindingAppend(VALUE klass);

void InitGPURenderPassDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPURenderPassDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPURenderPassDescriptorDataType>);

  DefineMethod(klass, "initialize", GPURenderPassDescriptor_initialize);
  DefineMethod(klass, "label", GPURenderPassDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPURenderPassDescriptor_SetLabel);
  DefineMethod(klass, "color_view", GPURenderPassDescriptor_ColorView);
  DefineMethod(klass, "color_view=", GPURenderPassDescriptor_ColorViewEqual);
  DefineMethod(klass, "load_op", GPURenderPassDescriptor_LoadOp);
  DefineMethod(klass, "load_op=", GPURenderPassDescriptor_LoadOpEqual);
  DefineMethod(klass, "store_op", GPURenderPassDescriptor_StoreOp);
  DefineMethod(klass, "store_op=", GPURenderPassDescriptor_StoreOpEqual);
  DefineMethod(klass, "clear_r", GPURenderPassDescriptor_ClearR);
  DefineMethod(klass, "clear_r=", GPURenderPassDescriptor_ClearREqual);
  DefineMethod(klass, "clear_g", GPURenderPassDescriptor_ClearG);
  DefineMethod(klass, "clear_g=", GPURenderPassDescriptor_ClearGEqual);
  DefineMethod(klass, "clear_b", GPURenderPassDescriptor_ClearB);
  DefineMethod(klass, "clear_b=", GPURenderPassDescriptor_ClearBEqual);
  DefineMethod(klass, "clear_a", GPURenderPassDescriptor_ClearA);
  DefineMethod(klass, "clear_a=", GPURenderPassDescriptor_ClearAEqual);
  InitGPURenderPassDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPURenderPassDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPURenderPassDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
