#pragma once

// Generated by bind/generate_binding.py -- do not edit.
// Rules: bind/Bindgen.md

#include "cruby_utils.h"

namespace binding {

RB_DECL_TYPE(Viewport);

void InitViewportBinding();

}  // namespace binding
