// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_fetch.h"

#include "core/network.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// `Fetch#body` answers ASCII-8BIT bytes, for the same reason as
// `NetworkEvent#data`.
RB_FUNC(Fetch_Body) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  const std::string& body = self_obj->body();
  return rb_enc_str_new(body.data(), static_cast<long>(body.size()),
                        rb_ascii8bit_encoding());
}

void DefineFetchBody(VALUE klass) {
  DefineMethod(klass, "body", Fetch_Body);
}
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Fetch  (core/network.h:128-161)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Fetch);

RB_FUNC(Fetch_initialize) {
  urge::RefPtr<urge::Fetch> obj = nullptr;
  EXC_BEGIN {
    if (argc == 1) {
      // initialize(url)
      std::string url;
      ParseArgs(argc, argv, "s", &url);
      obj = urge::MakeRefCounted<urge::Fetch>(url);
    } else if (argc == 2) {
      // initialize(url, method)
      std::string url, method;
      ParseArgs(argc, argv, "ss", &url, &method);
      obj = urge::MakeRefCounted<urge::Fetch>(url, method);
    } else if (argc == 3) {
      // initialize(url, method, body)
      std::string url, method, body;
      ParseArgs(argc, argv, "sss", &url, &method, &body);
      obj = urge::MakeRefCounted<urge::Fetch>(url, method, body);
    } else if (argc == 4) {
      // initialize(url, method, body, headers)
      std::string url, method, body;
      VALUE headers_val;
      ParseArgs(argc, argv, "ssso", &url, &method, &body, &headers_val);
      obj = urge::MakeRefCounted<urge::Fetch>(url, method, body,
          GetVectorOf<std::string>(headers_val));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Fetch_Start) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Start();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_Abort) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Abort();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_IsDone) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->IsDone() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_IsSuccess) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->IsSuccess() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_GetStatus) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->GetStatus());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_GetStatusText) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetStatusText();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_GetText) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetText();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_GetError) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetError();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_GetProgress) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(self_obj->GetProgress());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_GetHeader) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string name;
    ParseArgs(argc, argv, "s", &name);

    std::string result = self_obj->GetHeader(name);
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Fetch_GetHeaders) {
  auto* self_obj = GetSelfData<urge::Fetch>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return WrapVectorOf<std::string>(self_obj->GetHeaders());
  }
  EXC_END;
  return Qnil;
}

void InitFetchBindingAppend(VALUE klass);

void InitFetchBinding() {
  auto klass = rb_define_class("Fetch", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kFetchDataType>);

  DefineMethod(klass, "initialize", Fetch_initialize);
  DefineMethod(klass, "start", Fetch_Start);
  DefineMethod(klass, "abort", Fetch_Abort);
  DefineMethod(klass, "done?", Fetch_IsDone);
  DefineMethod(klass, "success?", Fetch_IsSuccess);
  DefineMethod(klass, "status", Fetch_GetStatus);
  DefineMethod(klass, "status_text", Fetch_GetStatusText);
  DefineMethod(klass, "text", Fetch_GetText);
  DefineMethod(klass, "error", Fetch_GetError);
  DefineMethod(klass, "progress", Fetch_GetProgress);
  DefineMethod(klass, "header", Fetch_GetHeader);
  DefineMethod(klass, "headers", Fetch_GetHeaders);
  DefineFetchBody(klass);
  InitFetchBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitFetchBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitFetchBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
