// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_bind_group_layout_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUBindGroupLayoutDescriptor  (core/gpu.h:365-382)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUBindGroupLayoutDescriptor, GPUObject);

RB_FUNC(GPUBindGroupLayoutDescriptor_initialize) {
  urge::RefPtr<urge::GPUBindGroupLayoutDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUBindGroupLayoutDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUBindGroupLayoutDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupLayoutDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupLayoutDescriptor_AddUniform) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t binding, visibility;
    ParseArgs(argc, argv, "uu", &binding, &visibility);

    self_obj->AddUniform(binding, visibility);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupLayoutDescriptor_AddStorage) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupLayoutDescriptor>(self);

  EXC_BEGIN {
    if (argc == 2) {
      // add_storage(binding, visibility)
      uint32_t binding, visibility;
      ParseArgs(argc, argv, "uu", &binding, &visibility);
      self_obj->AddStorage(binding, visibility);
    } else if (argc == 3) {
      // add_storage(binding, visibility, read_only)
      uint32_t binding, visibility;
      bool read_only;
      ParseArgs(argc, argv, "uub", &binding, &visibility, &read_only);
      self_obj->AddStorage(binding, visibility, read_only);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupLayoutDescriptor_AddTexture) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t binding, visibility;
    ParseArgs(argc, argv, "uu", &binding, &visibility);

    self_obj->AddTexture(binding, visibility);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBindGroupLayoutDescriptor_AddSampler) {
  auto* self_obj = GetSelfData<urge::GPUBindGroupLayoutDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t binding, visibility;
    ParseArgs(argc, argv, "uu", &binding, &visibility);

    self_obj->AddSampler(binding, visibility);
  }
  EXC_END;
  return Qnil;
}

void InitGPUBindGroupLayoutDescriptorBindingAppend(VALUE klass);

void InitGPUBindGroupLayoutDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUBindGroupLayoutDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUBindGroupLayoutDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUBindGroupLayoutDescriptor_initialize);
  DefineMethod(klass, "label", GPUBindGroupLayoutDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUBindGroupLayoutDescriptor_SetLabel);
  DefineMethod(klass, "add_uniform", GPUBindGroupLayoutDescriptor_AddUniform);
  DefineMethod(klass, "add_storage", GPUBindGroupLayoutDescriptor_AddStorage);
  DefineMethod(klass, "add_texture", GPUBindGroupLayoutDescriptor_AddTexture);
  DefineMethod(klass, "add_sampler", GPUBindGroupLayoutDescriptor_AddSampler);
  InitGPUBindGroupLayoutDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUBindGroupLayoutDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUBindGroupLayoutDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
