// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_plane.h"

#include "binding_bitmap.h"
#include "binding_color.h"
#include "binding_tone.h"
#include "binding_viewport.h"

#include "core/bitmap.h"
#include "core/plane.h"
#include "core/utility.h"
#include "core/viewport.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Plane  (core/plane.h:35-49)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Plane);

RB_FUNC(Plane_initialize) {
  urge::RefPtr<urge::Plane> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Plane>();
    } else if (argc == 1) {
      // initialize(viewport)
      VALUE viewport_val;
      ParseArgs(argc, argv, "o", &viewport_val);
      obj = urge::MakeRefCounted<urge::Plane>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

// Attribute: viewport (RefPtr<Viewport>)
BINDING_ATTR_OBJECT_REF(Plane,
                        urge::Plane,
                        Viewport,
                        urge::Viewport,
                        kViewportDataType);

// Attribute: bitmap (RefPtr<Bitmap>)
BINDING_ATTR_OBJECT_REF(Plane,
                        urge::Plane,
                        Bitmap,
                        urge::Bitmap,
                        kBitmapDataType);

// Attribute: ox (int32_t)
BINDING_ATTR_INT(Plane, urge::Plane, OX);

// Attribute: oy (int32_t)
BINDING_ATTR_INT(Plane, urge::Plane, OY);

// Attribute: zoom_x (float)
BINDING_ATTR_FLOAT(Plane, urge::Plane, ZoomX);

// Attribute: zoom_y (float)
BINDING_ATTR_FLOAT(Plane, urge::Plane, ZoomY);

// Attribute: opacity (int32_t)
BINDING_ATTR_INT(Plane, urge::Plane, Opacity);

// Attribute: blend_type (int32_t)
BINDING_ATTR_INT(Plane, urge::Plane, BlendType);

// Attribute: color (RefPtr<Color>)
BINDING_ATTR_OBJECT(Plane, urge::Plane, Color, urge::Color, kColorDataType);

// Attribute: tone (RefPtr<Tone>)
BINDING_ATTR_OBJECT(Plane, urge::Plane, Tone, urge::Tone, kToneDataType);

void InitPlaneBindingAppend(VALUE klass);

void InitPlaneBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("Plane", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kPlaneDataType>);

  DefineMethod(klass, "initialize", Plane_initialize);
  DefineMethod(klass, "viewport", Plane_Viewport);
  DefineMethod(klass, "viewport=", Plane_ViewportEqual);
  DefineMethod(klass, "bitmap", Plane_Bitmap);
  DefineMethod(klass, "bitmap=", Plane_BitmapEqual);
  DefineMethod(klass, "ox", Plane_OX);
  DefineMethod(klass, "ox=", Plane_OXEqual);
  DefineMethod(klass, "oy", Plane_OY);
  DefineMethod(klass, "oy=", Plane_OYEqual);
  DefineMethod(klass, "zoom_x", Plane_ZoomX);
  DefineMethod(klass, "zoom_x=", Plane_ZoomXEqual);
  DefineMethod(klass, "zoom_y", Plane_ZoomY);
  DefineMethod(klass, "zoom_y=", Plane_ZoomYEqual);
  DefineMethod(klass, "opacity", Plane_Opacity);
  DefineMethod(klass, "opacity=", Plane_OpacityEqual);
  DefineMethod(klass, "blend_type", Plane_BlendType);
  DefineMethod(klass, "blend_type=", Plane_BlendTypeEqual);
  DefineMethod(klass, "color", Plane_Color);
  DefineMethod(klass, "color=", Plane_ColorEqual);
  DefineMethod(klass, "tone", Plane_Tone);
  DefineMethod(klass, "tone=", Plane_ToneEqual);
  InitPlaneBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitPlaneBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitPlaneBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
