// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_image.h"

#include "binding_color.h"
#include "binding_disposable.h"
#include "binding_rect.h"

#include "core/image.h"
#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Image  (core/image.h:35-105)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(Image, Disposable);

RB_FUNC(Image_initialize) {
  urge::RefPtr<urge::Image> obj = nullptr;
  EXC_BEGIN {
    if (argc == 1) {
      // initialize(filename)
      std::string filename;
      ParseArgs(argc, argv, "s", &filename);
      obj = urge::MakeRefCounted<urge::Image>(filename);
    } else if (argc == 2) {
      // initialize(width, height)
      int width, height;
      ParseArgs(argc, argv, "ii", &width, &height);
      obj = urge::MakeRefCounted<urge::Image>(width, height);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Image_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Image> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Image>(other, kImageDataType);
    obj = urge::MakeRefCounted<urge::Image>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Image_Width) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Width());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_Height) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Height());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_GetPixel) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    int x, y;
    ParseArgs(argc, argv, "ii", &x, &y);

    auto result = self_obj->GetPixel(x, y);
    return WrapObject(result.get(), kColorDataType);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_SetPixel) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    int x, y;
    VALUE color_val;
    ParseArgs(argc, argv, "iio", &x, &y, &color_val);

    self_obj->SetPixel(x, y, GetObject<urge::Color>(color_val, kColorDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_FillRect) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    if (argc == 2) {
      // fill_rect(rect, color)
      VALUE rect_val, color_val;
      ParseArgs(argc, argv, "oo", &rect_val, &color_val);
      self_obj->FillRect(GetObject<urge::Rect>(rect_val, kRectDataType),
          GetObject<urge::Color>(color_val, kColorDataType));
    } else if (argc == 5) {
      // fill_rect(x, y, width, height, color)
      int x, y, width, height;
      VALUE color_val;
      ParseArgs(argc, argv, "iiiio", &x, &y, &width, &height, &color_val);
      self_obj->FillRect(x, y, width, height,
          GetObject<urge::Color>(color_val, kColorDataType));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_Blt) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    if (argc == 4) {
      // blt(x, y, src_image, src_rect)
      int x, y;
      VALUE src_image_val, src_rect_val;
      ParseArgs(argc, argv, "iioo", &x, &y, &src_image_val, &src_rect_val);
      self_obj->Blt(x, y, GetObject<urge::Image>(src_image_val, kImageDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType));
    } else if (argc == 5) {
      // blt(x, y, src_image, src_rect, opacity)
      int x, y, opacity;
      VALUE src_image_val, src_rect_val;
      ParseArgs(argc, argv, "iiooi", &x, &y, &src_image_val, &src_rect_val,
          &opacity);
      self_obj->Blt(x, y, GetObject<urge::Image>(src_image_val, kImageDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType), opacity);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_StretchBlt) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    if (argc == 3) {
      // stretch_blt(dst_rect, src_image, src_rect)
      VALUE dst_rect_val, src_image_val, src_rect_val;
      ParseArgs(argc, argv, "ooo", &dst_rect_val, &src_image_val,
          &src_rect_val);
      self_obj->StretchBlt(GetObject<urge::Rect>(dst_rect_val, kRectDataType),
          GetObject<urge::Image>(src_image_val, kImageDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType));
    } else if (argc == 4) {
      // stretch_blt(dst_rect, src_image, src_rect, opacity)
      VALUE dst_rect_val, src_image_val, src_rect_val;
      int opacity;
      ParseArgs(argc, argv, "oooi", &dst_rect_val, &src_image_val,
          &src_rect_val, &opacity);
      self_obj->StretchBlt(GetObject<urge::Rect>(dst_rect_val, kRectDataType),
          GetObject<urge::Image>(src_image_val, kImageDataType),
          GetObject<urge::Rect>(src_rect_val, kRectDataType), opacity);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_GradientFillRect) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    if (argc == 3) {
      // gradient_fill_rect(rect, color1, color2)
      VALUE rect_val, color1_val, color2_val;
      ParseArgs(argc, argv, "ooo", &rect_val, &color1_val, &color2_val);
      self_obj->GradientFillRect(GetObject<urge::Rect>(rect_val, kRectDataType),
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType));
    } else if (argc == 4) {
      // gradient_fill_rect(rect, color1, color2, vertical)
      VALUE rect_val, color1_val, color2_val;
      bool vertical;
      ParseArgs(argc, argv, "ooob", &rect_val, &color1_val, &color2_val,
          &vertical);
      self_obj->GradientFillRect(GetObject<urge::Rect>(rect_val, kRectDataType),
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType), vertical);
    } else if (argc == 6) {
      // gradient_fill_rect(x, y, width, height, color1, color2)
      int x, y, width, height;
      VALUE color1_val, color2_val;
      ParseArgs(argc, argv, "iiiioo", &x, &y, &width, &height, &color1_val,
          &color2_val);
      self_obj->GradientFillRect(x, y, width, height,
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType));
    } else if (argc == 7) {
      // gradient_fill_rect(x, y, width, height, color1, color2, vertical)
      int x, y, width, height;
      VALUE color1_val, color2_val;
      bool vertical;
      ParseArgs(argc, argv, "iiiioob", &x, &y, &width, &height, &color1_val,
          &color2_val, &vertical);
      self_obj->GradientFillRect(x, y, width, height,
          GetObject<urge::Color>(color1_val, kColorDataType),
          GetObject<urge::Color>(color2_val, kColorDataType), vertical);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_Clear) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Clear();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_ClearRect) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // clear_rect(rect)
      VALUE rect_val;
      ParseArgs(argc, argv, "o", &rect_val);
      self_obj->ClearRect(GetObject<urge::Rect>(rect_val, kRectDataType));
    } else if (argc == 4) {
      // clear_rect(x, y, width, height)
      int x, y, width, height;
      ParseArgs(argc, argv, "iiii", &x, &y, &width, &height);
      self_obj->ClearRect(x, y, width, height);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_ToDump) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->ToDump();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_SaveFile) {
  auto* self_obj = GetSelfData<urge::Image>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string filename;
    ParseArgs(argc, argv, "s", &filename);

    self_obj->SaveFile(filename);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Image_FromDump) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string data;
    ParseArgs(argc, argv, "s", &data);

    auto result = urge::Image::FromDump(data);
    return WrapObject(result.get(), kImageDataType);
  }
  EXC_END;
  return Qnil;
}

void InitImageBindingAppend(VALUE klass);

void InitImageBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Disposable"));
  auto klass = rb_define_class("Image", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kImageDataType>);

  DefineMethod(klass, "initialize", Image_initialize);
  DefineMethod(klass, "initialize_copy", Image_initialize_copy);
  DefineMethod(klass, "width", Image_Width);
  DefineMethod(klass, "height", Image_Height);
  DefineMethod(klass, "get_pixel", Image_GetPixel);
  DefineMethod(klass, "set_pixel", Image_SetPixel);
  DefineMethod(klass, "fill_rect", Image_FillRect);
  DefineMethod(klass, "blt", Image_Blt);
  DefineMethod(klass, "stretch_blt", Image_StretchBlt);
  DefineMethod(klass, "gradient_fill_rect", Image_GradientFillRect);
  DefineMethod(klass, "clear", Image_Clear);
  DefineMethod(klass, "clear_rect", Image_ClearRect);
  DefineMethod(klass, "to_dump", Image_ToDump);
  DefineMethod(klass, "save_file", Image_SaveFile);
  DefineClassMethod(klass, "from_dump", Image_FromDump);
  InitImageBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitImageBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitImageBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
