// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_buffer.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUBuffer  (core/gpu.h:683-704)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUBuffer, GPUObject);

RB_FUNC(GPUBuffer_GetSize) {
  auto* self_obj = GetSelfData<urge::GPUBuffer>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return ULL2NUM(self_obj->GetSize());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBuffer_MapAsync) {
  auto* self_obj = GetSelfData<urge::GPUBuffer>(self);

  EXC_BEGIN {
    CheckArgc(argc, 3);
    uint32_t mode;
    uint64_t offset, size;
    ParseArgs(argc, argv, "upp", &mode, &offset, &size);

    return self_obj->MapAsync(mode, offset, size) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBuffer_Unmap) {
  auto* self_obj = GetSelfData<urge::GPUBuffer>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Unmap();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBuffer_Read) {
  auto* self_obj = GetSelfData<urge::GPUBuffer>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint64_t offset, size;
    ParseArgs(argc, argv, "pp", &offset, &size);

    std::string result = self_obj->Read(offset, size);
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBuffer_Write) {
  auto* self_obj = GetSelfData<urge::GPUBuffer>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint64_t offset;
    std::string data;
    ParseArgs(argc, argv, "ps", &offset, &data);

    self_obj->Write(offset, data);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUBuffer_Destroy) {
  auto* self_obj = GetSelfData<urge::GPUBuffer>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Destroy();
  }
  EXC_END;
  return Qnil;
}

// Attribute: usage (uint32_t)
BINDING_ATTR_INT(GPUBuffer, urge::GPUBuffer, Usage);

// Attribute: map_state (uint32_t)
BINDING_ATTR_INT(GPUBuffer, urge::GPUBuffer, MapState);

void InitGPUBufferBindingAppend(VALUE klass);

void InitGPUBufferBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUBuffer", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUBufferDataType>);

  DefineMethod(klass, "size", GPUBuffer_GetSize);
  DefineMethod(klass, "map_async", GPUBuffer_MapAsync);
  DefineMethod(klass, "unmap", GPUBuffer_Unmap);
  DefineMethod(klass, "read", GPUBuffer_Read);
  DefineMethod(klass, "write", GPUBuffer_Write);
  DefineMethod(klass, "destroy", GPUBuffer_Destroy);
  DefineMethod(klass, "usage", GPUBuffer_Usage);
  DefineMethod(klass, "usage=", GPUBuffer_UsageEqual);
  DefineMethod(klass, "map_state", GPUBuffer_MapState);
  DefineMethod(klass, "map_state=", GPUBuffer_MapStateEqual);
  InitGPUBufferBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUBufferBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUBufferBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
