// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_mouse.h"

#include "binding_bitmap.h"

#include "core/bitmap.h"
#include "core/mouse.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Mouse  (core/mouse.h:38-120)
// -------------------------------------------------------------------------

RB_FUNC(Mouse_Update) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Mouse::Get().Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_X) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(urge::Mouse::Get().X());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_Y) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(urge::Mouse::Get().Y());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_SetPosition) {
  EXC_BEGIN {
    CheckArgc(argc, 2);
    double x, y;
    ParseArgs(argc, argv, "ff", &x, &y);

    urge::Mouse::Get().SetPosition(static_cast<float>(x),
        static_cast<float>(y));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_DeltaX) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(urge::Mouse::Get().DeltaX());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_DeltaY) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return rb_float_new(urge::Mouse::Get().DeltaY());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_FlushDelta) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    urge::Mouse::Get().FlushDelta();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_IsDown) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int button;
    ParseArgs(argc, argv, "i", &button);

    return urge::Mouse::Get().IsDown(button) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_IsUp) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int button;
    ParseArgs(argc, argv, "i", &button);

    return urge::Mouse::Get().IsUp(button) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_IsDouble) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int button;
    ParseArgs(argc, argv, "i", &button);

    return urge::Mouse::Get().IsDouble(button) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_IsPress) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int button;
    ParseArgs(argc, argv, "i", &button);

    return urge::Mouse::Get().IsPress(button) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_IsMove) {
  EXC_BEGIN {
    CheckArgc(argc, 1);
    int button;
    ParseArgs(argc, argv, "i", &button);

    return urge::Mouse::Get().IsMove(button) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_ScrollX) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Mouse::Get().ScrollX());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_ScrollY) {
  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(urge::Mouse::Get().ScrollY());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_SetCursor) {
  EXC_BEGIN {
    CheckArgc(argc, 3);
    VALUE image_val;
    int hot_x, hot_y;
    ParseArgs(argc, argv, "oii", &image_val, &hot_x, &hot_y);

    urge::Mouse::Get(
        ).SetCursor(GetObject<urge::Bitmap>(image_val, kBitmapDataType), hot_x,
        hot_y);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_Capture) {
  EXC_BEGIN {
    return (*urge::Mouse::Get().Attr_Capture()) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_CaptureEqual) {
  bool value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "b", &value);
    urge::Mouse::Get().Attr_Capture(value != 0);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_Visible) {
  EXC_BEGIN {
    return (*urge::Mouse::Get().Attr_Visible()) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_VisibleEqual) {
  bool value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "b", &value);
    urge::Mouse::Get().Attr_Visible(value != 0);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_Relative) {
  EXC_BEGIN {
    return (*urge::Mouse::Get().Attr_Relative()) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_RelativeEqual) {
  bool value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "b", &value);
    urge::Mouse::Get().Attr_Relative(value != 0);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_Grab) {
  EXC_BEGIN {
    return (*urge::Mouse::Get().Attr_Grab()) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_GrabEqual) {
  bool value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "b", &value);
    urge::Mouse::Get().Attr_Grab(value != 0);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_Raw) {
  EXC_BEGIN {
    return (*urge::Mouse::Get().Attr_Raw()) ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_RawEqual) {
  bool value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "b", &value);
    urge::Mouse::Get().Attr_Raw(value != 0);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_SpeedScale) {
  EXC_BEGIN {
    return rb_float_new((*urge::Mouse::Get().Attr_SpeedScale()));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Mouse_SpeedScaleEqual) {
  double value = {};

  EXC_BEGIN {
    ParseArgs(argc, argv, "f", &value);
    urge::Mouse::Get().Attr_SpeedScale(static_cast<float>(value));
  }
  EXC_END;
  return Qnil;
}

void InitMouseBindingAppend(VALUE mod);

void InitMouseBinding() {
  auto mod = rb_define_module("Mouse");

  DefineModuleFunction(mod, "update", Mouse_Update);
  DefineModuleFunction(mod, "x", Mouse_X);
  DefineModuleFunction(mod, "y", Mouse_Y);
  DefineModuleFunction(mod, "set_position", Mouse_SetPosition);
  DefineModuleFunction(mod, "delta_x", Mouse_DeltaX);
  DefineModuleFunction(mod, "delta_y", Mouse_DeltaY);
  DefineModuleFunction(mod, "flush_delta", Mouse_FlushDelta);
  DefineModuleFunction(mod, "down?", Mouse_IsDown);
  DefineModuleFunction(mod, "up?", Mouse_IsUp);
  DefineModuleFunction(mod, "double?", Mouse_IsDouble);
  DefineModuleFunction(mod, "press?", Mouse_IsPress);
  DefineModuleFunction(mod, "move?", Mouse_IsMove);
  DefineModuleFunction(mod, "scroll_x", Mouse_ScrollX);
  DefineModuleFunction(mod, "scroll_y", Mouse_ScrollY);
  DefineModuleFunction(mod, "set_cursor", Mouse_SetCursor);
  DefineModuleFunction(mod, "capture", Mouse_Capture);
  DefineModuleFunction(mod, "capture=", Mouse_CaptureEqual);
  DefineModuleFunction(mod, "visible", Mouse_Visible);
  DefineModuleFunction(mod, "visible=", Mouse_VisibleEqual);
  DefineModuleFunction(mod, "relative", Mouse_Relative);
  DefineModuleFunction(mod, "relative=", Mouse_RelativeEqual);
  DefineModuleFunction(mod, "grab", Mouse_Grab);
  DefineModuleFunction(mod, "grab=", Mouse_GrabEqual);
  DefineModuleFunction(mod, "raw", Mouse_Raw);
  DefineModuleFunction(mod, "raw=", Mouse_RawEqual);
  DefineModuleFunction(mod, "speed_scale", Mouse_SpeedScale);
  DefineModuleFunction(mod, "speed_scale=", Mouse_SpeedScaleEqual);
  InitMouseBindingAppend(mod);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitMouseBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitMouseBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
