// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_compute_pass_encoder.h"

#include "binding_gpu_bind_group.h"
#include "binding_gpu_compute_pipeline.h"
#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUComputePassEncoder  (core/gpu.h:930-940)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUComputePassEncoder, GPUObject);

RB_FUNC(GPUComputePassEncoder_SetPipeline) {
  auto* self_obj = GetSelfData<urge::GPUComputePassEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE pipeline_val;
    ParseArgs(argc, argv, "o", &pipeline_val);

    self_obj->SetPipeline(
        GetObject<urge::GPUComputePipeline>(pipeline_val, kGPUComputePipelineDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUComputePassEncoder_SetBindGroup) {
  auto* self_obj = GetSelfData<urge::GPUComputePassEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t index;
    VALUE group_val;
    ParseArgs(argc, argv, "uo", &index, &group_val);

    self_obj->SetBindGroup(index,
        GetObject<urge::GPUBindGroup>(group_val, kGPUBindGroupDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUComputePassEncoder_DispatchWorkgroups) {
  auto* self_obj = GetSelfData<urge::GPUComputePassEncoder>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // dispatch_workgroups(x)
      uint32_t x;
      ParseArgs(argc, argv, "u", &x);
      self_obj->DispatchWorkgroups(x);
    } else if (argc == 2) {
      // dispatch_workgroups(x, y)
      uint32_t x, y;
      ParseArgs(argc, argv, "uu", &x, &y);
      self_obj->DispatchWorkgroups(x, y);
    } else if (argc == 3) {
      // dispatch_workgroups(x, y, z)
      uint32_t x, y, z;
      ParseArgs(argc, argv, "uuu", &x, &y, &z);
      self_obj->DispatchWorkgroups(x, y, z);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUComputePassEncoder_End) {
  auto* self_obj = GetSelfData<urge::GPUComputePassEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->End();
  }
  EXC_END;
  return Qnil;
}

void InitGPUComputePassEncoderBindingAppend(VALUE klass);

void InitGPUComputePassEncoderBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUComputePassEncoder", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUComputePassEncoderDataType>);

  DefineMethod(klass, "set_pipeline", GPUComputePassEncoder_SetPipeline);
  DefineMethod(klass, "set_bind_group", GPUComputePassEncoder_SetBindGroup);
  DefineMethod(klass, "dispatch_workgroups", GPUComputePassEncoder_DispatchWorkgroups);
  DefineMethod(klass, "end", GPUComputePassEncoder_End);
  InitGPUComputePassEncoderBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUComputePassEncoderBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUComputePassEncoderBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
