// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_window_vx.h"

#include "binding_bitmap.h"
#include "binding_rect.h"
#include "binding_viewport.h"

#include "core/bitmap.h"
#include "core/utility.h"
#include "core/viewport.h"
#include "core/window_vx.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// WindowVX  (core/window_vx.h:80-110)
// -------------------------------------------------------------------------

RB_DEF_TYPE(WindowVX);

RB_FUNC(WindowVX_initialize) {
  urge::RefPtr<urge::WindowVX> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::WindowVX>();
    } else if (argc == 1) {
      // initialize(viewport)
      VALUE viewport_val;
      ParseArgs(argc, argv, "o", &viewport_val);
      obj = urge::MakeRefCounted<urge::WindowVX>(
          GetObject<urge::Viewport>(viewport_val, kViewportDataType));
    } else if (argc == 4) {
      // initialize(x, y, width, height)
      int x, y, width, height;
      ParseArgs(argc, argv, "iiii", &x, &y, &width, &height);
      obj = urge::MakeRefCounted<urge::WindowVX>(x, y, width, height);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(WindowVX_Update) {
  auto* self_obj = GetSelfData<urge::WindowVX>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Update();
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WindowVX_Move) {
  auto* self_obj = GetSelfData<urge::WindowVX>(self);

  EXC_BEGIN {
    CheckArgc(argc, 4);
    int x, y, width, height;
    ParseArgs(argc, argv, "iiii", &x, &y, &width, &height);

    self_obj->Move(x, y, width, height);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WindowVX_Opened) {
  auto* self_obj = GetSelfData<urge::WindowVX>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->Opened() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(WindowVX_Closed) {
  auto* self_obj = GetSelfData<urge::WindowVX>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->Closed() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

// Attribute: viewport (RefPtr<Viewport>)
BINDING_ATTR_OBJECT_REF(WindowVX,
                        urge::WindowVX,
                        Viewport,
                        urge::Viewport,
                        kViewportDataType);

// Attribute: windowskin (RefPtr<Bitmap>)
BINDING_ATTR_OBJECT_REF(WindowVX,
                        urge::WindowVX,
                        Windowskin,
                        urge::Bitmap,
                        kBitmapDataType);

// Attribute: contents (RefPtr<Bitmap>)
BINDING_ATTR_OBJECT_REF(WindowVX,
                        urge::WindowVX,
                        Contents,
                        urge::Bitmap,
                        kBitmapDataType);

// Attribute: cursor_rect (RefPtr<Rect>)
BINDING_ATTR_OBJECT(WindowVX,
                    urge::WindowVX,
                    CursorRect,
                    urge::Rect,
                    kRectDataType);

// Attribute: active (bool)
BINDING_ATTR_BOOL(WindowVX, urge::WindowVX, Active);

// Attribute: arrows_visible (bool)
BINDING_ATTR_BOOL(WindowVX, urge::WindowVX, ArrowsVisible);

// Attribute: pause (bool)
BINDING_ATTR_BOOL(WindowVX, urge::WindowVX, Pause);

// Attribute: x (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, X);

// Attribute: y (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, Y);

// Attribute: width (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, Width);

// Attribute: height (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, Height);

// Attribute: ox (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, OX);

// Attribute: oy (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, OY);

// Attribute: padding (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, Padding);

// Attribute: padding_bottom (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, PaddingBottom);

// Attribute: opacity (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, Opacity);

// Attribute: back_opacity (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, BackOpacity);

// Attribute: contents_opacity (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, ContentsOpacity);

// Attribute: openness (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, Openness);

// Attribute: scale (int32_t)
BINDING_ATTR_INT(WindowVX, urge::WindowVX, Scale);

void InitWindowVXBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Node"));
  auto klass = rb_define_class("WindowVX", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kWindowVXDataType>);

  DefineMethod(klass, "initialize", WindowVX_initialize);
  DefineMethod(klass, "update", WindowVX_Update);
  DefineMethod(klass, "move", WindowVX_Move);
  DefineMethod(klass, "opened", WindowVX_Opened);
  DefineMethod(klass, "closed", WindowVX_Closed);
  DefineMethod(klass, "viewport", WindowVX_Viewport);
  DefineMethod(klass, "viewport=", WindowVX_ViewportEqual);
  DefineMethod(klass, "windowskin", WindowVX_Windowskin);
  DefineMethod(klass, "windowskin=", WindowVX_WindowskinEqual);
  DefineMethod(klass, "contents", WindowVX_Contents);
  DefineMethod(klass, "contents=", WindowVX_ContentsEqual);
  DefineMethod(klass, "cursor_rect", WindowVX_CursorRect);
  DefineMethod(klass, "cursor_rect=", WindowVX_CursorRectEqual);
  DefineMethod(klass, "active", WindowVX_Active);
  DefineMethod(klass, "active=", WindowVX_ActiveEqual);
  DefineMethod(klass, "arrows_visible", WindowVX_ArrowsVisible);
  DefineMethod(klass, "arrows_visible=", WindowVX_ArrowsVisibleEqual);
  DefineMethod(klass, "pause", WindowVX_Pause);
  DefineMethod(klass, "pause=", WindowVX_PauseEqual);
  DefineMethod(klass, "x", WindowVX_X);
  DefineMethod(klass, "x=", WindowVX_XEqual);
  DefineMethod(klass, "y", WindowVX_Y);
  DefineMethod(klass, "y=", WindowVX_YEqual);
  DefineMethod(klass, "width", WindowVX_Width);
  DefineMethod(klass, "width=", WindowVX_WidthEqual);
  DefineMethod(klass, "height", WindowVX_Height);
  DefineMethod(klass, "height=", WindowVX_HeightEqual);
  DefineMethod(klass, "ox", WindowVX_OX);
  DefineMethod(klass, "ox=", WindowVX_OXEqual);
  DefineMethod(klass, "oy", WindowVX_OY);
  DefineMethod(klass, "oy=", WindowVX_OYEqual);
  DefineMethod(klass, "padding", WindowVX_Padding);
  DefineMethod(klass, "padding=", WindowVX_PaddingEqual);
  DefineMethod(klass, "padding_bottom", WindowVX_PaddingBottom);
  DefineMethod(klass, "padding_bottom=", WindowVX_PaddingBottomEqual);
  DefineMethod(klass, "opacity", WindowVX_Opacity);
  DefineMethod(klass, "opacity=", WindowVX_OpacityEqual);
  DefineMethod(klass, "back_opacity", WindowVX_BackOpacity);
  DefineMethod(klass, "back_opacity=", WindowVX_BackOpacityEqual);
  DefineMethod(klass, "contents_opacity", WindowVX_ContentsOpacity);
  DefineMethod(klass, "contents_opacity=", WindowVX_ContentsOpacityEqual);
  DefineMethod(klass, "openness", WindowVX_Openness);
  DefineMethod(klass, "openness=", WindowVX_OpennessEqual);
  DefineMethod(klass, "scale", WindowVX_Scale);
  DefineMethod(klass, "scale=", WindowVX_ScaleEqual);
}
// --- GENERATED END ---

}  // namespace binding
