// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_vector4.h"

#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Vector4  (core/utility.h:292-309)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Vector4);

RB_FUNC(Vector4_initialize) {
  urge::RefPtr<urge::Vector4> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Vector4>();
    } else if (argc == 1) {
      // initialize(v)
      double v;
      ParseArgs(argc, argv, "f", &v);
      obj = urge::MakeRefCounted<urge::Vector4>(static_cast<float>(v));
    } else if (argc == 4) {
      // initialize(xv, yv, zv, wv)
      double xv, yv, zv, wv;
      ParseArgs(argc, argv, "ffff", &xv, &yv, &zv, &wv);
      obj = urge::MakeRefCounted<urge::Vector4>(static_cast<float>(xv),
          static_cast<float>(yv), static_cast<float>(zv),
          static_cast<float>(wv));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Vector4_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Vector4> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Vector4>(other, kVector4DataType);
    obj = urge::MakeRefCounted<urge::Vector4>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Vector4_Set) {
  auto* self_obj = GetSelfData<urge::Vector4>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // set(v)
      VALUE v_val;
      ParseArgs(argc, argv, "o", &v_val);
      self_obj->Set(GetObject<urge::Vector4>(v_val, kVector4DataType));
    } else if (argc == 4) {
      // set(xv, yv, zv, wv)
      double xv, yv, zv, wv;
      ParseArgs(argc, argv, "ffff", &xv, &yv, &zv, &wv);
      self_obj->Set(static_cast<float>(xv), static_cast<float>(yv),
          static_cast<float>(zv), static_cast<float>(wv));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

void InitVector4BindingAppend(VALUE klass);

void InitVector4Binding() {
  auto klass = rb_define_class("Vector4", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kVector4DataType>);

  DefineMethod(klass, "initialize", Vector4_initialize);
  DefineMethod(klass, "initialize_copy", Vector4_initialize_copy);
  DefineMethod(klass, "set", Vector4_Set);
  InitVector4BindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitVector4Binding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitVector4BindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
