// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_render_pass_encoder.h"

#include "binding_gpu_bind_group.h"
#include "binding_gpu_buffer.h"
#include "binding_gpu_object.h"
#include "binding_gpu_render_pipeline.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPURenderPassEncoder  (core/gpu.h:896-922)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPURenderPassEncoder, GPUObject);

RB_FUNC(GPURenderPassEncoder_SetPipeline) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    VALUE pipeline_val;
    ParseArgs(argc, argv, "o", &pipeline_val);

    self_obj->SetPipeline(
        GetObject<urge::GPURenderPipeline>(pipeline_val, kGPURenderPipelineDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_SetBindGroup) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 2);
    uint32_t index;
    VALUE group_val;
    ParseArgs(argc, argv, "uo", &index, &group_val);

    self_obj->SetBindGroup(index,
        GetObject<urge::GPUBindGroup>(group_val, kGPUBindGroupDataType));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_SetVertexBuffer) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    if (argc == 2) {
      // set_vertex_buffer(slot, buffer)
      uint32_t slot;
      VALUE buffer_val;
      ParseArgs(argc, argv, "uo", &slot, &buffer_val);
      self_obj->SetVertexBuffer(slot,
          GetObject<urge::GPUBuffer>(buffer_val, kGPUBufferDataType));
    } else if (argc == 3) {
      // set_vertex_buffer(slot, buffer, offset)
      uint32_t slot;
      VALUE buffer_val;
      uint64_t offset;
      ParseArgs(argc, argv, "uop", &slot, &buffer_val, &offset);
      self_obj->SetVertexBuffer(slot,
          GetObject<urge::GPUBuffer>(buffer_val, kGPUBufferDataType), offset);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_SetIndexBuffer) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    if (argc == 2) {
      // set_index_buffer(buffer, format)
      VALUE buffer_val;
      uint32_t format;
      ParseArgs(argc, argv, "ou", &buffer_val, &format);
      self_obj->SetIndexBuffer(
          GetObject<urge::GPUBuffer>(buffer_val, kGPUBufferDataType), format);
    } else if (argc == 3) {
      // set_index_buffer(buffer, format, offset)
      VALUE buffer_val;
      uint32_t format;
      uint64_t offset;
      ParseArgs(argc, argv, "oup", &buffer_val, &format, &offset);
      self_obj->SetIndexBuffer(
          GetObject<urge::GPUBuffer>(buffer_val, kGPUBufferDataType), format,
          offset);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_Draw) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // draw(vertex_count)
      uint32_t vertex_count;
      ParseArgs(argc, argv, "u", &vertex_count);
      self_obj->Draw(vertex_count);
    } else if (argc == 2) {
      // draw(vertex_count, instance_count)
      uint32_t vertex_count, instance_count;
      ParseArgs(argc, argv, "uu", &vertex_count, &instance_count);
      self_obj->Draw(vertex_count, instance_count);
    } else if (argc == 3) {
      // draw(vertex_count, instance_count, first_vertex)
      uint32_t vertex_count, instance_count, first_vertex;
      ParseArgs(argc, argv, "uuu", &vertex_count, &instance_count,
          &first_vertex);
      self_obj->Draw(vertex_count, instance_count, first_vertex);
    } else if (argc == 4) {
      // draw(vertex_count, instance_count, first_vertex, first_instance)
      uint32_t vertex_count, instance_count, first_vertex, first_instance;
      ParseArgs(argc, argv, "uuuu", &vertex_count, &instance_count,
          &first_vertex, &first_instance);
      self_obj->Draw(vertex_count, instance_count, first_vertex,
          first_instance);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_DrawIndexed) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // draw_indexed(index_count)
      uint32_t index_count;
      ParseArgs(argc, argv, "u", &index_count);
      self_obj->DrawIndexed(index_count);
    } else if (argc == 2) {
      // draw_indexed(index_count, instance_count)
      uint32_t index_count, instance_count;
      ParseArgs(argc, argv, "uu", &index_count, &instance_count);
      self_obj->DrawIndexed(index_count, instance_count);
    } else if (argc == 3) {
      // draw_indexed(index_count, instance_count, first_index)
      uint32_t index_count, instance_count, first_index;
      ParseArgs(argc, argv, "uuu", &index_count, &instance_count, &first_index);
      self_obj->DrawIndexed(index_count, instance_count, first_index);
    } else if (argc == 4) {
      // draw_indexed(index_count, instance_count, first_index, base_vertex)
      uint32_t index_count, instance_count, first_index;
      int base_vertex;
      ParseArgs(argc, argv, "uuui", &index_count, &instance_count, &first_index,
          &base_vertex);
      self_obj->DrawIndexed(index_count, instance_count, first_index,
          base_vertex);
    } else if (argc == 5) {
      // draw_indexed(index_count, instance_count, first_index, base_vertex, first_instance)
      uint32_t index_count, instance_count, first_index, first_instance;
      int base_vertex;
      ParseArgs(argc, argv, "uuuiu", &index_count, &instance_count,
          &first_index, &base_vertex, &first_instance);
      self_obj->DrawIndexed(index_count, instance_count, first_index,
          base_vertex, first_instance);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_SetViewport) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    if (argc == 4) {
      // set_viewport(x, y, width, height)
      double x, y, width, height;
      ParseArgs(argc, argv, "ffff", &x, &y, &width, &height);
      self_obj->SetViewport(static_cast<float>(x), static_cast<float>(y),
          static_cast<float>(width), static_cast<float>(height));
    } else if (argc == 5) {
      // set_viewport(x, y, width, height, min_depth)
      double x, y, width, height, min_depth;
      ParseArgs(argc, argv, "fffff", &x, &y, &width, &height, &min_depth);
      self_obj->SetViewport(static_cast<float>(x), static_cast<float>(y),
          static_cast<float>(width), static_cast<float>(height),
          static_cast<float>(min_depth));
    } else if (argc == 6) {
      // set_viewport(x, y, width, height, min_depth, max_depth)
      double x, y, width, height, min_depth, max_depth;
      ParseArgs(argc, argv, "ffffff", &x, &y, &width, &height, &min_depth,
          &max_depth);
      self_obj->SetViewport(static_cast<float>(x), static_cast<float>(y),
          static_cast<float>(width), static_cast<float>(height),
          static_cast<float>(min_depth), static_cast<float>(max_depth));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_SetScissorRect) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 4);
    uint32_t x, y, width, height;
    ParseArgs(argc, argv, "uuuu", &x, &y, &width, &height);

    self_obj->SetScissorRect(x, y, width, height);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPURenderPassEncoder_End) {
  auto* self_obj = GetSelfData<urge::GPURenderPassEncoder>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->End();
  }
  EXC_END;
  return Qnil;
}

void InitGPURenderPassEncoderBindingAppend(VALUE klass);

void InitGPURenderPassEncoderBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPURenderPassEncoder", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPURenderPassEncoderDataType>);

  DefineMethod(klass, "set_pipeline", GPURenderPassEncoder_SetPipeline);
  DefineMethod(klass, "set_bind_group", GPURenderPassEncoder_SetBindGroup);
  DefineMethod(klass, "set_vertex_buffer", GPURenderPassEncoder_SetVertexBuffer);
  DefineMethod(klass, "set_index_buffer", GPURenderPassEncoder_SetIndexBuffer);
  DefineMethod(klass, "draw", GPURenderPassEncoder_Draw);
  DefineMethod(klass, "draw_indexed", GPURenderPassEncoder_DrawIndexed);
  DefineMethod(klass, "set_viewport", GPURenderPassEncoder_SetViewport);
  DefineMethod(klass, "set_scissor_rect", GPURenderPassEncoder_SetScissorRect);
  DefineMethod(klass, "end", GPURenderPassEncoder_End);
  InitGPURenderPassEncoderBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPURenderPassEncoderBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPURenderPassEncoderBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
