// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_animation.h"

#include "binding_disposable.h"
#include "binding_image.h"

#include "core/animation.h"
#include "core/image.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Animation  (core/animation.h:39-58)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(Animation, Disposable);

RB_FUNC(Animation_initialize) {
  urge::RefPtr<urge::Animation> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string filename;
    ParseArgs(argc, argv, "s", &filename);

    obj = urge::MakeRefCounted<urge::Animation>(filename);
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Animation_Width) {
  auto* self_obj = GetSelfData<urge::Animation>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Width());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Animation_Height) {
  auto* self_obj = GetSelfData<urge::Animation>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Height());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Animation_Count) {
  auto* self_obj = GetSelfData<urge::Animation>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return LONG2NUM(self_obj->Count());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Animation_Delay) {
  auto* self_obj = GetSelfData<urge::Animation>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    int index;
    ParseArgs(argc, argv, "i", &index);

    return LONG2NUM(self_obj->Delay(index));
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Animation_Delays) {
  auto* self_obj = GetSelfData<urge::Animation>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return WrapVectorOf<int32_t>(self_obj->Delays());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Animation_Frame) {
  auto* self_obj = GetSelfData<urge::Animation>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    int index;
    ParseArgs(argc, argv, "i", &index);

    auto result = self_obj->Frame(index);
    return WrapObject(result.get(), kImageDataType);
  }
  EXC_END;
  return Qnil;
}

void InitAnimationBindingAppend(VALUE klass);

void InitAnimationBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("Disposable"));
  auto klass = rb_define_class("Animation", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kAnimationDataType>);

  DefineMethod(klass, "initialize", Animation_initialize);
  DefineMethod(klass, "width", Animation_Width);
  DefineMethod(klass, "height", Animation_Height);
  DefineMethod(klass, "count", Animation_Count);
  DefineMethod(klass, "delay", Animation_Delay);
  DefineMethod(klass, "delays", Animation_Delays);
  DefineMethod(klass, "frame", Animation_Frame);
  InitAnimationBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitAnimationBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitAnimationBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
