// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_vector2.h"

#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Vector2  (core/utility.h:244-259)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Vector2);

RB_FUNC(Vector2_initialize) {
  urge::RefPtr<urge::Vector2> obj = nullptr;
  EXC_BEGIN {
    if (argc == 0) {
      // initialize()
      obj = urge::MakeRefCounted<urge::Vector2>();
    } else if (argc == 1) {
      // initialize(v)
      double v;
      ParseArgs(argc, argv, "f", &v);
      obj = urge::MakeRefCounted<urge::Vector2>(static_cast<float>(v));
    } else if (argc == 2) {
      // initialize(xv, yv)
      double xv, yv;
      ParseArgs(argc, argv, "ff", &xv, &yv);
      obj = urge::MakeRefCounted<urge::Vector2>(static_cast<float>(xv),
          static_cast<float>(yv));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(Vector2_initialize_copy) {
  VALUE other;
  ParseArgs(argc, argv, "o", &other);

  urge::RefPtr<urge::Vector2> obj = nullptr;
  EXC_BEGIN {
    auto other_obj = GetObject<urge::Vector2>(other, kVector2DataType);
    obj = urge::MakeRefCounted<urge::Vector2>(other_obj);
  }
  EXC_END;

  return SetupSelfData(self, obj.get());
}

RB_FUNC(Vector2_Set) {
  auto* self_obj = GetSelfData<urge::Vector2>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // set(v)
      VALUE v_val;
      ParseArgs(argc, argv, "o", &v_val);
      self_obj->Set(GetObject<urge::Vector2>(v_val, kVector2DataType));
    } else if (argc == 2) {
      // set(xv, yv)
      double xv, yv;
      ParseArgs(argc, argv, "ff", &xv, &yv);
      self_obj->Set(static_cast<float>(xv), static_cast<float>(yv));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

void InitVector2BindingAppend(VALUE klass);

void InitVector2Binding() {
  auto klass = rb_define_class("Vector2", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kVector2DataType>);

  DefineMethod(klass, "initialize", Vector2_initialize);
  DefineMethod(klass, "initialize_copy", Vector2_initialize_copy);
  DefineMethod(klass, "set", Vector2_Set);
  InitVector2BindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitVector2Binding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitVector2BindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
