// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_disposable.h"

#include "core/disposable.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Disposable  (core/disposable.h:32-36)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Disposable);

RB_FUNC(Disposable_IsDisposed) {
  auto* self_obj = GetSelfData<urge::Disposable>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    return self_obj->IsDisposed() ? Qtrue : Qfalse;
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Disposable_Dispose) {
  auto* self_obj = GetSelfData<urge::Disposable>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    self_obj->Dispose();
  }
  EXC_END;
  return Qnil;
}

void InitDisposableBindingAppend(VALUE klass);

void InitDisposableBinding() {
  auto klass = rb_define_class("Disposable", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kDisposableDataType>);

  DefineMethod(klass, "disposed?", Disposable_IsDisposed);
  DefineMethod(klass, "dispose", Disposable_Dispose);
  InitDisposableBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitDisposableBinding(), with `klass` the class the
// initialiser built. Patches the IR cannot express -- a proxy
// class, a method whose Ruby signature differs from its C++ one --
// belong here. The block is preserved verbatim; empty it and the
// generator writes this body back.
void InitDisposableBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
