// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_config.h"

#include "core/config.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Config  (core/config.h:36-45)
// -------------------------------------------------------------------------

RB_FUNC(Config_GetValue) {
  EXC_BEGIN {
    if (argc == 2) {
      // get_value(section, key)
      std::string section, key;
      ParseArgs(argc, argv, "ss", &section, &key);
      std::string result = urge::Config::Get().GetValue(section, key);
      return rb_enc_str_new(result.data(),
                           static_cast<long>(result.size()),
                           rb_utf8_encoding());
    } else if (argc == 3) {
      // get_value(section, key, defval)
      std::string section, key, defval;
      ParseArgs(argc, argv, "sss", &section, &key, &defval);
      std::string result = urge::Config::Get().GetValue(section, key, defval);
      return rb_enc_str_new(result.data(),
                           static_cast<long>(result.size()),
                           rb_utf8_encoding());
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Config_SetValue) {
  EXC_BEGIN {
    CheckArgc(argc, 3);
    std::string section, key, value;
    ParseArgs(argc, argv, "sss", &section, &key, &value);

    urge::Config::Get().SetValue(section, key, value);
  }
  EXC_END;
  return Qnil;
}

void InitConfigBindingAppend(VALUE mod);

void InitConfigBinding() {
  auto mod = rb_define_module("Config");

  DefineModuleFunction(mod, "get_value", Config_GetValue);
  DefineModuleFunction(mod, "set_value", Config_SetValue);
  InitConfigBindingAppend(mod);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitConfigBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitConfigBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
