// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_gpu_shader_module_descriptor.h"

#include "binding_gpu_object.h"

#include "core/gpu.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// GPUShaderModuleDescriptor  (core/gpu.h:322-353)
// -------------------------------------------------------------------------

RB_DEF_TYPE_INHERIT(GPUShaderModuleDescriptor, GPUObject);

RB_FUNC(GPUShaderModuleDescriptor_initialize) {
  urge::RefPtr<urge::GPUShaderModuleDescriptor> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::GPUShaderModuleDescriptor>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

RB_FUNC(GPUShaderModuleDescriptor_GetLabel) {
  auto* self_obj = GetSelfData<urge::GPUShaderModuleDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetLabel();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUShaderModuleDescriptor_SetLabel) {
  auto* self_obj = GetSelfData<urge::GPUShaderModuleDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetLabel(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUShaderModuleDescriptor_GetCode) {
  auto* self_obj = GetSelfData<urge::GPUShaderModuleDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetCode();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUShaderModuleDescriptor_SetCode) {
  auto* self_obj = GetSelfData<urge::GPUShaderModuleDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetCode(value);
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUShaderModuleDescriptor_GetEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPUShaderModuleDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 0);
    std::string result = self_obj->GetEntryPoint();
    return rb_enc_str_new(result.data(),
                         static_cast<long>(result.size()),
                         rb_utf8_encoding());
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(GPUShaderModuleDescriptor_SetEntryPoint) {
  auto* self_obj = GetSelfData<urge::GPUShaderModuleDescriptor>(self);

  EXC_BEGIN {
    CheckArgc(argc, 1);
    std::string value;
    ParseArgs(argc, argv, "s", &value);

    self_obj->SetEntryPoint(value);
  }
  EXC_END;
  return Qnil;
}

// Attribute: language (uint32_t)
BINDING_ATTR_INT(GPUShaderModuleDescriptor,
                 urge::GPUShaderModuleDescriptor,
                 Language);

// Attribute: stage (uint32_t)
BINDING_ATTR_INT(GPUShaderModuleDescriptor,
                 urge::GPUShaderModuleDescriptor,
                 Stage);

void InitGPUShaderModuleDescriptorBindingAppend(VALUE klass);

void InitGPUShaderModuleDescriptorBinding() {
  auto parent = rb_const_get(rb_cObject, rb_intern("GPUObject"));
  auto klass = rb_define_class("GPUShaderModuleDescriptor", parent);
  rb_define_alloc_func(klass, ClassAllocate<&kGPUShaderModuleDescriptorDataType>);

  DefineMethod(klass, "initialize", GPUShaderModuleDescriptor_initialize);
  DefineMethod(klass, "label", GPUShaderModuleDescriptor_GetLabel);
  DefineMethod(klass, "label=", GPUShaderModuleDescriptor_SetLabel);
  DefineMethod(klass, "code", GPUShaderModuleDescriptor_GetCode);
  DefineMethod(klass, "code=", GPUShaderModuleDescriptor_SetCode);
  DefineMethod(klass, "entry_point", GPUShaderModuleDescriptor_GetEntryPoint);
  DefineMethod(klass, "entry_point=", GPUShaderModuleDescriptor_SetEntryPoint);
  DefineMethod(klass, "language", GPUShaderModuleDescriptor_Language);
  DefineMethod(klass, "language=", GPUShaderModuleDescriptor_LanguageEqual);
  DefineMethod(klass, "stage", GPUShaderModuleDescriptor_Stage);
  DefineMethod(klass, "stage=", GPUShaderModuleDescriptor_StageEqual);
  InitGPUShaderModuleDescriptorBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitGPUShaderModuleDescriptorBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitGPUShaderModuleDescriptorBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
