// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md

// --- GENERATED INCLUDES BEGIN ---
#include "binding_camera.h"

#include "binding_vector3.h"
#include "binding_vector4.h"

#include "core/camera.h"
#include "core/utility.h"
// --- GENERATED INCLUDES END ---

// --- HANDWRITTEN INCLUDES BEGIN ---
// --- HANDWRITTEN INCLUDES END ---

namespace binding {

// --- HANDWRITTEN BEGIN ---
// --- HANDWRITTEN END ---

// --- GENERATED BEGIN ---
// -------------------------------------------------------------------------
// Camera  (core/camera.h:50-60)
// -------------------------------------------------------------------------

RB_DEF_TYPE(Camera);

RB_FUNC(Camera_initialize) {
  urge::RefPtr<urge::Camera> obj = nullptr;
  EXC_BEGIN {
    CheckArgc(argc, 0);
    obj = urge::MakeRefCounted<urge::Camera>();
  }
  EXC_END;
  return SetupSelfData(self, obj.get());
}

// Attribute: position (RefPtr<Vector3>)
BINDING_ATTR_OBJECT_REF(Camera,
                        urge::Camera,
                        Position,
                        urge::Vector3,
                        kVector3DataType);

// Attribute: quaternion (RefPtr<Vector4>)
BINDING_ATTR_OBJECT_REF(Camera,
                        urge::Camera,
                        Quaternion,
                        urge::Vector4,
                        kVector4DataType);

// Attribute: scale (RefPtr<Vector3>)
BINDING_ATTR_OBJECT_REF(Camera,
                        urge::Camera,
                        Scale,
                        urge::Vector3,
                        kVector3DataType);

void InitCameraBindingAppend(VALUE klass);

void InitCameraBinding() {
  auto klass = rb_define_class("Camera", rb_cObject);
  rb_define_alloc_func(klass, ClassAllocate<&kCameraDataType>);

  DefineMethod(klass, "initialize", Camera_initialize);
  DefineMethod(klass, "position", Camera_Position);
  DefineMethod(klass, "position=", Camera_PositionEqual);
  DefineMethod(klass, "quaternion", Camera_Quaternion);
  DefineMethod(klass, "quaternion=", Camera_QuaternionEqual);
  DefineMethod(klass, "scale", Camera_Scale);
  DefineMethod(klass, "scale=", Camera_ScaleEqual);
  InitCameraBindingAppend(klass);
}
// --- GENERATED END ---

// --- HANDWRITTEN INIT BEGIN ---
// Runs at the end of InitCameraBinding(), with the class (`klass`) or
// module (`mod`) the initialiser built in hand. Patches the IR
// cannot express -- a proxy class, a method whose Ruby signature
// differs from its C++ one -- belong here. The block is preserved
// verbatim; empty it and the generator writes this body back.
void InitCameraBindingAppend(VALUE klass) {
  (void)klass;
}
// --- HANDWRITTEN INIT END ---

}  // namespace binding
