#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""URGE CRuby glue generator.

Reads the IR (`bind/api_reference.json`, produced by `bind/gen_api_json.py`)
and writes one `binding_<class>.{h,cc}` per exported class or module, plus
`binding_init.{h,cc}`.

Generation is idempotent: every `.cc` is split into GENERATED blocks, which are
rewritten on each run, and HANDWRITTEN blocks, which are preserved verbatim.
Delete a file to have it recreated from the template.

Usage:
    python bind/generate_binding.py [ir.json] [output_dir]

Defaults to `bind/api_reference.json` and the `bind/` directory next to this
script.  The rules behind every emitted construct are documented in
`bind/Bindgen.md`.
"""

from __future__ import annotations

import json
import os
import re
import sys
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_IR = os.path.join(REPO_ROOT, "bind", "api_reference.json")
DEFAULT_OUT = os.path.join(REPO_ROOT, "bind")

GENERATED_INCLUDES_BEGIN = "// --- GENERATED INCLUDES BEGIN ---"
GENERATED_INCLUDES_END = "// --- GENERATED INCLUDES END ---"
HANDWRITTEN_INCLUDES_BEGIN = "// --- HANDWRITTEN INCLUDES BEGIN ---"
HANDWRITTEN_INCLUDES_END = "// --- HANDWRITTEN INCLUDES END ---"
GENERATED_BEGIN = "// --- GENERATED BEGIN ---"
GENERATED_END = "// --- GENERATED END ---"
HANDWRITTEN_BEGIN = "// --- HANDWRITTEN BEGIN ---"
HANDWRITTEN_END = "// --- HANDWRITTEN END ---"
HANDWRITTEN_INIT_BEGIN = "// --- HANDWRITTEN INIT BEGIN ---"
HANDWRITTEN_INIT_END = "// --- HANDWRITTEN INIT END ---"

# Every file this script writes carries this string in its banner.  The
# stale-file sweep below refuses to remove a file without it, so a hand-written
# `binding_something.cc` is never deleted just for matching the name pattern.
GENERATED_MARKER = "Generated by bind/generate_binding.py"
BINDING_OUTPUT_RE = re.compile(r"^binding_[a-z0-9_]+\.(h|cc)$")

FILE_HEADER = """\
// Generated by bind/generate_binding.py from the core headers. The GENERATED
// blocks are rewritten on every run; manually written glue (extra Ruby
// constants, accessors the IR cannot describe) belongs in the HANDWRITTEN
// blocks, which are preserved verbatim.
//
// The HANDWRITTEN INIT block sits after the GENERATED one and holds the body
// of Init<Class>BindingAppend(), which Init<Class>Binding() calls last, so it
// is where a patch that has to run inside the initialiser -- registering a
// proxy class, defining a method the signature cannot describe -- belongs.
//
// Rules: bind/Bindgen.md
"""

CLASS_HEADER = """\
#pragma once

// Generated by bind/generate_binding.py -- do not edit.
// Rules: bind/Bindgen.md

#include "cruby_utils.h"

namespace binding {

RB_DECL_TYPE(%s);

void Init%sBinding();

}  // namespace binding
"""

# A module (Graphics/Input) has no C++ object of its own, so it has no data
# type: it only forwards to the Singleton. See Bindgen.md "模块绑定".
MODULE_HEADER = """\
#pragma once

// Generated by bind/generate_binding.py -- do not edit.
// Rules: bind/Bindgen.md

#include "cruby_utils.h"

namespace binding {

void Init%sBinding();

}  // namespace binding
"""

# Local storage for every C++ parameter type the glue understands:
#   type -> (ParseArgs format character, local C++ type, call expression)
# `{n}` is the local variable name.  A type missing from this table marks the
# declaration as internal; gen_api_json.py already dropped those.
SCALAR_PARAMS = {
    "int8_t": ("i", "int", "static_cast<int8_t>({n})"),
    "int16_t": ("i", "int", "static_cast<int16_t>({n})"),
    "int32_t": ("i", "int", "{n}"),
    "int": ("i", "int", "{n}"),
    "uint8_t": ("u", "uint32_t", "static_cast<uint8_t>({n})"),
    "uint16_t": ("u", "uint32_t", "static_cast<uint16_t>({n})"),
    "uint32_t": ("u", "uint32_t", "{n}"),
    "unsigned int": ("u", "uint32_t", "{n}"),
    "int64_t": ("l", "int64_t", "{n}"),
    "uint64_t": ("p", "uint64_t", "{n}"),
    "float": ("f", "double", "static_cast<float>({n})"),
    "double": ("f", "double", "{n}"),
    "bool": ("b", "bool", "{n}"),
    "std::string": ("s", "std::string", "{n}"),
    "const char*": ("z", "const char*", "{n}"),
    "char*": ("z", "const char*", "{n}"),
    "std::vector<std::string>": ("o", "VALUE", "GetStringVector({n})"),
}

# C++ integral return type -> Ruby number constructor.
INT_RETURNS = {
    "int8_t": "INT2NUM",
    "int16_t": "INT2NUM",
    "int32_t": "LONG2NUM",
    "int": "LONG2NUM",
    "long": "LONG2NUM",
    "uint8_t": "UINT2NUM",
    "uint16_t": "UINT2NUM",
    "uint32_t": "ULONG2NUM",
    "unsigned int": "ULONG2NUM",
    "int64_t": "LL2NUM",
    "uint64_t": "ULL2NUM",
}

REFPTR_RE = re.compile(r"^RefPtr<\s*(?P<inner>[\w:]+)\s*>$")

# ---------------------------------------------------------------------------
# Override table
#
# Entries here exist because the Ruby side behaviour differs from a plain
# one-to-one mapping of the C++ declaration and therefore cannot be derived
# from a signature.  See Bindgen.md "特殊绑定".
# ---------------------------------------------------------------------------

TABLE_MANUAL = """\
// `Table#[]` / `Table#[]=` are hand written: Ruby hands the operands in
// (x[, y[, z]]) order with the value last, while `Table::Get` / `Table::Set`
// take the value first, so the arguments have to be reordered.  Out of range
// reads answer nil and out of range writes are ignored.
RB_FUNC(Table_Get) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  EXC_BEGIN {
    if (argc == 1) {
      // [](x)
      int x;
      ParseArgs(argc, argv, "i", &x);
      if (x < 0 || x >= self_obj->Xsize())
        return Qnil;
      return INT2NUM(self_obj->Get(x));
    } else if (argc == 2) {
      // [](x, y)
      int x, y;
      ParseArgs(argc, argv, "ii", &x, &y);
      if (x < 0 || x >= self_obj->Xsize() || y < 0 || y >= self_obj->Ysize())
        return Qnil;
      return INT2NUM(self_obj->Get(x, y));
    } else if (argc == 3) {
      // [](x, y, z)
      int x, y, z;
      ParseArgs(argc, argv, "iii", &x, &y, &z);
      if (x < 0 || x >= self_obj->Xsize() || y < 0 || y >= self_obj->Ysize() ||
          z < 0 || z >= self_obj->Zsize())
        return Qnil;
      return INT2NUM(self_obj->Get(x, y, z));
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }
  }
  EXC_END;
  return Qnil;
}

RB_FUNC(Table_Set) {
  auto* self_obj = GetSelfData<urge::Table>(self);

  int x = 0, y = 0, z = 0, value = 0;
  EXC_BEGIN {
    if (argc == 2) {
      // []=(x, value)
      ParseArgs(argc, argv, "ii", &x, &value);
    } else if (argc == 3) {
      // []=(x, y, value)
      ParseArgs(argc, argv, "iii", &x, &y, &value);
    } else if (argc == 4) {
      // []=(x, y, z, value)
      ParseArgs(argc, argv, "iiii", &x, &y, &z, &value);
    } else {
      rb_raise(rb_eArgError, "%s", "wrong number of arguments");
    }

    if (x < 0 || x >= self_obj->Xsize() || y < 0 || y >= self_obj->Ysize() ||
        z < 0 || z >= self_obj->Zsize()) {
      return Qnil;
    }

    self_obj->Set(static_cast<int16_t>(value), x, y, z);
  }
  EXC_END;
  return Qnil;
}
"""

INPUT_MANUAL = """\
// RGSS key constants (`Input::DOWN`, `Input::A`, ...).  They come from the
// table in core/input.h rather than from a declaration in the export block,
// so they cannot be generated.
void DefineInputKeyConstants(VALUE mod) {
  for (const auto& binding : urge::kKeyboardBindings) {
    ID key =
        rb_intern2(binding.name.data(), static_cast<long>(binding.name.size()));
    rb_const_set(mod, key, LONG2NUM(binding.key_id));
  }
}
"""

HANDWRITTEN_SEED = {
    "binding_table.cc": TABLE_MANUAL,
    "binding_input.cc": INPUT_MANUAL,
}

# Statements appended to the generated Init*Binding() body.
EXTRA_INIT_CALLS = {
    "Input": ["DefineInputKeyConstants(mod);"],
}


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def snake(name: str) -> str:
    out = []
    for i, c in enumerate(name):
        if c.isupper():
            if i > 0 and (
                name[i - 1].islower() or (i + 1 < len(name) and name[i + 1].islower())
            ):
                out.append("_")
            out.append(c.lower())
        else:
            out.append(c)
    return "".join(out)


def refptr_inner(cpp_type: str) -> Optional[str]:
    m = REFPTR_RE.match(cpp_type.strip())
    return m.group("inner") if m else None


def split_top_level(text: str, sep: str = ",") -> list[str]:
    parts: list[str] = []
    depth = 0
    cur: list[str] = []
    for c in text:
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        if c == sep and depth == 0:
            parts.append("".join(cur))
            cur = []
        else:
            cur.append(c)
    parts.append("".join(cur))
    return parts


def emit_call(call: str, indent: str, width: int = 80) -> list[str]:
    """Lay out a call statement, packing arguments onto continuation lines.

    `call` is the whole statement text without the trailing semicolon; the
    semicolon is added to the last line.
    """
    call = call + ";"
    line = indent + call
    if len(line) <= width or "(" not in call:
        return [line]
    paren = call.index("(")
    head = call[: paren + 1]
    args = split_top_level(call[paren + 1 : -2])
    continuation = indent + "    "
    if len(args) < 2:
        # A single argument that does not fit -- a nested call, usually. The only
        # break available is the outer parenthesis.
        if not args[0].strip():
            return [line]
        return [indent + head, continuation + args[0].strip() + ");"]
    lines: list[str] = []
    current = indent + head
    for i, arg in enumerate(args):
        piece = arg.strip() + ("," if i + 1 < len(args) else ");")
        separator = "" if current.endswith("(") else " "
        if not current.endswith("(") and len(current) + len(separator) + len(piece) > width:
            lines.append(current)
            current = continuation + piece
        else:
            current = current + separator + piece
    lines.append(current)
    return lines


def format_macro(text: str, indent: str = "", width: int = 80) -> list[str]:
    """One macro invocation, one argument per line (aligned) when too long."""
    line = indent + text
    if len(line) <= width or "(" not in text:
        return [line]
    paren = text.index("(")
    head = text[: paren + 1]
    args = split_top_level(text[paren + 1 : -2])
    if len(args) < 2:
        return [line]
    pad = " " * len(head)
    lines = [indent + head + args[0].strip() + ","]
    for arg in args[1:-1]:
        lines.append(indent + pad + arg.strip() + ",")
    lines.append(indent + pad + args[-1].strip() + ");")
    return lines


# ---------------------------------------------------------------------------
# IR model
# ---------------------------------------------------------------------------


class Model:
    def __init__(self, ir: dict[str, Any]):
        self.ir = ir
        self.classes: list[dict] = list(ir["classes"])
        self.modules: list[dict] = list(ir["modules"])
        self.by_cpp_name = {c["cpp_name"]: c for c in self.classes}
        self.marshalable = {
            c["cpp_name"]
            for c in self.classes
            if c["marshal"]["dump"] and c["marshal"]["load"]
        }

    def all_entries(self) -> list[dict]:
        return self.classes + self.modules

    def references(self, entry: dict) -> list[str]:
        """C++ classes this entry passes through `RefPtr`."""
        types: set[str] = set()
        param_groups: list[list[dict]] = []
        for ctor in entry.get("constructors", []):
            param_groups.append(ctor["params"])
        if entry.get("initialize_copy"):
            param_groups.append(entry["initialize_copy"]["params"])
        for key in ("instance_methods", "class_methods", "functions", "data_attributes"):
            for item in entry.get(key, []):
                param_groups.append(item.get("params", []))
                ret = item.get("return")
                if ret:
                    types.add(ret["cpp_type"])
        for key in ("attributes", "class_attributes"):
            for item in entry.get(key, []):
                types.add(item["cpp_type"])
        for item in (entry.get("index") or {}).values():
            param_groups.append(item.get("params", []))
        for params in param_groups:
            for p in params:
                types.add(p["type"])
        names = {refptr_inner(t) for t in types}
        names.discard(None)
        names.discard(entry["cpp_name"])
        return sorted(n for n in names if n in self.by_cpp_name)


def exported_parent(model: Model, entry: dict) -> Optional[str]:
    """The C++ base class of `entry`, when that base is exported as well.

    A derived class is only accepted where its base is expected once the two
    data types are linked (see `RB_DEF_TYPE_INHERIT` in cruby_utils.h), and
    only a base this library defines can be linked.  The generated data type
    of a class whose base is not exported -- `Object`, `Singleton<T>` -- is
    emitted without one.  The check is the same one `check_base_order` makes
    on the registration order: the parent has to be a class of the IR.
    """
    parent = entry.get("cpp_parent")
    return parent if parent in model.by_cpp_name else None


# ---------------------------------------------------------------------------
# Parameter / return emission
# ---------------------------------------------------------------------------


class ParamPlan:
    """Everything the glue needs for one argument list."""

    def __init__(self, params: list[dict]):
        self.params = params
        self.declarations: list[str] = []
        self.format = ""
        self.args: list[str] = []
        groups: list[tuple[str, list[str]]] = []
        for p in params:
            cpp_type = p["type"]
            name = p["name"]
            inner = refptr_inner(cpp_type)
            if inner is not None:
                local_kind = "VALUE"
                local = name + "_val"
                self.format += "o"
                self.args.append(
                    "GetObject<urge::%s>(%s, k%sDataType)" % (inner, local, inner)
                )
            else:
                fmt, local_kind, template = SCALAR_PARAMS[cpp_type]
                local = name + "_val" if local_kind == "VALUE" else name
                self.format += fmt
                self.args.append(template.format(n=local))
            for kind, names in groups:
                if kind == local_kind:
                    names.append(local)
                    break
            else:
                groups.append((local_kind, [local]))
        for kind, names in groups:
            self.declarations.append("%s %s;" % (kind, ", ".join(names)))
        self.locals = {
            p["name"]: (p["name"] + "_val" if self._kind(p["type"]) == "VALUE" else p["name"])
            for p in params
        }

    @staticmethod
    def _kind(cpp_type: str) -> str:
        inner = refptr_inner(cpp_type)
        if inner is not None:
            return "VALUE"
        return SCALAR_PARAMS[cpp_type][1]

    def parse_args_lines(self, indent: str) -> list[str]:
        if not self.format:
            return []
        pointers = ", ".join("&" + self.locals[p["name"]] for p in self.params)
        return emit_call(
            'ParseArgs(argc, argv, "%s", %s)' % (self.format, pointers), indent
        )


def emit_return(cpp_type: str, call: str, indent: str) -> list[str]:
    """`return <call>` converted from C++ to Ruby (or the bare call for void)."""
    if cpp_type == "void":
        return emit_call(call, indent)
    if cpp_type == "bool":
        return [indent + "return %s ? Qtrue : Qfalse;" % call]
    if cpp_type in INT_RETURNS:
        return [indent + "return %s(%s);" % (INT_RETURNS[cpp_type], call)]
    if cpp_type in ("float", "double"):
        return [indent + "return rb_float_new(%s);" % call]
    if cpp_type == "std::string":
        return emit_call("std::string result = %s" % call, indent) + [
            indent + "return rb_enc_str_new(result.data(),",
            indent + "                     static_cast<long>(result.size()),",
            indent + "                     rb_utf8_encoding());",
        ]
    if cpp_type == "std::vector<std::string>":
        return [indent + "return WrapStringVector(%s);" % call]
    inner = refptr_inner(cpp_type)
    if inner is not None:
        return [
            indent + "auto result = %s;" % call,
            indent + "return WrapObject(result.get(), k%sDataType);" % inner,
        ]
    if cpp_type in ("const char*", "char*"):
        # rubies this old have no rb_utf8_str_new_cstr, and the pointer may be
        # null, so measure it instead of relying on a NUL-terminated wrapper.
        return [
            indent + "const char* result = %s;" % call,
            indent + "return result ? rb_enc_str_new(result, static_cast<long>(std::strlen(result)),",
            indent + "                                       rb_utf8_encoding())",
            indent + "               : Qnil;",
        ]
    raise ValueError("no return conversion for %r" % cpp_type)


def arity_map(overloads: list[dict]) -> dict[int, dict]:
    """Map `argc` to the overload serving it, rejecting ambiguities."""
    covered: dict[int, dict] = {}
    for ov in overloads:
        params = ov["params"]
        if any(p["name"] == "..." for p in params):
            raise ValueError("variadic declarations are not supported")
        required = sum(1 for p in params if p.get("default") is None)
        for k in range(required, len(params) + 1):
            if k in covered:
                raise ValueError(
                    "ambiguous overload for argc=%d: %s vs %s"
                    % (k, covered[k]["cpp_name"], ov["cpp_name"])
                )
            covered[k] = ov
    return covered


def group_overloads(entries: list[dict]) -> list[list[dict]]:
    groups: dict[str, list[dict]] = {}
    order: list[str] = []
    for e in entries:
        if e["cpp_name"] not in groups:
            groups[e["cpp_name"]] = []
            order.append(e["cpp_name"])
        groups[e["cpp_name"]].append(e)
    return [groups[k] for k in order]


class Dispatch:
    """The `argc`-branch decision for one C++ declaration."""

    def __init__(self, overloads: list[dict]):
        self.overloads = overloads
        self.covered = arity_map(overloads)
        self.arities = sorted(self.covered)
        # A single fully specified shape needs no branches: CheckArgc answers
        # both the missing- and the extra-argument case on its own.
        self.simple = len(self.arities) == 1 and all(
            p.get("default") is None for p in self.covered[self.arities[0]]["params"]
        )

    def variants(self) -> list[list[dict]]:
        if self.simple:
            return [self.covered[self.arities[0]]["params"]]
        return [self.covered[k]["params"][:k] for k in self.arities]


def emit_framework(
    ruby_name: str,
    dispatch: Dispatch,
    invoke,
    tail: str,
    indent: str = "  ",
) -> list[str]:
    """Emit the body of a glue function.

    `invoke(args, indent)` returns the statements performing the call and the
    value conversion; `tail` is what the function answers when nothing raised.

    Every body is wrapped in `EXC_BEGIN`/`EXC_END`, even the one-arity ones: an
    `urge::Exception` thrown anywhere below the call (a GPU failure, a missing
    file, a disposed object) has to become a Ruby exception, and an exception
    escaping a C function of the VM is undefined behaviour.
    """
    lines: list[str] = [indent + "EXC_BEGIN {"]
    inner = indent + "  "
    if dispatch.simple:
        params = dispatch.variants()[0]
        plan = ParamPlan(params)
        lines.append(inner + "CheckArgc(argc, %d);" % len(params))
        lines.extend(inner + d for d in plan.declarations)
        lines.extend(plan.parse_args_lines(inner))
        if plan.declarations or plan.format:
            lines.append("")
        lines.extend(invoke(plan.args, inner))
    else:
        branch = inner
        nested = inner + "  "
        for index, params in enumerate(dispatch.variants()):
            keyword = "if" if index == 0 else "} else if"
            lines.append("%s%s (argc == %d) {" % (branch, keyword, len(params)))
            lines.append(
                "%s// %s(%s)"
                % (nested, ruby_name, ", ".join(p["name"] for p in params))
            )
            plan = ParamPlan(params)
            lines.extend(nested + d for d in plan.declarations)
            lines.extend(plan.parse_args_lines(nested))
            lines.extend(invoke(plan.args, nested))
        lines.append("%s} else {" % branch)
        lines.append(
            '%srb_raise(rb_eArgError, "%s", "wrong number of arguments");'
            % (nested, "%s")
        )
        lines.append("%s}" % branch)
    lines.append(indent + "}")
    lines.append(indent + "EXC_END;")
    lines.append(indent + tail)
    return lines


# ---------------------------------------------------------------------------
# Class emission
# ---------------------------------------------------------------------------


def emit_initialize(entry: dict) -> list[str]:
    name = entry["cpp_name"]
    dispatch = Dispatch(entry["constructors"])
    lines = ["  urge::RefPtr<urge::%s> obj = nullptr;" % name]

    def invoke(args: list[str], indent: str) -> list[str]:
        call = "obj = urge::MakeRefCounted<urge::%s>(%s)" % (name, ", ".join(args))
        return emit_call(call, indent)

    lines.extend(emit_framework("initialize", dispatch, invoke, "return SetupSelfData(self, obj.get());"))
    return ["RB_FUNC(%s_initialize) {" % name] + lines + ["}"]


def emit_initialize_copy(entry: dict) -> list[str]:
    name = entry["cpp_name"]
    return [
        "RB_FUNC(%s_initialize_copy) {" % name,
        "  VALUE other;",
        '  ParseArgs(argc, argv, "o", &other);',
        "",
        "  urge::RefPtr<urge::%s> obj = nullptr;" % name,
        "  EXC_BEGIN {",
        "    auto other_obj = GetObject<urge::%s>(other, k%sDataType);" % (name, name),
        "    obj = urge::MakeRefCounted<urge::%s>(other_obj);" % name,
        "  }",
        "  EXC_END;",
        "",
        "  return SetupSelfData(self, obj.get());",
        "}",
    ]


def emit_marshal(entry: dict) -> list[str]:
    name = entry["cpp_name"]
    return [
        "RB_FUNC(%s__dump) {" % name,
        "  auto* self_obj = GetSelfData<urge::%s>(self);" % name,
        "",
        "  EXC_BEGIN {",
        "    std::string result =",
        "        urge::%s::MarshalDump(urge::RefPtr<urge::%s>(self_obj));" % (name, name),
        "    return rb_str_new(result.data(), static_cast<long>(result.size()));",
        "  }",
        "  EXC_END;",
        "  return Qnil;",
        "}",
        "",
        "RB_FUNC(%s__load) {" % name,
        "  std::string data;",
        '  ParseArgs(argc, argv, "s", &data);',
        "",
        "  EXC_BEGIN {",
        "    VALUE obj = rb_obj_alloc(self);",
        "    auto ptr = urge::%s::MarshalLoad(data);" % name,
        "    return SetupSelfData(obj, ptr.get());",
        "  }",
        "  EXC_END;",
        "  return Qnil;",
        "}",
    ]


def emit_method(entry: dict, group: list[dict], is_static: bool) -> list[str]:
    name = entry["cpp_name"]
    head = group[0]
    dispatch = Dispatch(group)
    symbol = "%s_%s" % (name, head["cpp_name"])
    if is_static:
        receiver = "urge::%s::%s" % (name, head["cpp_name"])
    else:
        receiver = "self_obj->%s" % head["cpp_name"]
    return_type = head["return"]["cpp_type"]

    def invoke(args: list[str], indent: str) -> list[str]:
        return emit_return(return_type, "%s(%s)" % (receiver, ", ".join(args)), indent)

    lines = ["RB_FUNC(%s) {" % symbol]
    if not is_static:
        lines.append("  auto* self_obj = GetSelfData<urge::%s>(self);" % name)
        lines.append("")
    lines.extend(emit_framework(head["ruby_name"], dispatch, invoke, "return Qnil;"))
    lines.append("}")
    return lines


def attr_macro(entry: dict, attr: dict, static: bool, marshalable: set[str]) -> str:
    cpp_type = attr["cpp_type"]
    name = attr["cpp_name"]
    owner = entry["cpp_name"]
    inner = refptr_inner(cpp_type)
    if inner is not None:
        if static:
            return "BINDING_CLASS_ATTR_OBJECT(%s, urge::%s, %s, urge::%s, k%sDataType);" % (
                owner, owner, name, inner, inner,
            )
        macro = "BINDING_ATTR_OBJECT" if inner in marshalable else "BINDING_ATTR_OBJECT_REF"
        return "%s(%s, urge::%s, %s, urge::%s, k%sDataType);" % (
            macro, owner, owner, name, inner, inner,
        )
    prefix = "BINDING_CLASS_ATTR" if static else "BINDING_ATTR"
    if cpp_type in INT_RETURNS:
        suffix = "INT"
    elif cpp_type in ("float", "double"):
        suffix = "FLOAT"
    elif cpp_type == "bool":
        suffix = "BOOL"
    elif cpp_type == "std::vector<std::string>":
        suffix = "STRINGVECTOR"
    else:
        raise ValueError("no attribute macro for %r" % cpp_type)
    return "%s_%s(%s, urge::%s, %s);" % (prefix, suffix, owner, owner, name)


def emit_init_function(entry: dict) -> list[str]:
    name = entry["cpp_name"]
    lines = [
        # The tail block is written after this one in the file, so the call
        # below needs the declaration.
        "void Init%sBindingAppend(VALUE klass);" % name,
        "",
        "void Init%sBinding() {" % name,
    ]
    if entry["ruby_superclass"] == "Object":
        lines.append('  auto klass = rb_define_class("%s", rb_cObject);' % name)
    else:
        lines.append(
            '  auto parent = rb_const_get(rb_cObject, rb_intern("%s"));'
            % entry["ruby_superclass"]
        )
        lines.append('  auto klass = rb_define_class("%s", parent);' % name)
    lines.append("  rb_define_alloc_func(klass, ClassAllocate<&k%sDataType>);" % name)
    lines.append("")

    if entry["constructors"]:
        lines.append('  DefineMethod(klass, "initialize", %s_initialize);' % name)
    if entry["initialize_copy"]:
        lines.append('  DefineMethod(klass, "initialize_copy", %s_initialize_copy);' % name)
    for group in group_overloads(entry["instance_methods"]):
        lines.append(
            '  DefineMethod(klass, "%s", %s_%s);'
            % (group[0]["ruby_name"], name, group[0]["cpp_name"])
        )
    for key in ("get", "set"):
        item = (entry["index"] or {}).get(key)
        if item:
            lines.append(
                '  DefineMethod(klass, "%s", %s_%s);'
                % (item["ruby_name"], name, item["cpp_name"])
            )
    if entry["marshal"]["dump"] and entry["marshal"]["load"]:
        lines.append('  DefineMethod(klass, "_dump", %s__dump);' % name)
        lines.append('  DefineClassMethod(klass, "_load", %s__load);' % name)
    for group in group_overloads(entry["class_methods"]):
        lines.append(
            '  DefineClassMethod(klass, "%s", %s_%s);'
            % (group[0]["ruby_name"], name, group[0]["cpp_name"])
        )
    for attr in entry["attributes"]:
        lines.append('  DefineMethod(klass, "%s", %s_%s);' % (attr["name"], name, attr["cpp_name"]))
        lines.append(
            '  DefineMethod(klass, "%s", %s_%sEqual);' % (attr["setter"], name, attr["cpp_name"])
        )
    for attr in entry["class_attributes"]:
        lines.append(
            '  DefineClassMethod(klass, "%s", %s_%s);' % (attr["name"], name, attr["cpp_name"])
        )
        lines.append(
            '  DefineClassMethod(klass, "%s", %s_%sEqual);'
            % (attr["setter"], name, attr["cpp_name"])
        )
    lines.extend("  " + call for call in EXTRA_INIT_CALLS.get(name, []))
    lines.append("  Init%sBindingAppend(klass);" % name)
    lines.append("}")
    return lines


def emit_class(model: Model, entry: dict) -> list[str]:
    name = entry["cpp_name"]
    parent = exported_parent(model, entry)
    # The data type of a derived class points at its base's so that a value of
    # it is accepted where the base is expected; only an exported base has a
    # data type to point at.  See cruby_utils.h / Bindgen.md.
    declaration = (
        "RB_DEF_TYPE_INHERIT(%s, %s);" % (name, parent)
        if parent
        else "RB_DEF_TYPE(%s);" % name
    )
    lines = [
        "// " + "-" * 73,
        "// %s  (%s)" % (name, entry["export"]),
        "// " + "-" * 73,
        "",
        declaration,
        "",
    ]
    if entry["constructors"]:
        lines.extend(emit_initialize(entry))
        lines.append("")
    if entry["initialize_copy"]:
        lines.extend(emit_initialize_copy(entry))
        lines.append("")
    if entry["marshal"]["dump"] and entry["marshal"]["load"]:
        lines.extend(emit_marshal(entry))
        lines.append("")
    for group in group_overloads(entry["instance_methods"]):
        lines.extend(emit_method(entry, group, False))
        lines.append("")
    for group in group_overloads(entry["class_methods"]):
        lines.extend(emit_method(entry, group, True))
        lines.append("")
    for attr in entry["attributes"]:
        lines.append("// Attribute: %s (%s)" % (attr["name"], attr["cpp_type"]))
        lines.extend(format_macro(attr_macro(entry, attr, False, model.marshalable)))
        lines.append("")
    for attr in entry["class_attributes"]:
        lines.append("// Class attribute: %s (%s)" % (attr["name"], attr["cpp_type"]))
        lines.extend(format_macro(attr_macro(entry, attr, True, model.marshalable)))
        lines.append("")
    lines.extend(emit_init_function(entry))
    return lines


# ---------------------------------------------------------------------------
# Module emission
# ---------------------------------------------------------------------------


def emit_module_method(klass: str, group: list[dict]) -> list[str]:
    head = group[0]
    dispatch = Dispatch(group)
    symbol = "%s_%s" % (klass, head["cpp_name"])
    receiver = "urge::%s::Get()" % klass
    return_type = head["return"]["cpp_type"]

    def invoke(args: list[str], indent: str) -> list[str]:
        return emit_return(
            return_type, "%s.%s(%s)" % (receiver, head["cpp_name"], ", ".join(args)), indent
        )

    return ["RB_FUNC(%s) {" % symbol] + emit_framework(
        head["ruby_name"], dispatch, invoke, "return Qnil;"
    ) + ["}"]


def emit_module_attribute(klass: str, fn: dict) -> list[str]:
    """Module attributes read the Singleton through `Get()`.

    The IR splits a read/write pair into two entries because the setter's own
    return type is `void`; the getter below is the entry without `setter`.
    """
    # Every entry carries the value type of the attribute, which is what the
    # conversion has to be chosen from (see the instance attribute macros).
    cpp_type = fn["attr_value_type"]
    getter = "urge::%s::Get().Attr_%s" % (klass, fn["cpp_name"])
    symbol = "%s_%s" % (klass, fn["cpp_name"])
    if fn.get("setter"):
        inner = refptr_inner(cpp_type)
        if inner is not None:
            local, fmt, arg = "value", "o", "GetObject<urge::%s>(value, k%sDataType)" % (inner, inner)
        elif cpp_type in INT_RETURNS:
            local, fmt, arg = "value", "i", "value"
        elif cpp_type in ("float", "double"):
            local, fmt, arg = "value", "f", "static_cast<float>(value)"
        elif cpp_type == "bool":
            local, fmt, arg = "value", "b", "value != 0"
        elif cpp_type == "std::vector<std::string>":
            local, fmt, arg = "value", "o", "GetStringVector(value)"
        else:
            raise ValueError("unsupported module attribute type %r" % cpp_type)
        local_type = "VALUE" if fmt == "o" else SCALAR_PARAMS[cpp_type][1]
        initial = "Qnil" if fmt == "o" else "{}"
        return [
            "RB_FUNC(%sEqual) {" % symbol,
            "  %s %s = %s;" % (local_type, local, initial),
            "",
            "  EXC_BEGIN {",
            '    ParseArgs(argc, argv, "%s", &%s);' % (fmt, local),
            "    %s(%s);" % (getter, arg),
            "  }",
            "  EXC_END;",
            "  return Qnil;",
            "}",
        ]
    # `Attr_X()` answers `std::optional<ty>`; the getter always fills it in, the
    # same way the instance macros dereference it. A `RefPtr` attribute
    # dereferences twice: the optional, then the smart pointer.
    return ["RB_FUNC(%s) {" % symbol, "  EXC_BEGIN {"] + emit_return(
        cpp_type, "(*%s())" % getter, "    "
    ) + ["  }", "  EXC_END;", "  return Qnil;", "}"]


def emit_module(entry: dict) -> list[str]:
    name = entry["cpp_name"]
    lines = [
        "// " + "-" * 73,
        "// %s  (%s)" % (name, entry["export"]),
        "// " + "-" * 73,
        "",
    ]
    plain = [f for f in entry["functions"] if not f.get("attr")]
    for group in group_overloads(plain):
        lines.extend(emit_module_method(name, group))
        lines.append("")
    for fn in entry["functions"]:
        if fn.get("attr"):
            lines.extend(emit_module_attribute(name, fn))
            lines.append("")

    # The tail block is written after this one in the file, so the call below
    # needs the declaration.
    lines.append("void Init%sBindingAppend(VALUE mod);" % name)
    lines.append("")
    lines.append("void Init%sBinding() {" % name)
    lines.append('  auto mod = rb_define_module("%s");' % name)
    lines.append("")
    for group in group_overloads(plain):
        lines.append(
            '  DefineModuleFunction(mod, "%s", %s_%s);'
            % (group[0]["ruby_name"], name, group[0]["cpp_name"])
        )
    for fn in entry["functions"]:
        if fn.get("attr"):
            lines.append(
                '  DefineModuleFunction(mod, "%s", %s_%s%s);'
                % (fn["ruby_name"], name, fn["cpp_name"], "Equal" if fn.get("setter") else "")
            )
    lines.extend("  " + call for call in EXTRA_INIT_CALLS.get(name, []))
    lines.append("  Init%sBindingAppend(mod);" % name)
    lines.append("}")
    return lines


# ---------------------------------------------------------------------------
# File assembly
# ---------------------------------------------------------------------------


def cc_template() -> str:
    return "\n".join(
        [
            FILE_HEADER.rstrip("\n"),
            "",
            GENERATED_INCLUDES_BEGIN,
            GENERATED_INCLUDES_END,
            "",
            HANDWRITTEN_INCLUDES_BEGIN,
            HANDWRITTEN_INCLUDES_END,
            "",
            "namespace binding {",
            "",
            HANDWRITTEN_BEGIN,
            HANDWRITTEN_END,
            "",
            GENERATED_BEGIN,
            GENERATED_END,
            "",
            HANDWRITTEN_INIT_BEGIN,
            HANDWRITTEN_INIT_END,
            "",
            "}  // namespace binding",
            "",
        ]
    )


def default_init_append(name: str) -> str:
    """The tail block a freshly generated file starts with.

    The initialiser always calls `Init<Class>BindingAppend`, so the block has
    to define it even when the class needs no patch: an empty body is a no-op
    rather than a link error, and it doubles as the place to write one, with
    the class (`klass`) or module (`mod`) the initialiser built already in
    hand.
    """
    return "\n".join(
        [
            "// Runs at the end of Init%sBinding(), with the class (`klass`) or" % name,
            "// module (`mod`) the initialiser built in hand. Patches the IR",
            "// cannot express -- a proxy class, a method whose Ruby signature",
            "// differs from its C++ one -- belong here. The block is preserved",
            "// verbatim; empty it and the generator writes this body back.",
            "void Init%sBindingAppend(VALUE klass) {" % name,
            "  (void)klass;",
            "}",
        ]
    )


def splice(text: str, begin: str, end: str, body: str) -> str:
    i = text.index(begin) + len(begin)
    j = text.index(end)
    return text[:i] + "\n" + body + text[j:]


def region(text: str, begin: str, end: str) -> str:
    i = text.index(begin) + len(begin)
    j = text.index(end)
    return text[i:j].strip("\n")


def read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def write_text(path: str, text: str) -> None:
    """Write `text` to `path`, but only if that would actually change it.

    The repository is CRLF throughout; write it that way so regenerating never
    shows up as an end-of-line diff.

    The "only if it would change" part is load-bearing, not an optimisation.
    MSBuild decides what to rebuild by comparing timestamps, so rewriting a
    file with identical bytes still counts as a change and recompiles every
    translation unit that includes it.  Nothing here depends on the write
    having happened: the generators are deterministic, so the only caller that
    could care is one that reads the file back, and none does.  Skipping the
    write is what makes a re-run of the generators free.
    """
    text = text.replace("\r\n", "\n")
    if os.path.exists(path) and read_text(path) == text:
        return
    with open(path, "w", encoding="utf-8", newline="\r\n") as f:
        f.write(text)


def generate_cc(model: Model, entry: dict, path: str) -> None:
    file_name = os.path.basename(path)
    if os.path.exists(path):
        text = read_text(path)
        handwritten = region(text, HANDWRITTEN_BEGIN, HANDWRITTEN_END)
        handwritten_includes = region(
            text, HANDWRITTEN_INCLUDES_BEGIN, HANDWRITTEN_INCLUDES_END
        )
        # The tail block only exists in files written by a generator which
        # knows about it; a file from an older run gets the markers appended,
        # empty, so the run below has somewhere to put the block.
        if HANDWRITTEN_INIT_BEGIN not in text:
            text = text.replace(
                "\n}  // namespace binding",
                "\n" + HANDWRITTEN_INIT_BEGIN + "\n" + HANDWRITTEN_INIT_END
                + "\n\n}  // namespace binding",
            )
        handwritten_init = region(text, HANDWRITTEN_INIT_BEGIN, HANDWRITTEN_INIT_END)
    else:
        text = cc_template()
        handwritten = HANDWRITTEN_SEED.get(file_name, "").strip("\n")
        handwritten_includes = ""
        handwritten_init = ""

    refs = model.references(entry)
    binding_headers = ["binding_%s.h" % snake(r) for r in refs]
    # `RB_DEF_TYPE_INHERIT` names the base's data type, which its generated
    # header is what declares, so the entry's own base has to be included even
    # though no declaration of the class mentions it.
    parent = exported_parent(model, entry)
    if parent:
        binding_headers.append("binding_%s.h" % snake(parent))
    binding_headers = sorted(set(binding_headers))
    core_headers = sorted({entry["header"]} | {model.by_cpp_name[r]["header"] for r in refs})

    includes = ["#include \"binding_%s.h\"" % snake(entry["cpp_name"]), ""]
    includes += ["#include \"%s\"" % h for h in binding_headers]
    if binding_headers:
        includes.append("")
    includes += ["#include \"%s\"" % h for h in core_headers]

    text = splice(
        text, GENERATED_INCLUDES_BEGIN, GENERATED_INCLUDES_END,
        "\n".join(includes).strip("\n") + "\n",
    )
    text = splice(
        text, HANDWRITTEN_INCLUDES_BEGIN, HANDWRITTEN_INCLUDES_END,
        (handwritten_includes + "\n") if handwritten_includes else "",
    )
    text = splice(
        text, HANDWRITTEN_BEGIN, HANDWRITTEN_END,
        (handwritten + "\n") if handwritten else "",
    )
    # An empty tail block still has to define the function the generated
    # initialiser calls, so the default body is emitted when nothing is there.
    tail = handwritten_init or default_init_append(entry["cpp_name"])
    text = splice(
        text, HANDWRITTEN_INIT_BEGIN, HANDWRITTEN_INIT_END,
        tail + "\n",
    )

    body = emit_module(entry) if entry["kind"] == "module" else emit_class(model, entry)
    text = splice(text, GENERATED_BEGIN, GENERATED_END, "\n".join(body).strip("\n") + "\n")
    write_text(path, text)


def generate_init(model: Model, out_dir: str) -> None:
    write_text(
        os.path.join(out_dir, "binding_init.h"),
        """\
#pragma once

// Generated by bind/generate_binding.py -- do not edit.
// Rules: bind/Bindgen.md

#include "cruby_utils.h"

namespace binding {

// Defines the RGSS exception classes, every exported class and every exported
// module, in dependency order. Requires a live Ruby VM (`ruby_init()` must have
// run first) and redefines the classes when called again, so call it once.
void InitBindings();

}  // namespace binding
""",
    )

    path = os.path.join(out_dir, "binding_init.cc")
    if os.path.exists(path):
        text = read_text(path)
        handwritten = region(text, HANDWRITTEN_BEGIN, HANDWRITTEN_END)
    else:
        text = cc_template()
        handwritten = HANDWRITTEN_SEED.get("binding_init.cc", "").strip("\n")

    includes = ["#include \"binding_init.h\"", ""]
    includes += ['#include "binding_%s.h"' % snake(e["cpp_name"]) for e in model.all_entries()]
    body = [
        "namespace {",
        "",
        "// The RGSS exception classes the glue raises. A host entry point may",
        "// define them first, with parent classes of its own; this is the fallback",
        "// which keeps the binding library self sufficient.",
        "void DefineRGSSExceptions() {",
        "  if (NIL_P(g_reset_exception))",
        '    g_reset_exception = rb_define_class("RGSSReset", rb_eStandardError);',
        "  if (NIL_P(g_rgss_exception))",
        '    g_rgss_exception = rb_define_class("RGSSError", rb_eStandardError);',
        "}",
        "",
        "}  // namespace",
        "",
        "void InitBindings() {",
        "  DefineRGSSExceptions();",
        "",
    ]
    body += ["  Init%sBinding();" % e["cpp_name"] for e in model.all_entries()]
    body.append("}")

    text = splice(
        text, GENERATED_INCLUDES_BEGIN, GENERATED_INCLUDES_END,
        "\n".join(includes).strip("\n") + "\n",
    )
    text = splice(
        text, HANDWRITTEN_BEGIN, HANDWRITTEN_END,
        (handwritten + "\n") if handwritten else "",
    )
    text = splice(text, GENERATED_BEGIN, GENERATED_END, "\n".join(body) + "\n")
    write_text(path, text)


def prune_stale_outputs(model: Model, out_dir: str) -> list[tuple[str, bool]]:
    """Remove generated files whose entry is no longer in the IR.

    A class dropped from `core/` leaves `binding_<name>.{h,cc}` behind, and
    nothing else would ever clean them up: `bind/CMakeLists.txt` globs `*.cc`,
    so the leftovers keep being compiled -- against an API that no longer
    exists, which fails the build while pointing at a file nobody edited.

    "Should still exist" is decided by the IR, which is the only model this
    script has.  Two consequences worth stating, because they are deliberate:

      * a class that is still in `core/` but is no longer exported counts as
        gone.  Its glue would still compile against the class, but nothing
        calls the glue, and the file has already stopped tracking its header;
      * a rename is two different entries, so the old pair is removed and the
        new pair written in the same run.

    Hand-written *blocks* inside a generated file are not a reason to keep it:
    once the entry is gone there is no file to splice them back into, and the
    entry's fate decides theirs (see Bindgen.md, "残留文件清理").

    Only files whose banner carries GENERATED_MARKER are removed, so a
    hand-written file that merely matches `binding_*` survives.
    """
    entries = model.all_entries()
    if not entries:
        # A header the parser cannot read yields an empty model.  Sweeping on
        # that would delete the entire directory, so refuse and say so.
        print("  WARNING: the IR lists no entries -- skipping the stale-file sweep")
        return []

    expected = {"binding_init.h", "binding_init.cc"}
    for entry in entries:
        stem = "binding_%s" % snake(entry["cpp_name"])
        expected.add(stem + ".h")
        expected.add(stem + ".cc")

    removed: list[tuple[str, bool]] = []
    for name in sorted(os.listdir(out_dir)):
        if name in expected or not BINDING_OUTPUT_RE.match(name):
            continue
        path = os.path.join(out_dir, name)
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()
        except OSError:
            continue
        if GENERATED_MARKER not in text[:400]:
            print("  kept %s: not generated by this script" % name)
            continue
        # `region` uses str.index and raises on a missing marker, which is the
        # normal case for the `.h` files (they have no HANDWRITTEN block).
        if HANDWRITTEN_BEGIN in text and HANDWRITTEN_END in text:
            handwritten = region(text, HANDWRITTEN_BEGIN, HANDWRITTEN_END)
        else:
            handwritten = ""
        os.remove(path)
        removed.append((name, bool(handwritten.strip())))
    return removed


def main() -> int:
    ir_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_IR
    out_dir = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    with open(ir_path, "r", encoding="utf-8") as f:
        model = Model(json.load(f))

    for entry in model.all_entries():
        if entry["kind"] == "class":
            header = CLASS_HEADER % (entry["cpp_name"], entry["cpp_name"])
        else:
            header = MODULE_HEADER % entry["cpp_name"]
        write_text(os.path.join(out_dir, "binding_%s.h" % snake(entry["cpp_name"])), header)
        generate_cc(model, entry, os.path.join(out_dir, "binding_%s.cc" % snake(entry["cpp_name"])))
    generate_init(model, out_dir)

    print(
        "Generated %d classes, %d modules in %s"
        % (
            len(model.classes),
            len(model.modules),
            os.path.relpath(out_dir, REPO_ROOT).replace("\\", "/"),
        )
    )
    print("  marshalable: %s" % ", ".join(sorted(model.marshalable)))

    removed = prune_stale_outputs(model, out_dir)
    if removed:
        print("  removed %d file(s) whose entry is gone from the IR:" % len(removed))
        for name, had_handwritten in removed:
            print("    %s%s" % (name, "  [had hand-written glue]" if had_handwritten else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
